unit Unit29;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TForm29=class(TForm)
    QuickRep1: TQuickRep;
    QRSubDetail3: TQRSubDetail;
    SummaryBand1: TQRBand;
    QRShape118: TQRShape;
    QRShape108: TQRShape;
    QRShape107: TQRShape;
    QRShape106: TQRShape;
    QRShape105: TQRShape;
    QRShape104: TQRShape;
    QRShape119: TQRShape;
    QRShape117: TQRShape;
    QRShape116: TQRShape;
    QRShape122: TQRShape;
    QRShape115: TQRShape;
    QRShape126: TQRShape;
    QRShape124: TQRShape;
    QRShape153: TQRShape;
    QRShape99: TQRShape;
    QRShape98: TQRShape;
    QRShape97: TQRShape;
    QRShape96: TQRShape;
    QRShape95: TQRShape;
    QRShape94: TQRShape;
    QRShape93: TQRShape;
    QRShape92: TQRShape;
    QRShape91: TQRShape;
    QRShape90: TQRShape;
    QRShape89: TQRShape;
    QRShape88: TQRShape;
    QRShape87: TQRShape;
    QRShape86: TQRShape;
    QRShape85: TQRShape;
    QRShape84: TQRShape;
    QRShape83: TQRShape;
    QRShape3: TQRShape;
    QRShape2: TQRShape;
    QRShape164: TQRShape;
    QRShape163: TQRShape;
    QRShape162: TQRShape;
    QRShape161: TQRShape;
    QRShape160: TQRShape;
    QRShape159: TQRShape;
    QRShape158: TQRShape;
    QRShape157: TQRShape;
    QRShape156: TQRShape;
    QRShape154: TQRShape;
    QRShape152: TQRShape;
    QRShape151: TQRShape;
    QRShape150: TQRShape;
    QRShape148: TQRShape;
    QRShape147: TQRShape;
    QRShape146: TQRShape;
    QRShape145: TQRShape;
    QRShape142: TQRShape;
    QRShape141: TQRShape;
    QRShape140: TQRShape;
    QRShape133: TQRShape;
    QRShape132: TQRShape;
    QRShape131: TQRShape;
    QRShape130: TQRShape;
    QRShape129: TQRShape;
    QRShape128: TQRShape;
    QRShape127: TQRShape;
    QRShape125: TQRShape;
    QRShape123: TQRShape;
    QRShape121: TQRShape;
    QRShape120: TQRShape;
    QRShape114: TQRShape;
    QRShape113: TQRShape;
    QRShape112: TQRShape;
    QRShape111: TQRShape;
    QRShape110: TQRShape;
    QRShape109: TQRShape;
    QRShape103: TQRShape;
    QRShape102: TQRShape;
    QRShape101: TQRShape;
    QRShape100: TQRShape;
    QRShape1: TQRShape;
    QRLabel90: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel89: TQRLabel;
    QRLabel88: TQRLabel;
    QRLabel87: TQRLabel;
    QRLabel86: TQRLabel;
    QRLabel85: TQRLabel;
    QRLabel84: TQRLabel;
    QRLabel83: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel79: TQRLabel;
    QRLabel74: TQRLabel;
    QRLabel73: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel69: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel49: TQRLabel;
    QRLabel48: TQRLabel;
    QRLabel47: TQRLabel;
    QRLabel46: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel16: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel1: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel27: TQRLabel;
    QRLabel28: TQRLabel;
    QRDBText9: TQRDBText;
    QRLabel31: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel13: TQRLabel;
    QRDBText24: TQRDBText;
    QRDBText26: TQRDBText;
    QRDBText27: TQRDBText;
    QRDBText28: TQRDBText;
    QRDBText29: TQRDBText;
    QRDBText49: TQRDBText;
    QRLabel5: TQRLabel;
    QRDBText1: TQRDBText;
    QRDBText47: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText31: TQRDBText;
    QRDBText30: TQRDBText;
    QRDBText34: TQRDBText;
    procedure _PROC_0066B2B8(Sender : TObject);
    procedure _PROC_0066B2C0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form29: TForm29;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm29._PROC_0066B2B8(Sender : TObject);
begin
(*
0066B2B8   832DB0356B0001         sub     dword ptr [$006B35B0], +$01
0066B2BF   C3                     ret

*)
end;

procedure TForm29._PROC_0066B2C0(Sender : TObject);
begin
(*
0066B2C0   0CB3                   or      al, $B3
0066B2C2   660000                 add     [eax], al

*)
end;

end.