unit Unit18;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, acAlphaHints, ExtCtrls, SkinCtrls,
  spdbctrls, {acArcControls,} sEdit, acPNG, Buttons, sBitBtn, sSpeedButton,
  acImage, sLabel, sPanel;
type
  TPas=class(TForm)
    Timer1: TTimer;
    sAlphaHints1: TsAlphaHints;
    Notebook1: TNotebook;
    sPanel1: TsPanel;
    sImage1: TsImage;
    sLabelFX6: TsLabelFX;
    sLabelFX1: TsLabelFX;
    sLabelFX2: TsLabelFX;
    sLabelFX3: TsLabelFX;
    sImage2: TsImage;
    sImage3: TsImage;
    sEdit1: TsEdit;
    sPanel9: TsPanel;
    Edit1: TEdit;
    spSkinDBLookupComboBox1: TspSkinDBLookupComboBox;
    sEdit2: TsEdit;
    sPanel2: TsPanel;
    sImage4: TsImage;
    sLabelFX8: TsLabelFX;
    sLabelFX5: TsLabelFX;
    sLabelFX7: TsLabelFX;
    sSpeedButton2: TsSpeedButton;
    sLabelFX9: TsLabelFX;
    sLabelFX10: TsLabelFX;
    sPanel3: TsPanel;
    Edit2: TEdit;
    sBitBtn1: TsBitBtn;
    Edit3: TEdit;
    sPanel4: TsPanel;
    sLabelFX4: TsLabelFX;
    sImage7: TsImage;
    sImage8: TsImage;
    sSpeedButton8: TsSpeedButton;
    sSpeedButton1: TsSpeedButton;
    Label1: TLabel;
    sBitBtn2: TsBitBtn;
    sBitBtn32: TsBitBtn;
    procedure sBitBtn2Click(Sender : TObject);
    procedure sBitBtn32Click(Sender : TObject);
    procedure Timer1Timer(Sender : TObject);
    procedure sEdit1KeyDown1(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure sBitBtn1Click(Sender : TObject);
    procedure sEdit2KeyDown(Sender: TObject; var Key: Word;
      Shift: TShiftState);
    procedure sEdit1KeyDown(Sender: TObject; var Key: Word;
      Shift: TShiftState);
    procedure FormActivate(Sender: TObject);
    procedure spSkinDBLookupComboBox1Click(Sender: TObject);
  private
    { Private declarations }
  public
    nbr:Integer;
    { Public declarations }
  end;

var
  Pas: TPas;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation
    uses Unit1,Unit2;
{$R *.DFM}

procedure TPas.sBitBtn2Click(Sender : TObject);
begin
  //00655C4C
  Application.Terminate();
end;

procedure TPas.sBitBtn32Click(Sender : TObject);
begin
  //00655C5C
  if(sEdit1.Text = Data.ABSUsersPassword.Value )then begin

          { if(Pas.sEdit1.Text ='Faysoft19852017+*/')then begin
      end;

      Pas.sEdit2.Text:= Data.psType.Value;

      Form1.sTitleBar1.Items[1].Caption:=Data.psUser.Value+' || '+Data.psType.Value+' || '+'?? ????? ?????? ?? ???';
      }
      if(Data.ABSUserscompte.Value = 'User' ) then begin
        {if(Pas.sEdit1.Text = Data.psPass.Value)then begin

          Data.ps.Filter:= 'type=''+Pas.sEdit2.Text+'*'';
          Data.ps.Filtered:=True;
        end;}
      end
      else if(Data.ABSUserscompte.Value = 'Administrateur' ) then begin
        { if(Pas.sEdit1.Text = 'Faysoft19852017+*/')then begin
             Data.emp.First;
             while (not Data.emp.Eof) do begin
                 Data.emp.Next;
             end;
             Data.maj.First;
             while (not Data.maj.Eof) do begin
                Data.maj.Next;
             end;
             Form1.sSpeedButton5.Visible:=True;
             Form1.Timer2.Enabled:=True;
             Form1.sSpeedButton5.Visible:=False;
             Form1.Timer2.Enabled:=false;
             Data.psType.Value = 'User';
         end; }

      end;
    Form1.sTitleBar1.Items[1].Caption:='FAYCEL BOUDJIL || BOSS ||  „  ”ÃÌ· «·œŒÊ· „‰ ÿ—› ' ;
    Pas.Hide;
    Form1.Show;
  end
  else begin
   // Pas.sArcPreloader1.BaseColor:=$0FF0B;
    if(nbr=0)then begin
     ShowMessage('”Ì „ €·ﬁ «·»—‰«„Ã ... ‰«”› ⁄·Ï «·«“⁄«Ã');
     Application.Terminate;
    end
    else begin
     Pas.sPanel2.Visible:=True;
     //Pas.sArcPreloader1.Text:='ooooook';
     Pas.sLabelFX10.Caption:=IntToStr(nbr);
     Dec(nbr);
    end;


  end;

end;

procedure TPas.Timer1Timer(Sender : TObject);
var
  KeyState: TKeyboardState;
begin
  //006565FC
   GetKeyboardState(KeyState);
  if (KeyState[VK_CAPITAL] = 0) then
  begin
    Label1.Caption := 'Caps-Lock is OFF!';
    sImage8.Visible := True;
    sImage7.Visible := false;
  end
  else
  begin
    Label1.Caption := 'Caps-Lock is ON!';
    sImage8.Visible := false;
    sImage7.Visible := true;
  end;
end;

procedure TPas.sEdit1KeyDown1(Sender : TObject);
begin
(*
0065671C   55                     push    ebp
0065671D   8BEC                   mov     ebp, esp
0065671F   56                     push    esi
00656720   6683390D               cmp     word ptr [ecx], +$0D
00656724   750F                   jnz     00656735

* Reference to control TPas.sBitBtn32 : TsBitBtn
|
00656726   8B8000030000           mov     eax, [eax+$0300]
0065672C   66BEEBFF               mov     si, $FFEB

|
00656730   E897D7DAFF             call    00403ECC
00656735   5E                     pop     esi
00656736   5D                     pop     ebp
00656737   C20400                 ret     $0004

*)
end;

procedure TPas.FormShow(Sender : TObject);
begin
  //0065673C
    SetWindowPos(Handle,$0FF,Pas.Left,Pas.Top,Pas.Width,Pas.Height,$13);
end;

procedure TPas.sBitBtn1Click(Sender : TObject);
begin
  //006567F0
  Pas.sPanel2.Visible:=false;
end;

procedure TPas.sEdit2KeyDown(Sender: TObject; var Key: Word;
  Shift: TShiftState);
begin
 //======
end;

procedure TPas.sEdit1KeyDown(Sender: TObject; var Key: Word;
  Shift: TShiftState);
begin
 //======
end;

procedure TPas.FormActivate(Sender: TObject);
begin
 //00656764
 nbr:=5;
end;

procedure TPas.spSkinDBLookupComboBox1Click(Sender: TObject);
begin
      if(Data.ABSUserscompte.Value = 'User' ) then begin
          sEdit1.Text:='0000';
      end
      else if(Data.ABSUserscompte.Value = 'Administrateur' ) then begin
          sEdit1.Text:='1234';
      end;
end;

end.


