unit Unit24;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QuickRpt, QRCtrls, ExtCtrls;
type
  TForm24=class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape10: TQRShape;
    QRShape8: TQRShape;
    QRLabel1: TQRLabel;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRShape9: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRLabel7: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel14: TQRLabel;
    QRShape13: TQRShape;
    QRShape15: TQRShape;
    QRLabel15: TQRLabel;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    QRLabel46: TQRLabel;
    QRShape50: TQRShape;
    QRLabel53: TQRLabel;
    QRLabel54: TQRLabel;
    QRShape7: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel8: TQRLabel;
    QRSubDetail3: TQRSubDetail;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRShape49: TQRShape;
    SummaryBand1: TQRBand;
    QRShape34: TQRShape;
    QRShape43: TQRShape;
    QRShape45: TQRShape;
    QRShape47: TQRShape;
    QRLabel48: TQRLabel;
    QRLabel50: TQRLabel;
    QRLabel51: TQRLabel;
    QRLabel52: TQRLabel;
    QRDBText18: TQRDBText;
    QRDBText21: TQRDBText;
    QRDBText22: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText20: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText47: TQRDBText;
    QRDBText49: TQRDBText;
    QRDBText46: TQRDBText;
    QRDBText45: TQRDBText;
    QRLabel3: TQRLabel;
    QRLabel2: TQRLabel;
    QRDBText1: TQRDBText;
    QRLabel4: TQRLabel;
    QRDBText11: TQRDBText;
    procedure _PROC_006699D8(Sender : TObject);
    procedure _PROC_006699E0(Sender : TObject);
    procedure _PROC_00669B21(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form24: TForm24;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm24._PROC_006699D8(Sender : TObject);
begin
(*
006699D8   832D98356B0001         sub     dword ptr [$006B3598], +$01
006699DF   C3                     ret

*)
end;

procedure TForm24._PROC_006699E0(Sender : TObject);
begin
(*
006699E0   2C9A                   sub     al, $9A
006699E2   660000                 add     [eax], al

*)
end;

procedure TForm24._PROC_00669B21(Sender : TObject);
begin
(*
00669B21   0080A06600F8           add     [eax+$F80066A0], al
00669B27   0200                   add     al, byte ptr [eax]
00669B29   0000                   add     [eax], al

*)
end;

end.