unit Unit48;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QuickRpt, QRCtrls, ExtCtrls ;
type
  TForm48=class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape16: TQRShape;
    QRShape50: TQRShape;
    QRLabel1: TQRLabel;
    QRShape17: TQRShape;
    QRShape21: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRLabel16: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel41: TQRLabel;
    QRShape27: TQRShape;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRShape13: TQRShape;
    QRLabel5: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel53: TQRLabel;
    QRLabel60: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRShape26: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel25: TQRLabel;
    QRSubDetail3: TQRSubDetail;
    QRShape8: TQRShape;
    QRShape30: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape55: TQRShape;
    QRDBText18: TQRDBText;
    QRDBText43: TQRDBText;
    QRDBText44: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    SummaryBand1: TQRBand;
    QRShape34: TQRShape;
    QRShape42: TQRShape;
    QRShape46: TQRShape;
    QRLabel48: TQRLabel;
    QRDBText34: TQRDBText;
    QRDBText35: TQRDBText;
    QRDBText37: TQRDBText;
    QRDBText38: TQRDBText;
    QRDBText39: TQRDBText;
    QRShape53: TQRShape;
    QRDBText33: TQRDBText;
    QRShape31: TQRShape;
    QRLabel2: TQRLabel;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRLabel3: TQRLabel;
    QRDBText2: TQRDBText;
    QRDBText1: TQRDBText;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel4: TQRLabel;
    procedure _PROC_006755DC(Sender : TObject);
    procedure _PROC_006755E4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form48: TForm48;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm48._PROC_006755DC(Sender : TObject);
begin
(*
006755DC   832D60366B0001         sub     dword ptr [$006B3660], +$01
006755E3   C3                     ret

*)
end;

procedure TForm48._PROC_006755E4(Sender : TObject);
begin
(*
006755E4   305667                 xor     [esi+$67], dl
006755E7   0000                   add     [eax], al

*)
end;

end.