unit Unit44;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TForm44=class(TForm)
    sPanel2: TsPanel;
    sImage4: TsImage;
    sSpeedButton2: TsSpeedButton;
    sLabelFX1: TsLabelFX;
    sPanel3: TsPanel;
    sSpeedButton1: TsSpeedButton;
    Edit2: TEdit;
    sPanel1: TsPanel;
    sLabelFX2: TsLabelFX;
    sBitBtn32: TsBitBtn;
    procedure sBitBtn32Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_00610ECC(Sender : TObject);
    procedure _PROC_00610EFC(Sender : TObject);
    procedure _PROC_00610F04(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form44: TForm44;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm44.sBitBtn32Click(Sender : TObject);
begin
(*

* Reference to Form44
|
00610E98   A118336B00             mov     eax, dword ptr [$006B3318]

* Reference to: Forms.TCustomForm.Close()
|
00610E9D   E85616E7FF             call    004824F8
00610EA2   C3                     ret

*)
end;

procedure TForm44.FormShow(Sender : TObject);
begin
(*
00610EA4   53                     push    ebx
00610EA5   8BD8                   mov     ebx, eax
00610EA7   6A13                   push    $13

* Reference to field TForm44.OFFS_004C
|
00610EA9   8B434C                 mov     eax, [ebx+$4C]
00610EAC   50                     push    eax

* Reference to field TForm44.OFFS_0048
|
00610EAD   8B4348                 mov     eax, [ebx+$48]
00610EB0   50                     push    eax

* Reference to field TForm44.OFFS_0044
|
00610EB1   8B4344                 mov     eax, [ebx+$44]
00610EB4   50                     push    eax

* Reference to field TForm44.OFFS_0040
|
00610EB5   8B4340                 mov     eax, [ebx+$40]
00610EB8   50                     push    eax
00610EB9   6AFF                   push    $FF
00610EBB   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
00610EBD   E8CE9CE5FF             call    0046AB90
00610EC2   50                     push    eax

* Reference to: user32.SetWindowPos()
|
00610EC3   E8F86FDFFF             call    00407EC0
00610EC8   5B                     pop     ebx
00610EC9   C3                     ret

*)
end;

procedure TForm44._PROC_00610ECC(Sender : TObject);
begin
(*
00610ECC   55                     push    ebp
00610ECD   8BEC                   mov     ebp, esp
00610ECF   33C0                   xor     eax, eax
00610ED1   55                     push    ebp
00610ED2   68F10E6100             push    $00610EF1
00610ED7   64FF30                 push    dword ptr fs:[eax]
00610EDA   648920                 mov     fs:[eax], esp
00610EDD   FF051C336B00           inc     dword ptr [$006B331C]
00610EE3   33C0                   xor     eax, eax
00610EE5   5A                     pop     edx
00610EE6   59                     pop     ecx
00610EE7   59                     pop     ecx
00610EE8   648910                 mov     fs:[eax], edx

****** FINALLY
|
00610EEB   68F80E6100             push    $00610EF8
00610EF0   C3                     ret

00610EF1   E96E35DFFF             jmp     00404464
00610EF6   EBF8                   jmp     00610EF0

****** END
|
00610EF8   5D                     pop     ebp
00610EF9   C3                     ret

*)
end;

procedure TForm44._PROC_00610EFC(Sender : TObject);
begin
(*
00610EFC   832D1C336B0001         sub     dword ptr [$006B331C], +$01
00610F03   C3                     ret

*)
end;

procedure TForm44._PROC_00610F04(Sender : TObject);
begin
(*
00610F04   50                     push    eax
00610F05   0F6100                 punpcklwd MM0, [eax]
00610F08   0000                   add     [eax], al

*)
end;

end.