unit Unit17;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TForm17=class(TForm)
    QuickRep1: TQuickRep;
    QRShape4: TQRShape;
    QRSubDetail1: TQRSubDetail;
    QRLabel5: TQRLabel;
    QRShape52: TQRShape;
    QRLabel4: TQRLabel;
    QRLabel6: TQRLabel;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRShape7: TQRShape;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel23: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;
    QRDBText1: TQRDBText;
    QRDBText4: TQRDBText;
    QRLabel27: TQRLabel;
    QRLabel28: TQRLabel;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    QRShape34: TQRShape;
    QRShape35: TQRShape;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRDBText16: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText17: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    v: TQRShape;
    QRLabel31: TQRLabel;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel36: TQRLabel;
    QRLabel37: TQRLabel;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText18: TQRDBText;
    QRDBText19: TQRDBText;
    QRDBText20: TQRDBText;
    QRDBText21: TQRDBText;
    QRDBText22: TQRDBText;
    QRShape36: TQRShape;
    QRDBText24: TQRDBText;
    QRDBText25: TQRDBText;
    QRShape37: TQRShape;
    QRLabel7: TQRLabel;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRDBText27: TQRDBText;
    QRDBText23: TQRDBText;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRShape40: TQRShape;
    QRShape41: TQRShape;
    QRDBText31: TQRDBText;
    QRLabel3: TQRLabel;
    QRShape42: TQRShape;
    QRDBText32: TQRDBText;
    QRShape43: TQRShape;
    QRLabel8: TQRLabel;
    QRShape44: TQRShape;
    QRDBText33: TQRDBText;
    QRShape45: TQRShape;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRShape46: TQRShape;
    QRShape47: TQRShape;
    QRShape48: TQRShape;
    QRShape49: TQRShape;
    QRDBText34: TQRDBText;
    QRDBText35: TQRDBText;
    QRLabel38: TQRLabel;
    QRShape50: TQRShape;
    QRShape51: TQRShape;
    QRDBText36: TQRDBText;
    QRDirection: TQRLabel;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRLabel15: TQRLabel;
    QRLabel39: TQRLabel;
    procedure QRDirectionPrint(sender: TObject; var Value: String);
    procedure QRLabel15Print(sender: TObject; var Value: String);
    procedure QRLabel39Print(sender: TObject; var Value: String);
    procedure QRLabel1Print(sender: TObject; var Value: String);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form17: TForm17;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation
     uses unit2;
{$R *.DFM}

procedure TForm17.QRDirectionPrint(sender: TObject; var Value: String);
begin
  Value := '„œÌ—Ì… «· ﬂÊÌ‰ «·„Â‰Ì ·‹'+ Data.GetParametre('WEL');
end;

procedure TForm17.QRLabel15Print(sender: TObject; var Value: String);
begin
   Value := Data.GetParametre('Cfpa');
end;

procedure TForm17.QRLabel39Print(sender: TObject; var Value: String);
begin
  Value := Data.GetParametre('APC');
end;

procedure TForm17.QRLabel1Print(sender: TObject; var Value: String);
begin
   Value := Data.GetParametre('APC')+' ›Ì :'+FormatDateTime('dd/mm/yyyy', Now);
end;

end.
