unit Unit51;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, sGroupBox, ComCtrls, acProgressBar,
  Buttons, sBitBtn, sSpeedButton, sLabel, acPNG, ExtCtrls, acImage, sPanel;
type
  TSauvegarder=class(TForm)
    sPanel1: TsPanel;
    sImage1: TsImage;
    sPanel2: TsPanel;
    sPanel4: TsPanel;
    sSpeedButton8: TsSpeedButton;
    sLabelFX1: TsLabelFX;
    sImage2: TsImage;
    sBitBtn2: TsBitBtn;
    lb_fichier: TsBitBtn;
    sProgressBar1: TsProgressBar;
    sLabelFX2: TsLabelFX;
    sLabelFX3: TsLabelFX;
    sRadioGroup1: TsRadioGroup;
    procedure FormActivate(Sender : TObject);
    procedure lb_fichierClick(Sender : TObject);
    procedure sBitBtn2Click(Sender : TObject);
    procedure _PROC_0069A816(Sender : TObject);
    procedure _PROC_0069A8A1(Sender : TObject);
    procedure _PROC_0069A8D0(Sender : TObject);
    procedure _PROC_0069A8D8(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Sauvegarder: TSauvegarder;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TSauvegarder.FormActivate(Sender : TObject);
begin
(*
0069A1DC   53                     push    ebx
0069A1DD   8BD8                   mov     ebx, eax

* Possible String Reference to: ' ÕœÌÀ ﬁÊ«⁄œ «·»Ì«‰« '
|
0069A1DF   BA08A26900             mov     edx, $0069A208

* Reference to control TSauvegarder.sLabelFX1 : TsLabelFX
|
0069A1E4   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
0069A1EA   E8699FDCFF             call    00464158
0069A1EF   33D2                   xor     edx, edx

* Reference to control TSauvegarder.sProgressBar1 : TsProgressBar
|
0069A1F1   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Comctrls.TProgressBar.SetPosition(Integer)
|
0069A1F7   E84816DBFF             call    0044B844
0069A1FC   5B                     pop     ebx
0069A1FD   C3                     ret

*)
end;

procedure TSauvegarder.lb_fichierClick(Sender : TObject);
begin
(*
0069A220   55                     push    ebp
0069A221   8BEC                   mov     ebp, esp
0069A223   B90C000000             mov     ecx, $0000000C
0069A228   6A00                   push    $00
0069A22A   6A00                   push    $00
0069A22C   49                     dec     ecx
0069A22D   75F9                   jnz     0069A228
0069A22F   53                     push    ebx
0069A230   56                     push    esi
0069A231   8945FC                 mov     [ebp-$04], eax
0069A234   33C0                   xor     eax, eax
0069A236   55                     push    ebp

* Possible String Reference to: 'ÈÓù÷ˇÎä^[ãÂ]√'
|
0069A237   6871A66900             push    $0069A671
0069A23C   64FF30                 push    dword ptr fs:[eax]
0069A23F   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'C:\Windows\System32\sgsql.dll'
|
0069A242   B888A66900             mov     eax, $0069A688

|
0069A247   E81CFDD6FF             call    00409F68
0069A24C   84C0                   test    al, al
0069A24E   751B                   jnz     0069A26B

* Possible String Reference to: '«·‰”Œ…  Ã—Ì»Ì… ... ·ÕÃ“ «·‰”Œ… ﬂ«„·
|                                … Ì—ÃÏ «· Ê«’· „⁄ «·„»—„Ã'
|
0069A250   B9B0A66900             mov     ecx, $0069A6B0
0069A255   B201                   mov     dl, $01

* Reference to class Exception
|
0069A257   A140864000             mov     eax, dword ptr [$00408640]

* Reference to: Axctrls.TOleStream.Create(System.[DelphiInterfacePointer; Integer; IStream ])
|
0069A25C   E85F38D7FF             call    0040DAC0

|
0069A261   E836A2D6FF             call    0040449C
0069A266   E98A030000             jmp     0069A5F5

* Reference to Sauvegarder
|
0069A26B   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSauvegarder.sRadioGroup1 : TsRadioGroup
|
0069A26E   8B8028030000           mov     eax, [eax+$0328]

* Reference to field TsRadioGroup.OFFS_02A8
|
0069A274   8B80A8020000           mov     eax, [eax+$02A8]
0069A27A   83E801                 sub     eax, +$01
0069A27D   7213                   jb      0069A292
0069A27F   751E                   jnz     0069A29F
0069A281   8D4DF4                 lea     ecx, [ebp-$0C]
0069A284   33D2                   xor     edx, edx

* Possible String Reference to: ' ÕœÌœ „ﬂ«‰ Õ›Ÿ «·‰”Œ… «·«Õ Ì«ÿÌ…'
|
0069A286   B8F8A66900             mov     eax, $0069A6F8

|
0069A28B   E8E888E0FF             call    004A2B78
0069A290   EB0D                   jmp     0069A29F
0069A292   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: '..\GS-CFP\backup'
|
0069A295   BA24A76900             mov     edx, $0069A724

|
0069A29A   E879A8D6FF             call    00404B18
0069A29F   B201                   mov     dl, $01

* Reference to class TStringList
|
0069A2A1   A138B74100             mov     eax, dword ptr [$0041B738]

|
0069A2A6   E8F599D6FF             call    00403CA0
0069A2AB   8945F8                 mov     [ebp-$08], eax
0069A2AE   33C0                   xor     eax, eax
0069A2B0   55                     push    ebp

* Possible String Reference to: 'È¥û÷ˇÈπ˛ˇˇÉ}'
|
0069A2B1   68ABA56900             push    $0069A5AB
0069A2B6   64FF30                 push    dword ptr fs:[eax]
0069A2B9   648920                 mov     fs:[eax], esp
0069A2BC   8D55EC                 lea     edx, [ebp-$14]

* Reference to TData instance
|
0069A2BF   A1D8F06A00             mov     eax, dword ptr [$006AF0D8]
0069A2C4   8B00                   mov     eax, [eax]

* Reference to control TData.DossiersCible : TStringField
|
0069A2C6   8B801C0A0000           mov     eax, [eax+$0A1C]
0069A2CC   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TStringField.OFFS_60
|
0069A2CE   FF5160                 call    dword ptr [ecx+$60]
0069A2D1   8B45EC                 mov     eax, [ebp-$14]
0069A2D4   8B55F8                 mov     edx, [ebp-$08]

|
0069A2D7   E878FDFFFF             call    0069A054
0069A2DC   8B45F8                 mov     eax, [ebp-$08]
0069A2DF   8B10                   mov     edx, [eax]

* Possible reference to virtual method TStringList.OFFS_14
|
0069A2E1   FF5214                 call    dword ptr [edx+$14]
0069A2E4   85C0                   test    eax, eax
0069A2E6   750A                   jnz     0069A2F2

|
0069A2E8   E85BA2D6FF             call    00404548
0069A2ED   E903030000             jmp     0069A5F5
0069A2F2   33DB                   xor     ebx, ebx
0069A2F4   33C0                   xor     eax, eax
0069A2F6   8945F0                 mov     [ebp-$10], eax
0069A2F9   8B45F4                 mov     eax, [ebp-$0C]

|
0069A2FC   E83FAAD6FF             call    00404D40
0069A301   83F803                 cmp     eax, +$03
0069A304   7E0D                   jle     0069A313
0069A306   8D45F4                 lea     eax, [ebp-$0C]
0069A309   BA40A76900             mov     edx, $0069A740

|
0069A30E   E835AAD6FF             call    00404D48
0069A313   8D55E4                 lea     edx, [ebp-$1C]

* Reference to TForm1 instance
|
0069A316   A170FA6A00             mov     eax, dword ptr [$006AFA70]
0069A31B   8B00                   mov     eax, [eax]

* Reference to control TForm1.sLabelFX97 : TsLabelFX
|
0069A31D   8B804C090000           mov     eax, [eax+$094C]

* Reference to: Controls.TControl.GetText()
|
0069A323   E8009EDCFF             call    00464128
0069A328   8B4DE4                 mov     ecx, [ebp-$1C]
0069A32B   8D45E8                 lea     eax, [ebp-$18]
0069A32E   8B55F4                 mov     edx, [ebp-$0C]

|
0069A331   E856AAD6FF             call    00404D8C
0069A336   8B45E8                 mov     eax, [ebp-$18]

|
0069A339   E8E2FFD6FF             call    0040A320

* Reference to Sauvegarder
|
0069A33E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSauvegarder.sProgressBar1 : TsProgressBar
|
0069A341   8B801C030000           mov     eax, [eax+$031C]
0069A347   33D2                   xor     edx, edx

* Reference to: Comctrls.TProgressBar.SetPosition(Integer)
|
0069A349   E8F614DBFF             call    0044B844

* Reference to Sauvegarder
|
0069A34E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSauvegarder.sProgressBar1 : TsProgressBar
|
0069A351   8B801C030000           mov     eax, [eax+$031C]
0069A357   BA64000000             mov     edx, $00000064

* Reference to: Comctrls.TProgressBar.SetMax(Integer)
|
0069A35C   E8D314DBFF             call    0044B834
0069A361   8D4DE0                 lea     ecx, [ebp-$20]
0069A364   8BD3                   mov     edx, ebx
0069A366   8B45F8                 mov     eax, [ebp-$08]
0069A369   8B30                   mov     esi, [eax]

* Possible reference to virtual method TStringList.OFFS_0C
|
0069A36B   FF560C                 call    dword ptr [esi+$0C]
0069A36E   8B45E0                 mov     eax, [ebp-$20]

|
0069A371   E8F2FBD6FF             call    00409F68
0069A376   3C01                   cmp     al, $01
0069A378   0F85D3000000           jnz     0069A451
0069A37E   8D4DD8                 lea     ecx, [ebp-$28]
0069A381   8BD3                   mov     edx, ebx
0069A383   8B45F8                 mov     eax, [ebp-$08]
0069A386   8B30                   mov     esi, [eax]

* Possible reference to virtual method TStringList.OFFS_0C
|
0069A388   FF560C                 call    dword ptr [esi+$0C]
0069A38B   8B45D8                 mov     eax, [ebp-$28]
0069A38E   8D55DC                 lea     edx, [ebp-$24]

|
0069A391   E85AFED6FF             call    0040A1F0
0069A396   8B55DC                 mov     edx, [ebp-$24]

* Reference to Sauvegarder
|
0069A399   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSauvegarder.sLabelFX1 : TsLabelFX
|
0069A39C   8B800C030000           mov     eax, [eax+$030C]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
0069A3A2   E8B19DDCFF             call    00464158
0069A3A7   8B45F8                 mov     eax, [ebp-$08]
0069A3AA   8B10                   mov     edx, [eax]

* Possible reference to virtual method TStringList.OFFS_14
|
0069A3AC   FF5214                 call    dword ptr [edx+$14]
0069A3AF   50                     push    eax
0069A3B0   6BC364                 imul    eax, ebx, $64
0069A3B3   5A                     pop     edx
0069A3B4   8BCA                   mov     ecx, edx
0069A3B6   99                     cdq
0069A3B7   F7F9                   idiv    ecx 
0069A3B9   8BD0                   mov     edx, eax

* Reference to Sauvegarder
|
0069A3BB   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSauvegarder.sProgressBar1 : TsProgressBar
|
0069A3BE   8B801C030000           mov     eax, [eax+$031C]

* Reference to: Comctrls.TProgressBar.SetPosition(Integer)
|
0069A3C4   E87B14DBFF             call    0044B844

* Reference to TApplication instance
|
0069A3C9   A130F76A00             mov     eax, dword ptr [$006AF730]
0069A3CE   8B00                   mov     eax, [eax]

* Reference to: Forms.TApplication.ProcessMessages()
|
0069A3D0   E8D7B7DEFF             call    00485BAC
0069A3D5   6AFF                   push    $FF
0069A3D7   FF75F4                 push    dword ptr [ebp-$0C]
0069A3DA   8D55D0                 lea     edx, [ebp-$30]

* Reference to TForm1 instance
|
0069A3DD   A170FA6A00             mov     eax, dword ptr [$006AFA70]
0069A3E2   8B00                   mov     eax, [eax]

* Reference to control TForm1.sLabelFX97 : TsLabelFX
|
0069A3E4   8B804C090000           mov     eax, [eax+$094C]

* Reference to: Controls.TControl.GetText()
|
0069A3EA   E8399DDCFF             call    00464128
0069A3EF   FF75D0                 push    dword ptr [ebp-$30]
0069A3F2   6840A76900             push    $0069A740
0069A3F7   8D4DC8                 lea     ecx, [ebp-$38]
0069A3FA   8BD3                   mov     edx, ebx
0069A3FC   8B45F8                 mov     eax, [ebp-$08]
0069A3FF   8B30                   mov     esi, [eax]

* Possible reference to virtual method TStringList.OFFS_0C
|
0069A401   FF560C                 call    dword ptr [esi+$0C]
0069A404   8B45C8                 mov     eax, [ebp-$38]
0069A407   8D55CC                 lea     edx, [ebp-$34]

|
0069A40A   E8E1FDD6FF             call    0040A1F0
0069A40F   FF75CC                 push    dword ptr [ebp-$34]
0069A412   8D45D4                 lea     eax, [ebp-$2C]
0069A415   BA04000000             mov     edx, $00000004

|
0069A41A   E8E1A9D6FF             call    00404E00
0069A41F   8B45D4                 mov     eax, [ebp-$2C]

|
0069A422   E819ABD6FF             call    00404F40
0069A427   50                     push    eax
0069A428   8D4DC4                 lea     ecx, [ebp-$3C]
0069A42B   8BD3                   mov     edx, ebx
0069A42D   8B45F8                 mov     eax, [ebp-$08]
0069A430   8B30                   mov     esi, [eax]

* Possible reference to virtual method TStringList.OFFS_0C
|
0069A432   FF560C                 call    dword ptr [esi+$0C]
0069A435   8B45C4                 mov     eax, [ebp-$3C]

|
0069A438   E803ABD6FF             call    00404F40
0069A43D   50                     push    eax

* Reference to: kernel32.CopyFileA()
|
0069A43E   E8E5CDD6FF             call    00407228
0069A443   83F801                 cmp     eax, +$01
0069A446   1BC0                   sbb     eax, eax
0069A448   40                     inc     eax
0069A449   84C0                   test    al, al
0069A44B   7503                   jnz     0069A450
0069A44D   FF45F0                 inc     dword ptr [ebp-$10]
0069A450   43                     inc     ebx
0069A451   8B45F8                 mov     eax, [ebp-$08]
0069A454   8B10                   mov     edx, [eax]

* Possible reference to virtual method TStringList.OFFS_14
|
0069A456   FF5214                 call    dword ptr [edx+$14]
0069A459   3BD8                   cmp     ebx, eax
0069A45B   0F8C00FFFFFF           jl      0069A361
0069A461   33C0                   xor     eax, eax
0069A463   5A                     pop     edx
0069A464   59                     pop     ecx
0069A465   59                     pop     ecx
0069A466   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'É}'
|
0069A469   68B5A56900             push    $0069A5B5
0069A46E   FF75F4                 push    dword ptr [ebp-$0C]
0069A471   8D55BC                 lea     edx, [ebp-$44]

* Reference to TForm1 instance
|
0069A474   A170FA6A00             mov     eax, dword ptr [$006AFA70]
0069A479   8B00                   mov     eax, [eax]

* Reference to control TForm1.sLabelFX97 : TsLabelFX
|
0069A47B   8B804C090000           mov     eax, [eax+$094C]

* Reference to: Controls.TControl.GetText()
|
0069A481   E8A29CDCFF             call    00464128
0069A486   FF75BC                 push    dword ptr [ebp-$44]
0069A489   6840A76900             push    $0069A740

* Possible String Reference to: 'Backup.INI'
|
0069A48E   684CA76900             push    $0069A74C
0069A493   8D45C0                 lea     eax, [ebp-$40]
0069A496   BA04000000             mov     edx, $00000004

|
0069A49B   E860A9D6FF             call    00404E00
0069A4A0   8B4DC0                 mov     ecx, [ebp-$40]
0069A4A3   B201                   mov     dl, $01

* Reference to class TIniFile
|
0069A4A5   A1341B4400             mov     eax, dword ptr [$00441B34]

* Reference to: Axctrls.TOleStream.Create(System.[DelphiInterfacePointer; Integer; IStream ])
|
0069A4AA   E83577DAFF             call    00441BE4
0069A4AF   8BD8                   mov     ebx, eax
0069A4B1   8D55B8                 lea     edx, [ebp-$48]

* Reference to TData instance
|
0069A4B4   A1D8F06A00             mov     eax, dword ptr [$006AF0D8]
0069A4B9   8B00                   mov     eax, [eax]

* Reference to control TData.DossiersCode : TStringField
|
0069A4BB   8B80100A0000           mov     eax, [eax+$0A10]
0069A4C1   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TStringField.OFFS_60
|
0069A4C3   FF5160                 call    dword ptr [ecx+$60]
0069A4C6   8B45B8                 mov     eax, [ebp-$48]
0069A4C9   50                     push    eax

* Possible String Reference to: 'code'
|
0069A4CA   B960A76900             mov     ecx, $0069A760

* Possible String Reference to: 'Backup'
|
0069A4CF   BA70A76900             mov     edx, $0069A770
0069A4D4   8BC3                   mov     eax, ebx
0069A4D6   8B30                   mov     esi, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
0069A4D8   FF5604                 call    dword ptr [esi+$04]
0069A4DB   8D55B4                 lea     edx, [ebp-$4C]

* Reference to TData instance
|
0069A4DE   A1D8F06A00             mov     eax, dword ptr [$006AF0D8]
0069A4E3   8B00                   mov     eax, [eax]

* Reference to control TData.DossiersNom : TStringField
|
0069A4E5   8B80140A0000           mov     eax, [eax+$0A14]
0069A4EB   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TStringField.OFFS_60
|
0069A4ED   FF5160                 call    dword ptr [ecx+$60]
0069A4F0   8B45B4                 mov     eax, [ebp-$4C]
0069A4F3   50                     push    eax

* Possible String Reference to: 'Nom'
|
0069A4F4   B980A76900             mov     ecx, $0069A780

* Possible String Reference to: 'Backup'
|
0069A4F9   BA70A76900             mov     edx, $0069A770
0069A4FE   8BC3                   mov     eax, ebx
0069A500   8B30                   mov     esi, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
0069A502   FF5604                 call    dword ptr [esi+$04]
0069A505   FF75F4                 push    dword ptr [ebp-$0C]

* Possible String Reference to: 'Dossier'
|
0069A508   688CA76900             push    $0069A78C
0069A50D   8D55AC                 lea     edx, [ebp-$54]

* Reference to TForm1 instance
|
0069A510   A170FA6A00             mov     eax, dword ptr [$006AFA70]
0069A515   8B00                   mov     eax, [eax]

* Reference to control TForm1.sLabelFX97 : TsLabelFX
|
0069A517   8B804C090000           mov     eax, [eax+$094C]

* Reference to: Controls.TControl.GetText()
|
0069A51D   E8069CDCFF             call    00464128
0069A522   FF75AC                 push    dword ptr [ebp-$54]
0069A525   6840A76900             push    $0069A740
0069A52A   8D45B0                 lea     eax, [ebp-$50]
0069A52D   BA04000000             mov     edx, $00000004

|
0069A532   E8C9A8D6FF             call    00404E00
0069A537   8B45B0                 mov     eax, [ebp-$50]
0069A53A   50                     push    eax

* Possible String Reference to: 'Emplacement'
|
0069A53B   B99CA76900             mov     ecx, $0069A79C

* Possible String Reference to: 'Backup'
|
0069A540   BA70A76900             mov     edx, $0069A770
0069A545   8BC3                   mov     eax, ebx
0069A547   8B30                   mov     esi, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
0069A549   FF5604                 call    dword ptr [esi+$04]
0069A54C   8D55A8                 lea     edx, [ebp-$58]

* Reference to TForm1 instance
|
0069A54F   A170FA6A00             mov     eax, dword ptr [$006AFA70]
0069A554   8B00                   mov     eax, [eax]

* Reference to control TForm1.sLabelFX97 : TsLabelFX
|
0069A556   8B804C090000           mov     eax, [eax+$094C]

* Reference to: Controls.TControl.GetText()
|
0069A55C   E8C79BDCFF             call    00464128
0069A561   8B45A8                 mov     eax, [ebp-$58]
0069A564   50                     push    eax

* Possible String Reference to: 'Date'
|
0069A565   B9B0A76900             mov     ecx, $0069A7B0

* Possible String Reference to: 'Backup'
|
0069A56A   BA70A76900             mov     edx, $0069A770
0069A56F   8BC3                   mov     eax, ebx
0069A571   8B30                   mov     esi, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
0069A573   FF5604                 call    dword ptr [esi+$04]

* Possible String Reference to: '·«” ⁄«œ… «·»Ì«‰«  «‰”Œ «·„·›«  «·„—
|                                ›ﬁ… ≈·Ï „·› DATA'
|
0069A576   68C0A76900             push    $0069A7C0

* Possible String Reference to: 'OBSERV'
|
0069A57B   B9FCA76900             mov     ecx, $0069A7FC

* Possible String Reference to: 'Backup'
|
0069A580   BA70A76900             mov     edx, $0069A770
0069A585   8BC3                   mov     eax, ebx
0069A587   8B30                   mov     esi, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
0069A589   FF5604                 call    dword ptr [esi+$04]

* Possible String Reference to: 'FAYCEL BOUDJIL'
|
0069A58C   680CA86900             push    $0069A80C

* Possible String Reference to: 'BOSS'
|
0069A591   B924A86900             mov     ecx, $0069A824

* Possible String Reference to: 'Backup'
|
0069A596   BA70A76900             mov     edx, $0069A770
0069A59B   8BC3                   mov     eax, ebx
0069A59D   8B18                   mov     ebx, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
0069A59F   FF5304                 call    dword ptr [ebx+$04]
0069A5A2   8B45F8                 mov     eax, [ebp-$08]

|
0069A5A5   E82697D6FF             call    00403CD0
0069A5AA   C3                     ret

0069A5AB   E9B49ED6FF             jmp     00404464
0069A5B0   E9B9FEFFFF             jmp     0069A46E

****** END
|
0069A5B5   837DF000               cmp     dword ptr [ebp-$10], +$00
0069A5B9   7E32                   jle     0069A5ED

* Possible String Reference to: '⁄œœ «·√Œÿ«¡:'
|
0069A5BB   6834A86900             push    $0069A834
0069A5C0   8D55A0                 lea     edx, [ebp-$60]
0069A5C3   8B45F0                 mov     eax, [ebp-$10]

|
0069A5C6   E83DF3D6FF             call    00409908
0069A5CB   FF75A0                 push    dword ptr [ebp-$60]

* Possible String Reference to: ' Œÿ√ '
|
0069A5CE   684CA86900             push    $0069A84C

* Possible String Reference to: '›Ì ‰”Œ ﬁÊ«⁄œ «·»Ì«‰«  ... «·‰”Œ… «·
|                                «Õ Ì«ÿÌ… „ÊÃÊœ… „”»ﬁ«'
|
0069A5D3   685CA86900             push    $0069A85C
0069A5D8   8D45A4                 lea     eax, [ebp-$5C]
0069A5DB   BA04000000             mov     edx, $00000004

|
0069A5E0   E81BA8D6FF             call    00404E00
0069A5E5   8B45A4                 mov     eax, [ebp-$5C]

* Reference to: Dialogs.ShowMessage(System.AnsiString)
|
0069A5E8   E837F7D9FF             call    00439D24

* Reference to Sauvegarder
|
0069A5ED   8B45FC                 mov     eax, [ebp-$04]

* Reference to: Forms.TCustomForm.Close()
|
0069A5F0   E8037FDEFF             call    004824F8
0069A5F5   33C0                   xor     eax, eax
0069A5F7   5A                     pop     edx
0069A5F8   59                     pop     ecx
0069A5F9   59                     pop     ecx
0069A5FA   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[ãÂ]√'
|
0069A5FD   6878A66900             push    $0069A678
0069A602   8D45A0                 lea     eax, [ebp-$60]
0069A605   BA02000000             mov     edx, $00000002

|
0069A60A   E895A4D6FF             call    00404AA4
0069A60F   8D45A8                 lea     eax, [ebp-$58]
0069A612   BA02000000             mov     edx, $00000002

|
0069A617   E888A4D6FF             call    00404AA4
0069A61C   8D45B0                 lea     eax, [ebp-$50]
0069A61F   BA03000000             mov     edx, $00000003

|
0069A624   E87BA4D6FF             call    00404AA4
0069A629   8D45BC                 lea     eax, [ebp-$44]

|
0069A62C   E84FA4D6FF             call    00404A80
0069A631   8D45C0                 lea     eax, [ebp-$40]
0069A634   BA04000000             mov     edx, $00000004

|
0069A639   E866A4D6FF             call    00404AA4
0069A63E   8D45D0                 lea     eax, [ebp-$30]

|
0069A641   E83AA4D6FF             call    00404A80
0069A646   8D45D4                 lea     eax, [ebp-$2C]
0069A649   BA04000000             mov     edx, $00000004

|
0069A64E   E851A4D6FF             call    00404AA4
0069A653   8D45E4                 lea     eax, [ebp-$1C]

|
0069A656   E825A4D6FF             call    00404A80
0069A65B   8D45E8                 lea     eax, [ebp-$18]
0069A65E   BA02000000             mov     edx, $00000002

|
0069A663   E83CA4D6FF             call    00404AA4
0069A668   8D45F4                 lea     eax, [ebp-$0C]

|
0069A66B   E810A4D6FF             call    00404A80
0069A670   C3                     ret

0069A671   E9EE9DD6FF             jmp     00404464
0069A676   EB8A                   jmp     0069A602

****** END
|
0069A678   5E                     pop     esi
0069A679   5B                     pop     ebx
0069A67A   8BE5                   mov     esp, ebp
0069A67C   5D                     pop     ebp
0069A67D   C3                     ret

*)
end;

procedure TSauvegarder.sBitBtn2Click(Sender : TObject);
begin
(*

* Reference to: Forms.TCustomForm.Close()
|
0069A898   E85B7CDEFF             call    004824F8
0069A89D   C3                     ret

*)
end;

procedure TSauvegarder._PROC_0069A816(Sender : TObject);
begin
(*
0069A816   44                     inc     esp
0069A817   4A                     dec     edx
0069A818   49                     dec     ecx
0069A819   4C                     dec     esp
0069A81A   0000                   add     [eax], al

*)
end;

procedure TSauvegarder._PROC_0069A8A1(Sender : TObject);
begin
(*
0069A8A1   8BEC                   mov     ebp, esp
0069A8A3   33C0                   xor     eax, eax
0069A8A5   55                     push    ebp

* Possible String Reference to: 'Èöõ÷ˇÎ¯]√ã¿É-¨6k'
|
0069A8A6   68C5A86900             push    $0069A8C5
0069A8AB   64FF30                 push    dword ptr fs:[eax]
0069A8AE   648920                 mov     fs:[eax], esp
0069A8B1   FF05AC366B00           inc     dword ptr [$006B36AC]
0069A8B7   33C0                   xor     eax, eax
0069A8B9   5A                     pop     edx
0069A8BA   59                     pop     ecx
0069A8BB   59                     pop     ecx
0069A8BC   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-¨6k'
|
0069A8BF   68CCA86900             push    $0069A8CC
0069A8C4   C3                     ret

0069A8C5   E99A9BD6FF             jmp     00404464
0069A8CA   EBF8                   jmp     0069A8C4

****** END
|
0069A8CC   5D                     pop     ebp
0069A8CD   C3                     ret

*)
end;

procedure TSauvegarder._PROC_0069A8D0(Sender : TObject);
begin
(*
0069A8D0   832DAC366B0001         sub     dword ptr [$006B36AC], +$01
0069A8D7   C3                     ret

*)
end;

procedure TSauvegarder._PROC_0069A8D8(Sender : TObject);
begin
(*
0069A8D8   24A9                   and     al, $A9
0069A8DA   690000000000           imul    eax, [eax], $00000000
0069A8E0   0000                   add     [eax], al

*)
end;

end.