unit Unit16;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TForm16=class(TForm)
    QuickRep1: TQuickRep;
    QRSubDetail3: TQRSubDetail;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel6: TQRLabel;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRDBText1: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText9: TQRDBText;
    QRLabel23: TQRLabel;
    QRShape21: TQRShape;
    QRDBText10: TQRDBText;
    QRDBText24: TQRDBText;
    QRDBText11: TQRDBText;
    procedure _PROC_00654084(Sender : TObject);
    procedure _PROC_0065408D(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form16: TForm16;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm16._PROC_00654084(Sender : TObject);
begin
(*
00654084   832D44356B0001         sub     dword ptr [$006B3544], +$01
0065408B   C3                     ret

*)
end;

procedure TForm16._PROC_0065408D(Sender : TObject);
begin
(*
0065408D   40                     inc     eax
0065408E   650003                 add     gs:[ebx], al
00654091   11545072               adc     [eax+edx*2+$72], edx
00654095   6F                     outsd
00654096   677265                 jb      006540FE
00654099   7373                   jnb     0065410E
0065409B   42                     inc     edx
0065409C   61                     popa
0065409D   7253                   jb      006540F2
0065409F   7479                   jz      0065411A
006540A1   6C                     insb
006540A2   650100                 add     gs:[eax], eax
006540A5   0000                   add     [eax], al

006540A7   0001                   add     [ecx], al
006540A9   0000                   add     [eax], al

006540AB   008C4065000A70         add     [eax+eax*2+$700A0065], cl
006540B2   627374                 bound   esi, qword ptr [ebx+$74]
006540B5   4E                     dec     esi
006540B6   6F                     outsd
006540B7   726D                   jb      00654126
006540B9   61                     popa
006540BA   6C                     insb
006540BB   0B7062                 or      esi, [eax+$62]
006540BE   7374                   jnb     00654134
006540C0   4D                     dec     ebp
006540C1   61                     popa
006540C2   7271                   jb      00654135
006540C4   7565                   jnz     0065412B
006540C6   650D61635072           or      eax, $72506361
006540CC   6F                     outsd
006540CD   677265                 jb      00654135
006540D0   7373                   jnb     00654145
006540D2   42                     inc     edx
006540D3   61                     popa
006540D4   728D                   jb      00654063
006540D6   40                     inc     eax
006540D7   002441                 add     [ecx+eax*2], ah
006540DA   650000                 add     gs:[eax], al
006540DD   0000                   add     [eax], al

006540DF   0000                   add     [eax], al

006540E1   0000                   add     [eax], al

006540E3   00EC                   add     ah, ch
006540E5   41                     inc     ecx
006540E6   650010                 add     gs:[eax], dl
006540E9   42                     inc     edx
006540EA   650000                 add     gs:[eax], al
006540ED   0000                   add     [eax], al

006540EF   0000                   add     [eax], al

006540F1   0000                   add     [eax], al

006540F3   0000                   add     [eax], al

006540F5   0000                   add     [eax], al

006540F7   00FE                   add     dh, bh
006540F9   41                     inc     ecx
006540FA   6500540200             add     gs:[edx+eax+$00], dl
006540FF   00A85E44000C           add     [eax+$C00445E], ch
00654105   694200D0426500         imul    eax, [edx+$00], $006542D0
0065410C   60                     pusha
0065410D   624200                 bound   eax, qword ptr [edx+$00]
00654110   2C3F                   sub     al, $3F
00654112   40                     inc     eax
00654113   00EC                   add     ah, ch
00654115   854600                 test    [esi+$00], eax
00654118   683C400084             push    $8400403C
0065411D   3C40                   cmp     al, $40
0065411F   00F4                   add     ah, dh
00654121   43                     inc     ebx
00654122   6500A8B64600B4         add     gs:[eax+$B40046B6], ch
00654129   7D46                   jnl     00654171
0065412B   0088E1410074           add     [eax+$740041E1], cl
00654131   45                     inc     ebp
00654132   6500D0                 add     al, dl
00654135   354600686A             xor     eax, $6A680046
0065413A   46                     inc     esi
0065413B   0010                   add     [eax], dl
0065413D   3F                     aas
0065413E   46                     inc     esi
0065413F   002469                 add     [ecx+ebp*2], ah
00654142   42                     inc     edx
00654143   000C66                 add     [esi], cl
00654146   42                     inc     edx
00654147   000466                 add     [esi], al
0065414A   42                     inc     edx
0065414B   002C69                 add     [ecx+ebp*2], ch
0065414E   42                     inc     edx
0065414F   0008                   add     [eax], cl
00654151   43                     inc     ebx
00654152   6500BCB14600D8B6       add     gs:[ecx+esi*4+$B6D80046], bh
0065415A   46                     inc     esi
0065415B   0024B6                 add     [esi+esi*4], ah
0065415E   46                     inc     esi
0065415F   00443446               add     [esp+esi+$46], al
00654163   0038                   add     [eax], bh
00654165   AC                     lodsb
00654166   46                     inc     esi
00654167   0058AC                 add     [eax-$54], bl
0065416A   46                     inc     esi
0065416B   0038                   add     [eax], bh
0065416D   A946008C33             test    eax, $338C0046
00654172   46                     inc     esi
00654173   009033460004           add     [eax+$4004633], dl
00654179   6446                   inc     esi
0065417B   0030                   add     [eax], dh
0065417D   6446                   inc     esi
0065417F   00F8                   add     al, bh
00654181   3E46                   inc     esi
00654183   0008                   add     [eax], cl
00654185   3546008440             xor     eax, $40840046
0065418A   46                     inc     esi
0065418B   00FC                   add     ah, bh
0065418D   3F                     aas
0065418E   46                     inc     esi
0065418F   0010                   add     [eax], dl
00654191   43                     inc     ebx
00654192   46                     inc     esi
00654193   00BC4146004C52         add     [ecx+eax*2+$524C0046], bh
0065419A   6500B4644600C4A9       add     gs:[esp+$A9C40046], dh
006541A2   46                     inc     esi
006541A3   0080AA460044           add     [eax+$440046AA], al
006541A9   A5                     movsd
006541AA   46                     inc     esi
006541AB   0064AA46               add     [edx+ebp*4+$46], ah
006541AF   00E0                   add     al, ah
006541B1   6A46                   push    $46
006541B3   00747146               add     [ecx+esi*2+$46], dh
006541B7   00147F                 add     [edi+edi*2], dl
006541BA   46                     inc     esi
006541BB   007855                 add     [eax+$55], bh
006541BE   6500FC                 add     ah, bh
006541C1   7B46                   jnp     00654209
006541C3   00B8556500AC           add     [eax+$AC006555], bh
006541C9   7F46                   jnle    00654211
006541CB   00B07F460068           add     [eax+$6800467F], dh
006541D1   7E46                   jle     00654219
006541D3   0008                   add     [eax], cl
006541D5   B644                   mov     dh, $44
006541D7   00A4AB46005888         add     [ebx+ebp*4+$88580046], ah
006541DE   46                     inc     esi
006541DF   0098BD4600E8           add     [eax+$E80046BD], bl
006541E5   A7                     cmpsd
006541E6   46                     inc     esi
006541E7   0010                   add     [eax], dl
006541E9   AB                     stosd
006541EA   46                     inc     esi
006541EB   000E                   add     [esi], cl
006541ED   0000                   add     [eax], al

006541EF   0000                   add     [eax], al

006541F1   0001                   add     [ecx], al
006541F3   0000                   add     [eax], al

006541F5   000411                 add     [ecx+edx], al
006541F8   40                     inc     eax
006541F9   00440200               add     [edx+eax+$00], al
006541FD   000D54735072           add     [$72507354], cl
00654203   6F                     outsd
00654204   677265                 jb      0065426C
00654207   7373                   jnb     0065427C
00654209   42                     inc     edx
0065420A   61                     popa
0065420B   7210                   jb      0065421D
0065420D   42                     inc     edx
0065420E   650007                 add     gs:[edi], al
00654211   0D54735072             or      eax, $72507354
00654216   6F                     outsd
00654217   677265                 jb      0065427F
0065421A   7373                   jnb     0065428F
0065421C   42                     inc     edx
0065421D   61                     popa
0065421E   7224                   jb      00654244
00654220   41                     inc     ecx
00654221   6500CC                 add     ah, cl
00654224   5F                     pop     edi
00654225   44                     inc     esp
00654226   002F                   add     [edi], ch
00654228   000D61635072           add     [$72506361], cl
0065422E   6F                     outsd
0065422F   677265                 jb      00654297
00654232   7373                   jnb     006542A7
00654234   42                     inc     edx
00654235   61                     popa
00654236   7204                   jb      0065423C
00654238   000411                 add     [ecx+edx], al
0065423B   40                     inc     eax
0065423C   00440200               add     [edx+eax+$00], al
00654240   FFC8                   dec     eax
00654242   50                     push    eax
00654243   650001                 add     gs:[ecx], al
00654246   0000                   add     [eax], al

00654248   0000                   add     [eax], al

0065424A   0000                   add     [eax], al

0065424C   800000                 add     byte ptr [eax], $00
0065424F   00802B000C50           add     [eax+$500C002B], al
00654255   726F                   jb      006542C6
00654257   677265                 jb      006542BF
0065425A   7373                   jnb     006542CF
0065425C   53                     push    ebx
0065425D   6B696E04               imul    ebp, [ecx+$6E], $04
00654261   015700                 add     [edi+$00], edx
00654264   40                     inc     eax
00654265   0200                   add     al, byte ptr [eax]
00654267   FF4002                 inc     dword ptr [eax+$02]
0065426A   00FF                   add     bh, bh
0065426C   0100                   add     [eax], eax
0065426E   0000                   add     [eax], al

00654270   0000                   add     [eax], al

00654272   008000000080           add     [eax+$80000000], al
00654278   2C00                   sub     al, $00
0065427A   08536B                 or      [ebx+$6B], dl
0065427D   696E446174618C         imul    ebp, [esi+$44], $8C617461
00654284   40                     inc     eax
00654285   65005002               add     gs:[eax+$02], dl
00654289   00FF                   add     bh, bh
0065428B   7C51                   jl      006542DE
0065428D   650001                 add     gs:[ecx], al
00654290   0000                   add     [eax], al

00654292   0000                   add     [eax], al

00654294   0000                   add     [eax], al

00654296   800000                 add     byte ptr [eax], $00
00654299   0000                   add     [eax], al

0065429B   2D00055374             sub     eax, $74530500
006542A0   796C                   jns     0065430E
006542A2   6554                   push    esp
006542A4   104000                 adc     [eax+$00], al
006542A7   4C                     dec     esp
006542A8   0200                   add     al, byte ptr [eax]
006542AA   FFFC                   DB  $FF, $FC  //      
006542AC   50                     push    eax
006542AD   650001                 add     gs:[ecx], al
006542B0   0000                   add     [eax], al

006542B2   0000                   add     [eax], al

006542B4   0000                   add     [eax], al

006542B6   800A00                 or      byte ptr [edx], $00
006542B9   0000                   add     [eax], al

006542BB   2E000F                 add     cs:[edi], cl
006542BE   4D                     dec     ebp
006542BF   61                     popa
006542C0   7271                   jb      00654333
006542C2   7565                   jnz     00654329
006542C4   6549                   dec     ecx
006542C6   6E                     outsb
006542C7   7465                   jz      0065432E
006542C9   7276                   jb      00654341
006542CB   61                     popa
006542CC   6C                     insb
006542CD   8D4000                 lea     eax, [eax+$00]
006542D0   53                     push    ebx
006542D1   8BD8                   mov     ebx, eax
006542D3   8BC3                   mov     eax, ebx

|
006542D5   E84AFCDAFF             call    00403F24
006542DA   B201                   mov     dl, $01
006542DC   8B8340020000           mov     eax, [ebx+$0240]

|
006542E2   E861E9F1FF             call    00572C48
006542E7   5B                     pop     ebx
006542E8   C3                     ret

006542E9   8D4000                 lea     eax, [eax+$00]
006542EC   53                     push    ebx
006542ED   56                     push    esi
006542EE   8BF2                   mov     esi, edx
006542F0   8BD8                   mov     ebx, eax
006542F2   8BD6                   mov     edx, esi
006542F4   8BC3                   mov     eax, ebx

* Reference to : TsOpenPictureDialog._PROC_0055F9C4()
|
006542F6   E8C9B6F0FF             call    0055F9C4
006542FB   6AFF                   push    $FF
006542FD   6AFF                   push    $FF
006542FF   56                     push    esi

* Reference to: user32.InflateRect()
|
00654300   E88B39DBFF             call    00407C90
00654305   5E                     pop     esi
00654306   5B                     pop     ebx
00654307   C3                     ret

00654308   55                     push    ebp
00654309   8BEC                   mov     ebp, esp
0065430B   51                     push    ecx
0065430C   53                     push    ebx
0065430D   56                     push    esi
0065430E   57                     push    edi
0065430F   84D2                   test    dl, dl
00654311   7408                   jz      0065431B
00654313   83C4F0                 add     esp, -$10

|
00654316   E819FDDAFF             call    00404034
0065431B   8BF9                   mov     edi, ecx
0065431D   8855FF                 mov     [ebp-$01], dl
00654320   8BD8                   mov     ebx, eax
00654322   6A00                   push    $00
00654324   8BCB                   mov     ecx, ebx
00654326   B201                   mov     dl, $01

* Reference to class TsCommonData
|
00654328   A188005700             mov     eax, dword ptr [$00570088]

|
0065432D   E812E4F1FF             call    00572744
00654332   8BF0                   mov     esi, eax
00654334   89B340020000           mov     [ebx+$0240], esi

* Reference to field TsCommonData.OFFS_002C
|
0065433A   C7462CA1000000         mov     dword ptr [esi+$2C], $000000A1
00654341   8BCF                   mov     ecx, edi
00654343   33D2                   xor     edx, edx
00654345   8BC3                   mov     eax, ebx

* Reference to: Comctrls.TProgressBar.Create(Classes.TComponent)
|
00654347   E84C71DFFF             call    0044B498
0065434C   C7832402000028000000   mov     dword ptr [ebx+$0224], $00000028
00654356   C7832802000008000000   mov     dword ptr [ebx+$0228], $00000008
00654360   C7832C020000FFFFFFFF   mov     dword ptr [ebx+$022C], $FFFFFFFF
0065436A   C7834C0200000A000000   mov     dword ptr [ebx+$024C], $0000000A
00654374   C6835002000000         mov     byte ptr [ebx+$0250], $00
0065437B   8B4350                 mov     eax, [ebx+$50]
0065437E   0B05F0436500           or      eax, [$006543F0]
00654384   894350                 mov     [ebx+$50], eax
00654387   8BCB                   mov     ecx, ebx
00654389   B201                   mov     dl, $01

* Reference to class TTimer
|
0065438B   A180A74300             mov     eax, dword ptr [$0043A780]

* Reference to: Extctrls.TTimer.Create(Classes.TComponent)
|
00654390   E8E77ADEFF             call    0043BE7C
00654395   8BF0                   mov     esi, eax
00654397   89B330020000           mov     [ebx+$0230], esi
0065439D   8BC6                   mov     eax, esi
0065439F   33D2                   xor     edx, edx

* Reference to: Extctrls.TTimer.SetEnabled()
|
006543A1   E85E7CDEFF             call    0043C004
006543A6   8B8330020000           mov     eax, [ebx+$0230]
006543AC   BA1E000000             mov     edx, $0000001E

* Reference to: Extctrls.TTimer.SetInterval(Cardinal)
|
006543B1   E85E7CDEFF             call    0043C014
006543B6   53                     push    ebx
006543B7   6830566500             push    $00655630
006543BC   8B8330020000           mov     eax, [ebx+$0230]

* Reference to: Extctrls.TTimer.SetOnTimer(Pointer; System.TObject)
|
006543C2   E85D7CDEFF             call    0043C024
006543C7   C7832002000001000000   mov     dword ptr [ebx+$0220], $00000001
006543D1   8BC3                   mov     eax, ebx
006543D3   807DFF00               cmp     byte ptr [ebp-$01], $00
006543D7   740F                   jz      006543E8

|
006543D9   E8AEFCDAFF             call    0040408C
006543DE   648F0500000000         pop     dword ptr fs:[$00000000]
006543E5   83C40C                 add     esp, +$0C
006543E8   8BC3                   mov     eax, ebx
006543EA   5F                     pop     edi
006543EB   5E                     pop     esi
006543EC   5B                     pop     ebx
006543ED   59                     pop     ecx
006543EE   5D                     pop     ebp
006543EF   C3                     ret

*)
end;

end.