unit Unit7;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, sComboBox, Buttons, sBitBtn, acPNG,
  ExtCtrls, acImage, sLabel, sPanel;
type
  TForm7=class(TForm)
    sPanel1: TsPanel;
    sLabelFX1: TsLabelFX;
    sLabelFX2: TsLabelFX;
    sPanel2: TsPanel;
    sBitBtn5: TsBitBtn;
    sBitBtn6: TsBitBtn;
    sComboBox1: TsComboBox;
    sComboBox2: TsComboBox;
    sImage1: TsImage;
    procedure sBitBtn5Click(Sender : TObject);
    procedure sBitBtn6Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_0062D59D(Sender : TObject);
    procedure _PROC_0062D5D8(Sender : TObject);
    procedure _PROC_0062D5E0(Sender : TObject);
    procedure _PROC_0062D951(Sender : TObject);
    procedure _PROC_0062D980(Sender : TObject);
    procedure _PROC_0062D988(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form7: TForm7;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation
       uses Unit2, DB;
{$R *.DFM}

procedure TForm7.sBitBtn5Click(Sender : TObject);
begin
  //00628088
  ModalResult := mrCancel;
  Close;
end;

procedure TForm7.sBitBtn6Click(Sender : TObject);
var
  i:integer;
begin
  //006280E8
   ModalResult := MrOk;
end;

procedure TForm7.FormShow(Sender : TObject);
begin
(*
0062D574   53                     push    ebx
0062D575   8BD8                   mov     ebx, eax
0062D577   6A13                   push    $13

* Reference to field TForm7.OFFS_004C
|
0062D579   8B434C                 mov     eax, [ebx+$4C]
0062D57C   50                     push    eax

* Reference to field TForm7.OFFS_0048
|
0062D57D   8B4348                 mov     eax, [ebx+$48]
0062D580   50                     push    eax

* Reference to field TForm7.OFFS_0044
|
0062D581   8B4344                 mov     eax, [ebx+$44]
0062D584   50                     push    eax

* Reference to field TForm7.OFFS_0040
|
0062D585   8B4340                 mov     eax, [ebx+$40]
0062D588   50                     push    eax
0062D589   6AFF                   push    $FF
0062D58B   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
0062D58D   E8FED5E3FF             call    0046AB90
0062D592   50                     push    eax

* Reference to: user32.SetWindowPos()
|
0062D593   E828A9DDFF             call    00407EC0
0062D598   5B                     pop     ebx
0062D599   C3                     ret

*)
end;

procedure TForm7._PROC_0062D59D(Sender : TObject);
begin
(*
0062D59D   8BEC                   mov     ebp, esp
0062D59F   33C0                   xor     eax, eax
0062D5A1   55                     push    ebp
0062D5A2   68CDD56200             push    $0062D5CD
0062D5A7   64FF30                 push    dword ptr fs:[eax]
0062D5AA   648920                 mov     fs:[eax], esp
0062D5AD   FF0518346B00           inc     dword ptr [$006B3418]
0062D5B3   750A                   jnz     0062D5BF
0062D5B5   B814346B00             mov     eax, $006B3414

|
0062D5BA   E8C174DDFF             call    00404A80
0062D5BF   33C0                   xor     eax, eax
0062D5C1   5A                     pop     edx
0062D5C2   59                     pop     ecx
0062D5C3   59                     pop     ecx
0062D5C4   648910                 mov     fs:[eax], edx

****** FINALLY
|
0062D5C7   68D4D56200             push    $0062D5D4
0062D5CC   C3                     ret

0062D5CD   E9926EDDFF             jmp     00404464
0062D5D2   EBF8                   jmp     0062D5CC

****** END
|
0062D5D4   5D                     pop     ebp
0062D5D5   C3                     ret

*)
end;

procedure TForm7._PROC_0062D5D8(Sender : TObject);
begin
(*
0062D5D8   832D18346B0001         sub     dword ptr [$006B3418], +$01
0062D5DF   C3                     ret

*)
end;

procedure TForm7._PROC_0062D5E0(Sender : TObject);
begin
(*
0062D5E0   68066B0013             push    $13006B06
0062D5E5   FE00                   inc     byte ptr [eax]
0062D5E7   006806                 add     [eax+$06], ch
0062D5EA   6B0014                 imul    eax, [eax], $14
0062D5ED   FE00                   inc     byte ptr [eax]
0062D5EF   006806                 add     [eax+$06], ch
0062D5F2   6B0015                 imul    eax, [eax], $15
0062D5F5   FE00                   inc     byte ptr [eax]
0062D5F7   006806                 add     [eax+$06], ch
0062D5FA   6B0016                 imul    eax, [eax], $16
0062D5FD   FE00                   inc     byte ptr [eax]
0062D5FF   006806                 add     [eax+$06], ch
0062D602   6B0017                 imul    eax, [eax], $17
0062D605   FE00                   inc     byte ptr [eax]
0062D607   006806                 add     [eax+$06], ch
0062D60A   6B0018                 imul    eax, [eax], $18
0062D60D   FE00                   inc     byte ptr [eax]
0062D60F   006806                 add     [eax+$06], ch
0062D612   6B0019                 imul    eax, [eax], $19
0062D615   FE00                   inc     byte ptr [eax]
0062D617   006806                 add     [eax+$06], ch
0062D61A   6B001A                 imul    eax, [eax], $1A
0062D61D   FE00                   inc     byte ptr [eax]
0062D61F   006806                 add     [eax+$06], ch
0062D622   6B001B                 imul    eax, [eax], $1B
0062D625   FE00                   inc     byte ptr [eax]
0062D627   006806                 add     [eax+$06], ch
0062D62A   6B001C                 imul    eax, [eax], $1C
0062D62D   FE00                   inc     byte ptr [eax]
0062D62F   006806                 add     [eax+$06], ch
0062D632   6B001D                 imul    eax, [eax], $1D
0062D635   FE00                   inc     byte ptr [eax]
0062D637   006806                 add     [eax+$06], ch
0062D63A   6B001E                 imul    eax, [eax], $1E
0062D63D   FE00                   inc     byte ptr [eax]
0062D63F   006806                 add     [eax+$06], ch
0062D642   6B001F                 imul    eax, [eax], $1F
0062D645   FE00                   inc     byte ptr [eax]
0062D647   006806                 add     [eax+$06], ch
0062D64A   6B0000                 imul    eax, [eax], $00
0062D64D   FE00                   inc     byte ptr [eax]
0062D64F   006806                 add     [eax+$06], ch
0062D652   6B0001                 imul    eax, [eax], $01
0062D655   FE00                   inc     byte ptr [eax]
0062D657   006806                 add     [eax+$06], ch
0062D65A   6B0002                 imul    eax, [eax], $02
0062D65D   FE00                   inc     byte ptr [eax]
0062D65F   006806                 add     [eax+$06], ch
0062D662   6B0003                 imul    eax, [eax], $03
0062D665   FE00                   inc     byte ptr [eax]
0062D667   006806                 add     [eax+$06], ch
0062D66A   6B0004                 imul    eax, [eax], $04
0062D66D   FE00                   inc     byte ptr [eax]
0062D66F   006806                 add     [eax+$06], ch
0062D672   6B0005                 imul    eax, [eax], $05
0062D675   FE00                   inc     byte ptr [eax]
0062D677   006806                 add     [eax+$06], ch
0062D67A   6B0006                 imul    eax, [eax], $06
0062D67D   FE00                   inc     byte ptr [eax]
0062D67F   006806                 add     [eax+$06], ch
0062D682   6B0007                 imul    eax, [eax], $07
0062D685   FE00                   inc     byte ptr [eax]
0062D687   006806                 add     [eax+$06], ch
0062D68A   6B0008                 imul    eax, [eax], $08
0062D68D   FE00                   inc     byte ptr [eax]
0062D68F   006806                 add     [eax+$06], ch
0062D692   6B0009                 imul    eax, [eax], $09
0062D695   FE00                   inc     byte ptr [eax]
0062D697   006806                 add     [eax+$06], ch
0062D69A   6B000A                 imul    eax, [eax], $0A
0062D69D   FE00                   inc     byte ptr [eax]
0062D69F   006806                 add     [eax+$06], ch
0062D6A2   6B000B                 imul    eax, [eax], $0B
0062D6A5   FE00                   inc     byte ptr [eax]
0062D6A7   006806                 add     [eax+$06], ch
0062D6AA   6B000C                 imul    eax, [eax], $0C
0062D6AD   FE00                   inc     byte ptr [eax]
0062D6AF   006806                 add     [eax+$06], ch
0062D6B2   6B000D                 imul    eax, [eax], $0D
0062D6B5   FE00                   inc     byte ptr [eax]
0062D6B7   006806                 add     [eax+$06], ch
0062D6BA   6B000E                 imul    eax, [eax], $0E
0062D6BD   FE00                   inc     byte ptr [eax]
0062D6BF   006806                 add     [eax+$06], ch
0062D6C2   6B000F                 imul    eax, [eax], $0F
0062D6C5   FE00                   inc     byte ptr [eax]
0062D6C7   006806                 add     [eax+$06], ch
0062D6CA   6B00F0                 imul    eax, [eax], $F0
0062D6CD   FD                     std
0062D6CE   0000                   add     [eax], al

*)
end;

procedure TForm7._PROC_0062D951(Sender : TObject);
begin
(*
0062D951   8BEC                   mov     ebp, esp
0062D953   33C0                   xor     eax, eax
0062D955   55                     push    ebp
0062D956   6875D96200             push    $0062D975
0062D95B   64FF30                 push    dword ptr fs:[eax]
0062D95E   648920                 mov     fs:[eax], esp
0062D961   FF051C346B00           inc     dword ptr [$006B341C]
0062D967   33C0                   xor     eax, eax
0062D969   5A                     pop     edx
0062D96A   59                     pop     ecx
0062D96B   59                     pop     ecx
0062D96C   648910                 mov     fs:[eax], edx

****** FINALLY
|
0062D96F   687CD96200             push    $0062D97C
0062D974   C3                     ret

0062D975   E9EA6ADDFF             jmp     00404464
0062D97A   EBF8                   jmp     0062D974

****** END
|
0062D97C   5D                     pop     ebp
0062D97D   C3                     ret

*)
end;

procedure TForm7._PROC_0062D980(Sender : TObject);
begin
(*
0062D980   832D1C346B0001         sub     dword ptr [$006B341C], +$01
0062D987   C3                     ret

*)
end;

procedure TForm7._PROC_0062D988(Sender : TObject);
begin
(*
0062D988   D4                     aam
0062D989   D96200                 fldenv  ???? ptr [edx+$00]
0062D98C   0000                   add     [eax], al

*)
end;

end.