unit Unit38;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, sComboBox, Buttons, sBitBtn, acPNG,
  ExtCtrls, acImage, sLabel, sPanel;
type
  TForm38=class(TForm)
    sPanel1: TsPanel;
    sLabelFX1: TsLabelFX;
    sImage1: TsImage;
    sPanel2: TsPanel;
    sBitBtn5: TsBitBtn;
    sBitBtn6: TsBitBtn;
    sComboBox1: TsComboBox;
    procedure sBitBtn5Click(Sender : TObject);
    procedure sBitBtn6Click(Sender : TObject);
    procedure _PROC_00670C01(Sender : TObject);
    procedure _PROC_00670C30(Sender : TObject);
    procedure _PROC_00670C38(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form38: TForm38;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm38.sBitBtn5Click(Sender : TObject);
begin
(*

* Reference to Form38
|
006706B8   A10C366B00             mov     eax, dword ptr [$006B360C]

* Reference to: Forms.TCustomForm.Close()
|
006706BD   E8361EE1FF             call    004824F8
006706C2   C3                     ret

*)
end;

procedure TForm38.sBitBtn6Click(Sender : TObject);
begin
(*
006706C4   55                     push    ebp
006706C5   8BEC                   mov     ebp, esp
006706C7   B90A000000             mov     ecx, $0000000A
006706CC   6A00                   push    $00
006706CE   6A00                   push    $00
006706D0   49                     dec     ecx
006706D1   75F9                   jnz     006706CC
006706D3   53                     push    ebx
006706D4   56                     push    esi
006706D5   57                     push    edi

* Reference to TData instance
|
006706D6   8B35D8F06A00           mov     esi, [$006AF0D8]
006706DC   33C0                   xor     eax, eax
006706DE   55                     push    ebp
006706DF   68A60B6700             push    $00670BA6
006706E4   64FF30                 push    dword ptr fs:[eax]
006706E7   648920                 mov     fs:[eax], esp
006706EA   8D55FC                 lea     edx, [ebp-$04]
006706ED   8B06                   mov     eax, [esi]
006706EF   8B80E0020000           mov     eax, [eax+$02E0]
006706F5   8B08                   mov     ecx, [eax]
006706F7   FF5160                 call    dword ptr [ecx+$60]
006706FA   837DFC00               cmp     dword ptr [ebp-$04], +$00
006706FE   0F8451040000           jz      00670B55
00670704   8B06                   mov     eax, [esi]
00670706   8B80D8020000           mov     eax, [eax+$02D8]

|
0067070C   E8CBD8F2FF             call    0059DFDC
00670711   E92A040000             jmp     00670B40

* Possible String Reference to: 'Wakala_cb=''
|
00670716   68BC0B6700             push    $00670BBC
0067071B   8D55F4                 lea     edx, [ebp-$0C]
0067071E   8B06                   mov     eax, [esi]
00670720   8B80E0020000           mov     eax, [eax+$02E0]
00670726   8B08                   mov     ecx, [eax]
00670728   FF5160                 call    dword ptr [ecx+$60]
0067072B   FF75F4                 push    dword ptr [ebp-$0C]

* Possible String Reference to: '*''
|
0067072E   68D00B6700             push    $00670BD0
00670733   8D45F8                 lea     eax, [ebp-$08]
00670736   BA03000000             mov     edx, $00000003

|
0067073B   E8C046D9FF             call    00404E00
00670740   8B55F8                 mov     edx, [ebp-$08]
00670743   8B06                   mov     eax, [esi]
00670745   8B808C060000           mov     eax, [eax+$068C]
0067074B   8B08                   mov     ecx, [eax]
0067074D   FF9198010000           call    dword ptr [ecx+$0198]
00670753   8B06                   mov     eax, [esi]
00670755   8B808C060000           mov     eax, [eax+$068C]
0067075B   B201                   mov     dl, $01
0067075D   8B08                   mov     ecx, [eax]
0067075F   FF9190010000           call    dword ptr [ecx+$0190]
00670765   8B06                   mov     eax, [esi]
00670767   8B808C060000           mov     eax, [eax+$068C]

|
0067076D   E8FAD6F2FF             call    0059DE6C
00670772   84C0                   test    al, al
00670774   0F85B9030000           jnz     00670B33
0067077A   8B06                   mov     eax, [esi]
0067077C   8B80A8060000           mov     eax, [eax+$06A8]

|
00670782   E8A5DDF2FF             call    0059E52C
00670787   33FF                   xor     edi, edi
00670789   8D55EC                 lea     edx, [ebp-$14]
0067078C   8B06                   mov     eax, [esi]
0067078E   8B80E0020000           mov     eax, [eax+$02E0]
00670794   8B08                   mov     ecx, [eax]
00670796   FF5160                 call    dword ptr [ecx+$60]
00670799   FF75EC                 push    dword ptr [ebp-$14]
0067079C   68DC0B6700             push    $00670BDC
006707A1   8D55E8                 lea     edx, [ebp-$18]

* Reference to Form38
|
006707A4   A10C366B00             mov     eax, dword ptr [$006B360C]

* Reference to field Form38.OFFS_0310
|
006707A9   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.TControl.GetText()
|
006707AF   E87439DFFF             call    00464128
006707B4   FF75E8                 push    dword ptr [ebp-$18]
006707B7   8D45F0                 lea     eax, [ebp-$10]
006707BA   BA03000000             mov     edx, $00000003

|
006707BF   E83C46D9FF             call    00404E00
006707C4   8B55F0                 mov     edx, [ebp-$10]
006707C7   8B06                   mov     eax, [esi]
006707C9   8B80BC060000           mov     eax, [eax+$06BC]
006707CF   8B08                   mov     ecx, [eax]
006707D1   FF91B0000000           call    dword ptr [ecx+$00B0]
006707D7   8D55E4                 lea     edx, [ebp-$1C]

* Reference to Form38
|
006707DA   A10C366B00             mov     eax, dword ptr [$006B360C]

* Reference to field Form38.OFFS_0310
|
006707DF   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.TControl.GetText()
|
006707E5   E83E39DFFF             call    00464128
006707EA   8B55E4                 mov     edx, [ebp-$1C]
006707ED   8B06                   mov     eax, [esi]
006707EF   8B80C0060000           mov     eax, [eax+$06C0]
006707F5   8B08                   mov     ecx, [eax]
006707F7   FF91B0000000           call    dword ptr [ecx+$00B0]
006707FD   8B06                   mov     eax, [esi]
006707FF   8B80C4060000           mov     eax, [eax+$06C4]
00670805   33D2                   xor     edx, edx
00670807   8B08                   mov     ecx, [eax]
00670809   FF91A8000000           call    dword ptr [ecx+$00A8]
0067080F   6A00                   push    $00
00670811   6A00                   push    $00
00670813   8B06                   mov     eax, [esi]
00670815   8B80C8060000           mov     eax, [eax+$06C8]
0067081B   8B10                   mov     edx, [eax]
0067081D   FF929C000000           call    dword ptr [edx+$009C]
00670823   6A00                   push    $00
00670825   6A00                   push    $00
00670827   8B06                   mov     eax, [esi]
00670829   8B80CC060000           mov     eax, [eax+$06CC]
0067082F   8B10                   mov     edx, [eax]
00670831   FF929C000000           call    dword ptr [edx+$009C]
00670837   8B06                   mov     eax, [esi]
00670839   8B80A8060000           mov     eax, [eax+$06A8]
0067083F   8B10                   mov     edx, [eax]
00670841   FF924C020000           call    dword ptr [edx+$024C]
00670847   8B06                   mov     eax, [esi]
00670849   8B808C060000           mov     eax, [eax+$068C]

|
0067084F   E888D7F2FF             call    0059DFDC
00670854   E9A7020000             jmp     00670B00
00670859   8B06                   mov     eax, [esi]
0067085B   8B80FC090000           mov     eax, [eax+$09FC]
00670861   8B10                   mov     edx, [eax]
00670863   FF5258                 call    dword ptr [edx+$58]
00670866   85C0                   test    eax, eax
00670868   0F8485020000           jz      00670AF3
0067086E   8B06                   mov     eax, [esi]
00670870   8B80AC060000           mov     eax, [eax+$06AC]

|
00670876   E8B1DCF2FF             call    0059E52C
0067087B   47                     inc     edi
0067087C   8D55E0                 lea     edx, [ebp-$20]
0067087F   8B06                   mov     eax, [esi]
00670881   8B8064090000           mov     eax, [eax+$0964]
00670887   8B08                   mov     ecx, [eax]
00670889   FF5160                 call    dword ptr [ecx+$60]
0067088C   8B55E0                 mov     edx, [ebp-$20]
0067088F   8B06                   mov     eax, [esi]
00670891   8B80D4060000           mov     eax, [eax+$06D4]
00670897   8B08                   mov     ecx, [eax]
00670899   FF91B0000000           call    dword ptr [ecx+$00B0]
0067089F   8B06                   mov     eax, [esi]
006708A1   8B80DC060000           mov     eax, [eax+$06DC]
006708A7   8BD7                   mov     edx, edi
006708A9   8B08                   mov     ecx, [eax]
006708AB   FF91A8000000           call    dword ptr [ecx+$00A8]
006708B1   8D55DC                 lea     edx, [ebp-$24]
006708B4   8B06                   mov     eax, [esi]
006708B6   8B80C8090000           mov     eax, [eax+$09C8]
006708BC   8B08                   mov     ecx, [eax]
006708BE   FF5160                 call    dword ptr [ecx+$60]
006708C1   8B55DC                 mov     edx, [ebp-$24]
006708C4   8B06                   mov     eax, [esi]
006708C6   8B80D8060000           mov     eax, [eax+$06D8]
006708CC   8B08                   mov     ecx, [eax]
006708CE   FF91B0000000           call    dword ptr [ecx+$00B0]
006708D4   8B06                   mov     eax, [esi]
006708D6   8B80FC090000           mov     eax, [eax+$09FC]
006708DC   8B10                   mov     edx, [eax]
006708DE   FF5258                 call    dword ptr [edx+$58]
006708E1   8BD0                   mov     edx, eax
006708E3   8B06                   mov     eax, [esi]
006708E5   8B80E0060000           mov     eax, [eax+$06E0]
006708EB   8B08                   mov     ecx, [eax]
006708ED   FF91A8000000           call    dword ptr [ecx+$00A8]
006708F3   8D55D8                 lea     edx, [ebp-$28]
006708F6   8B06                   mov     eax, [esi]
006708F8   8B80040A0000           mov     eax, [eax+$0A04]
006708FE   8B08                   mov     ecx, [eax]
00670900   FF5160                 call    dword ptr [ecx+$60]
00670903   8B45D8                 mov     eax, [ebp-$28]
00670906   BAE80B6700             mov     edx, $00670BE8

|
0067090B   E87C45D9FF             call    00404E8C
00670910   7517                   jnz     00670929
00670912   6A00                   push    $00
00670914   6800093D00             push    $003D0900
00670919   8B06                   mov     eax, [esi]
0067091B   8B80E4060000           mov     eax, [eax+$06E4]
00670921   8B10                   mov     edx, [eax]
00670923   FF929C000000           call    dword ptr [edx+$009C]
00670929   8D55D4                 lea     edx, [ebp-$2C]
0067092C   8B06                   mov     eax, [esi]
0067092E   8B80040A0000           mov     eax, [eax+$0A04]
00670934   8B08                   mov     ecx, [eax]
00670936   FF5160                 call    dword ptr [ecx+$60]
00670939   8B45D4                 mov     eax, [ebp-$2C]
0067093C   BAF40B6700             mov     edx, $00670BF4

|
00670941   E84645D9FF             call    00404E8C
00670946   7517                   jnz     0067095F
00670948   6A00                   push    $00
0067094A   6800127A00             push    $007A1200
0067094F   8B06                   mov     eax, [esi]
00670951   8B80E4060000           mov     eax, [eax+$06E4]
00670957   8B10                   mov     edx, [eax]
00670959   FF929C000000           call    dword ptr [edx+$009C]
0067095F   8B06                   mov     eax, [esi]
00670961   8B80FC090000           mov     eax, [eax+$09FC]
00670967   8B10                   mov     edx, [eax]
00670969   FF5258                 call    dword ptr [edx+$58]
0067096C   83F805                 cmp     eax, +$05
0067096F   7F40                   jnle    006709B1
00670971   8B06                   mov     eax, [esi]
00670973   8B80E0060000           mov     eax, [eax+$06E0]
00670979   8B10                   mov     edx, [eax]
0067097B   FF5258                 call    dword ptr [edx+$58]
0067097E   8945D0                 mov     [ebp-$30], eax
00670981   DB45D0                 fild    dword ptr [ebp-$30]
00670984   DB7DC4                 fstp    tbyte ptr [ebp-$3C]
00670987   9B                     wait
00670988   8B06                   mov     eax, [esi]
0067098A   8B80E4060000           mov     eax, [eax+$06E4]
00670990   8B10                   mov     edx, [eax]
00670992   FF524C                 call    dword ptr [edx+$4C]
00670995   DB6DC4                 fld     tbyte ptr [ebp-$3C]
00670998   DEC9                   fmulp   st(1), st(0)
0067099A   83C4F8                 add     esp, -$08
0067099D   DF3C24                 fistp   qword ptr [esp]
006709A0   9B                     wait
006709A1   8B06                   mov     eax, [esi]
006709A3   8B80E8060000           mov     eax, [eax+$06E8]
006709A9   8B10                   mov     edx, [eax]
006709AB   FF929C000000           call    dword ptr [edx+$009C]
006709B1   8B06                   mov     eax, [esi]
006709B3   8B80FC090000           mov     eax, [eax+$09FC]
006709B9   8B10                   mov     edx, [eax]
006709BB   FF5258                 call    dword ptr [edx+$58]
006709BE   83F805                 cmp     eax, +$05
006709C1   7E65                   jle     00670A28
006709C3   8B06                   mov     eax, [esi]
006709C5   8B80E4060000           mov     eax, [eax+$06E4]
006709CB   8B10                   mov     edx, [eax]
006709CD   FF524C                 call    dword ptr [edx+$4C]
006709D0   D80DF80B6700           fmul    dword ptr [$00670BF8]
006709D6   DB7DC4                 fstp    tbyte ptr [ebp-$3C]
006709D9   9B                     wait
006709DA   8B06                   mov     eax, [esi]
006709DC   8B80E4060000           mov     eax, [eax+$06E4]
006709E2   8B10                   mov     edx, [eax]
006709E4   FF524C                 call    dword ptr [edx+$4C]
006709E7   D835FC0B6700           fdiv    dword ptr [$00670BFC]
006709ED   DB7DB8                 fstp    tbyte ptr [ebp-$48]
006709F0   9B                     wait
006709F1   8B06                   mov     eax, [esi]
006709F3   8B80E0060000           mov     eax, [eax+$06E0]
006709F9   8B10                   mov     edx, [eax]
006709FB   FF5258                 call    dword ptr [edx+$58]
006709FE   83E805                 sub     eax, +$05
00670A01   8945D0                 mov     [ebp-$30], eax
00670A04   DB45D0                 fild    dword ptr [ebp-$30]
00670A07   DB6DB8                 fld     tbyte ptr [ebp-$48]
00670A0A   DEC9                   fmulp   st(1), st(0)
00670A0C   DB6DC4                 fld     tbyte ptr [ebp-$3C]
00670A0F   DEC1                   faddp   st(1), st(0)
00670A11   83C4F8                 add     esp, -$08
00670A14   DF3C24                 fistp   qword ptr [esp]
00670A17   9B                     wait
00670A18   8B06                   mov     eax, [esi]
00670A1A   8B80E8060000           mov     eax, [eax+$06E8]
00670A20   8B10                   mov     edx, [eax]
00670A22   FF929C000000           call    dword ptr [edx+$009C]
00670A28   8B06                   mov     eax, [esi]
00670A2A   8B80AC060000           mov     eax, [eax+$06AC]
00670A30   8B10                   mov     edx, [eax]
00670A32   FF924C020000           call    dword ptr [edx+$024C]
00670A38   8B06                   mov     eax, [esi]
00670A3A   8B80A8060000           mov     eax, [eax+$06A8]

|
00670A40   E8A3D9F2FF             call    0059E3E8
00670A45   8B06                   mov     eax, [esi]
00670A47   8B98C4060000           mov     ebx, [eax+$06C4]
00670A4D   8BC3                   mov     eax, ebx
00670A4F   8B10                   mov     edx, [eax]
00670A51   FF5258                 call    dword ptr [edx+$58]
00670A54   50                     push    eax
00670A55   8B06                   mov     eax, [esi]
00670A57   8B80E0060000           mov     eax, [eax+$06E0]
00670A5D   8B10                   mov     edx, [eax]
00670A5F   FF5258                 call    dword ptr [edx+$58]
00670A62   5A                     pop     edx
00670A63   03D0                   add     edx, eax
00670A65   8BC3                   mov     eax, ebx
00670A67   8B08                   mov     ecx, [eax]
00670A69   FF91A8000000           call    dword ptr [ecx+$00A8]
00670A6F   8B06                   mov     eax, [esi]
00670A71   8B80C8060000           mov     eax, [eax+$06C8]
00670A77   8B10                   mov     edx, [eax]
00670A79   FF524C                 call    dword ptr [edx+$4C]
00670A7C   DF7DB0                 fistp   qword ptr [ebp-$50]
00670A7F   9B                     wait
00670A80   8B06                   mov     eax, [esi]
00670A82   8B80E4060000           mov     eax, [eax+$06E4]
00670A88   8B10                   mov     edx, [eax]
00670A8A   FF524C                 call    dword ptr [edx+$4C]
00670A8D   DF6DB0                 fild    qword ptr [ebp-$50]
00670A90   DEC1                   faddp   st(1), st(0)
00670A92   83C4F8                 add     esp, -$08
00670A95   DF3C24                 fistp   qword ptr [esp]
00670A98   9B                     wait
00670A99   8B06                   mov     eax, [esi]
00670A9B   8B80C8060000           mov     eax, [eax+$06C8]
00670AA1   8B10                   mov     edx, [eax]
00670AA3   FF929C000000           call    dword ptr [edx+$009C]
00670AA9   8B06                   mov     eax, [esi]
00670AAB   8B80CC060000           mov     eax, [eax+$06CC]
00670AB1   8B10                   mov     edx, [eax]
00670AB3   FF524C                 call    dword ptr [edx+$4C]
00670AB6   DF7DB0                 fistp   qword ptr [ebp-$50]
00670AB9   9B                     wait
00670ABA   8B06                   mov     eax, [esi]
00670ABC   8B80E8060000           mov     eax, [eax+$06E8]
00670AC2   8B10                   mov     edx, [eax]
00670AC4   FF524C                 call    dword ptr [edx+$4C]
00670AC7   DF6DB0                 fild    qword ptr [ebp-$50]
00670ACA   DEC1                   faddp   st(1), st(0)
00670ACC   83C4F8                 add     esp, -$08
00670ACF   DF3C24                 fistp   qword ptr [esp]
00670AD2   9B                     wait
00670AD3   8B06                   mov     eax, [esi]
00670AD5   8B80CC060000           mov     eax, [eax+$06CC]
00670ADB   8B10                   mov     edx, [eax]
00670ADD   FF929C000000           call    dword ptr [edx+$009C]
00670AE3   8B06                   mov     eax, [esi]
00670AE5   8B80A8060000           mov     eax, [eax+$06A8]
00670AEB   8B10                   mov     edx, [eax]
00670AED   FF924C020000           call    dword ptr [edx+$024C]
00670AF3   8B06                   mov     eax, [esi]
00670AF5   8B808C060000           mov     eax, [eax+$068C]

|
00670AFB   E8F4D7F2FF             call    0059E2F4
00670B00   8B06                   mov     eax, [esi]
00670B02   8B808C060000           mov     eax, [eax+$068C]
00670B08   80B8A100000000         cmp     byte ptr [eax+$00A1], $00
00670B0F   0F8444FDFFFF           jz      00670859
00670B15   8B06                   mov     eax, [esi]
00670B17   8B80C4060000           mov     eax, [eax+$06C4]
00670B1D   8B10                   mov     edx, [eax]
00670B1F   FF5258                 call    dword ptr [edx+$58]
00670B22   85C0                   test    eax, eax
00670B24   750D                   jnz     00670B33
00670B26   8B06                   mov     eax, [esi]
00670B28   8B80A8060000           mov     eax, [eax+$06A8]

|
00670B2E   E8EDDBF2FF             call    0059E720
00670B33   8B06                   mov     eax, [esi]
00670B35   8B80D8020000           mov     eax, [eax+$02D8]

|
00670B3B   E8B4D7F2FF             call    0059E2F4
00670B40   8B06                   mov     eax, [esi]
00670B42   8B80D8020000           mov     eax, [eax+$02D8]
00670B48   80B8A100000000         cmp     byte ptr [eax+$00A1], $00
00670B4F   0F84C1FBFFFF           jz      00670716
00670B55   8B06                   mov     eax, [esi]
00670B57   8B808C060000           mov     eax, [eax+$068C]
00670B5D   33D2                   xor     edx, edx
00670B5F   8B08                   mov     ecx, [eax]
00670B61   FF9190010000           call    dword ptr [ecx+$0190]

* Reference to Form38
|
00670B67   A10C366B00             mov     eax, dword ptr [$006B360C]

* Reference to: Forms.TCustomForm.Close()
|
00670B6C   E88719E1FF             call    004824F8
00670B71   33C0                   xor     eax, eax
00670B73   5A                     pop     edx
00670B74   59                     pop     ecx
00670B75   59                     pop     ecx
00670B76   648910                 mov     fs:[eax], edx

****** FINALLY
|
00670B79   68AD0B6700             push    $00670BAD
00670B7E   8D45D4                 lea     eax, [ebp-$2C]
00670B81   BA04000000             mov     edx, $00000004

|
00670B86   E8193FD9FF             call    00404AA4
00670B8B   8D45E4                 lea     eax, [ebp-$1C]
00670B8E   BA02000000             mov     edx, $00000002

|
00670B93   E80C3FD9FF             call    00404AA4
00670B98   8D45EC                 lea     eax, [ebp-$14]
00670B9B   BA05000000             mov     edx, $00000005

|
00670BA0   E8FF3ED9FF             call    00404AA4
00670BA5   C3                     ret

00670BA6   E9B938D9FF             jmp     00404464
00670BAB   EBD1                   jmp     00670B7E

****** END
|
00670BAD   5F                     pop     edi
00670BAE   5E                     pop     esi
00670BAF   5B                     pop     ebx
00670BB0   8BE5                   mov     esp, ebp
00670BB2   5D                     pop     ebp
00670BB3   C3                     ret

*)
end;

procedure TForm38._PROC_00670C01(Sender : TObject);
begin
(*
00670C01   8BEC                   mov     ebp, esp
00670C03   33C0                   xor     eax, eax
00670C05   55                     push    ebp
00670C06   68250C6700             push    $00670C25
00670C0B   64FF30                 push    dword ptr fs:[eax]
00670C0E   648920                 mov     fs:[eax], esp
00670C11   FF0510366B00           inc     dword ptr [$006B3610]
00670C17   33C0                   xor     eax, eax
00670C19   5A                     pop     edx
00670C1A   59                     pop     ecx
00670C1B   59                     pop     ecx
00670C1C   648910                 mov     fs:[eax], edx

****** FINALLY
|
00670C1F   682C0C6700             push    $00670C2C
00670C24   C3                     ret

00670C25   E93A38D9FF             jmp     00404464
00670C2A   EBF8                   jmp     00670C24

****** END
|
00670C2C   5D                     pop     ebp
00670C2D   C3                     ret

*)
end;

procedure TForm38._PROC_00670C30(Sender : TObject);
begin
(*
00670C30   832D10366B0001         sub     dword ptr [$006B3610], +$01
00670C37   C3                     ret

*)
end;

procedure TForm38._PROC_00670C38(Sender : TObject);
begin
(*
00670C38   840C67                 test    [edi], cl
00670C3B   0000                   add     [eax], al

*)
end;

end.