unit Unit47;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QuickRpt, QRCtrls, ExtCtrls;
type
  TForm47=class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape21: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRLabel16: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel41: TQRLabel;
    QRShape50: TQRShape;
    QRShape27: TQRShape;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRShape13: TQRShape;
    QRLabel5: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel53: TQRLabel;
    QRLabel60: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRShape26: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRSubDetail3: TQRSubDetail;
    QRShape8: TQRShape;
    QRShape30: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape55: TQRShape;
    QRDBText18: TQRDBText;
    QRDBText43: TQRDBText;
    QRDBText44: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    SummaryBand1: TQRBand;
    QRShape34: TQRShape;
    QRShape42: TQRShape;
    QRShape46: TQRShape;
    QRLabel48: TQRLabel;
    QRDBText32: TQRDBText;
    QRDBText34: TQRDBText;
    QRDBText35: TQRDBText;
    QRDBText37: TQRDBText;
    QRDBText38: TQRDBText;
    QRDBText39: TQRDBText;
    QRShape53: TQRShape;
    QRDBText33: TQRDBText;
    QRShape31: TQRShape;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRLabel2: TQRLabel;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRLabel3: TQRLabel;
    QRLabel1: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel4: TQRLabel;
    procedure _PROC_00674FA0(Sender : TObject);
    procedure _PROC_00674FA8(Sender : TObject);
    procedure _PROC_00674FBA(Sender : TObject);
    procedure _PROC_00674FCA(Sender : TObject);
    procedure _PROC_0067558E(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form47: TForm47;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm47._PROC_00674FA0(Sender : TObject);
begin
(*
00674FA0   832D58366B0001         sub     dword ptr [$006B3658], +$01
00674FA7   C3                     ret

*)
end;

procedure TForm47._PROC_00674FA8(Sender : TObject);
begin
(*
00674FA8   F4                     hlt
00674FA9   4F                     dec     edi
00674FAA   670000                 add     [bx+si], al
00674FAD   0000                   add     [eax], al

*)
end;

procedure TForm47._PROC_00674FBA(Sender : TObject);
begin
(*
00674FBA   6700E8                 add     al, ch
00674FBD   50                     push    eax
00674FBE   670000                 add     [bx+si], al
00674FC1   0000                   add     [eax], al

*)
end;

procedure TForm47._PROC_00674FCA(Sender : TObject);
begin
(*
00674FCA   670014                 add     [si], dl
00674FCD   0400                   add     al, +$00
00674FCF   0078B4                 add     [eax-$4C], bh
00674FD2   47                     inc     edi
00674FD3   000C69                 add     [ecx+ebp*2], cl
00674FD6   42                     inc     edx
00674FD7   00D4                   add     ah, dl
00674FD9   E447                   in      al, $47
00674FDB   0088E647002C           add     [eax+$2C0047E6], cl
00674FE1   3F                     aas
00674FE2   40                     inc     eax
00674FE3   00F4                   add     ah, dh
00674FE5   0A4800                 or      cl, byte ptr [eax+$00]
00674FE8   683C400084             push    $8400403C
00674FED   3C40                   cmp     al, $40
00674FEF   00F0                   add     al, dh
00674FF1   E647                   out     $47, al
00674FF3   00A8B6460060           add     [eax+$600046B6], ch
00674FF9   EC                     in      al, dx
00674FFA   47                     inc     edi
00674FFB   0088E14100B0           add     [eax+$B00041E1], cl
00675001   E84700ECE8             call    E953504D
00675006   47                     inc     edi
00675007   00F8                   add     al, bh
00675009   E94700103F             jmp     3F775055
0067500E   46                     inc     esi
0067500F   002469                 add     [ecx+ebp*2], ah
00675012   42                     inc     edx
00675013   0070F2                 add     [eax-$0E], dh
00675016   47                     inc     edi
00675017   000466                 add     [esi], al
0067501A   42                     inc     edx
0067501B   0010                   add     [eax], dl
0067501D   2E48                   dec     eax
0067501F   0048E3                 add     [eax-$1D], cl
00675022   47                     inc     edi
00675023   00BCB14600D8B6         add     [ecx+esi*4+$B6D80046], bh
0067502A   46                     inc     esi
0067502B   0024B6                 add     [esi+esi*4], ah
0067502E   46                     inc     esi
0067502F   00443446               add     [esp+esi+$46], al
00675033   0038                   add     [eax], bh
00675035   AC                     lodsb
00675036   46                     inc     esi
00675037   0050EF                 add     [eax-$11], dl
0067503A   47                     inc     edi
0067503B   0038                   add     [eax], bh
0067503D   A946008C33             test    eax, $338C0046
00675042   46                     inc     esi
00675043   009033460044           add     [eax+$44004633], dl
00675049   F0                     lock
0067504A   47                     inc     edi
0067504B   0030                   add     [eax], dh
0067504D   6446                   inc     esi
0067504F   00F8                   add     al, bh
00675051   3E46                   inc     esi
00675053   0008                   add     [eax], cl
00675055   3546008440             xor     eax, $40840046
0067505A   46                     inc     esi
0067505B   0038                   add     [eax], bh
0067505D   F2                     repne
0067505E   47                     inc     edi
0067505F   0004F1                 add     [ecx+esi*8], al
00675062   47                     inc     edi
00675063   00BC414600B0F2         add     [ecx+eax*2+$F2B00046], bh
0067506A   47                     inc     edi
0067506B   00B4644600C4A9         add     [esp+$A9C40046], dh
00675072   46                     inc     esi
00675073   0080AA460044           add     [eax+$440046AA], al
00675079   A5                     movsd
0067507A   46                     inc     esi
0067507B   0064AA46               add     [edx+ebp*4+$46], ah
0067507F   0030                   add     [eax], dh
00675081   DE4700                 fiadd   word ptr [edi+$00]
00675084   54                     push    esp
00675085   F9                     stc
00675086   47                     inc     edi
00675087   00147F                 add     [edi+edi*2], dl
0067508A   46                     inc     esi
0067508B   0018                   add     [eax], bl
0067508D   06                     push    es
0067508E   48                     dec     eax
0067508F   007809                 add     [eax+$09], bh
00675092   48                     dec     eax
00675093   003408                 add     [eax+ecx], dh
00675096   48                     dec     eax
00675097   00AC7F4600B07F         add     [edi+edi*2+$7FB00046], ch
0067509E   46                     inc     esi
0067509F   00B00A480010           add     [eax+$1000480A], dh
006750A5   7E46                   jle     006750ED
006750A7   00A4AB4600A411         add     [ebx+ebp*4+$11A40046], ah
006750AE   48                     dec     eax
006750AF   0098BD4600E8           add     [eax+$E80046BD], bl
006750B5   A7                     cmpsd
006750B6   46                     inc     esi
006750B7   00B826480024           add     [eax+$24004826], bh
006750BD   D84700                 fadd    dword ptr [edi+$00]
006750C0   D4                     aam
006750C1   DA4700                 fiadd   dword ptr [edi+$00]
006750C4   98                     cwde 
006750C5   17                     pop     ss
006750C6   48                     dec     eax
006750C7   00D4                   add     ah, dl
006750C9   E747                   out     $47, eax
006750CB   0050E8                 add     [eax-$18], dl
006750CE   47                     inc     edi
006750CF   00982A48000C           add     [eax+$C00482A], bl
006750D5   E547                   in      eax, $47
006750D7   009C2548007C0C         add     [ebp+$C7C0048], bl
006750DE   48                     dec     eax
006750DF   005027                 add     [eax+$27], dl
006750E2   48                     dec     eax
006750E3   0034F2                 add     [edx+esi*8], dh
006750E6   47                     inc     edi
006750E7   004700                 add     [edi+$00], al
006750EA   7255                   jb      00675141
006750EC   6700F8                 add     al, bh
006750EF   0200                   add     al, byte ptr [eax]
006750F1   0000                   add     [eax], al

006750F3   0009                   add     [ecx], cl
006750F5   51                     push    ecx
006750F6   7569                   jnz     00675161
006750F8   636B52                 arpl    [ebx+$52], bp
006750FB   657031                 jo      0067512F
006750FE   FC                     cld
006750FF   0200                   add     al, byte ptr [eax]
00675101   0001                   add     [ecx], al
00675103   000A                   add     [edx], cl
00675105   54                     push    esp
00675106   69746C6542616E64       imul    esi, [esp+ebp*2+$65], $646E6142
0067510E   3100                   xor     [eax], eax
00675110   0300                   add     eax, [eax]
00675112   0002                   add     [edx], al
00675114   0009                   add     [ecx], cl
00675116   51                     push    ecx
00675117   52                     push    edx
00675118   53                     push    ebx
00675119   6861706531             push    $31657061
0067511E   360403                 add     al, +$03
00675121   0000                   add     [eax], al

00675123   0200                   add     al, byte ptr [eax]
00675125   095152                 or      [ecx+$52], edx
00675128   53                     push    ebx
00675129   6861706535             push    $35657061
0067512E   3008                   xor     [eax], cl
00675130   0300                   add     eax, [eax]
00675132   0003                   add     [ebx], al
00675134   0008                   add     [eax], cl
00675136   51                     push    ecx
00675137   52                     push    edx
00675138   4C                     dec     esp
00675139   61                     popa
0067513A   62656C                 bound   esp, qword ptr [ebp+$6C]
0067513D   310C03                 xor     [ebx+eax], ecx
00675140   0000                   add     [eax], al

00675142   0200                   add     al, byte ptr [eax]
00675144   095152                 or      [ecx+$52], edx
00675147   53                     push    ebx
00675148   6861706531             push    $31657061
0067514D   37                     aaa
0067514E   1003                   adc     [ebx], al
00675150   0000                   add     [eax], al

00675152   0200                   add     al, byte ptr [eax]
00675154   095152                 or      [ecx+$52], edx
00675157   53                     push    ebx
00675158   6861706532             push    $32657061
0067515D   311403                 xor     [ebx+eax], edx
00675160   0000                   add     [eax], al

00675162   0200                   add     al, byte ptr [eax]
00675164   095152                 or      [ecx+$52], edx
00675167   53                     push    ebx
00675168   6861706532             push    $32657061
0067516D   3418                   xor     al, $18
0067516F   0300                   add     eax, [eax]
00675171   0002                   add     [edx], al
00675173   0009                   add     [ecx], cl
00675175   51                     push    ecx
00675176   52                     push    edx
00675177   53                     push    ebx
00675178   6861706532             push    $32657061
0067517D   351C030000             xor     eax, $0000031C
00675182   0300                   add     eax, [eax]
00675184   095152                 or      [ecx+$52], edx
00675187   4C                     dec     esp
00675188   61                     popa
00675189   62656C                 bound   esp, qword ptr [ebp+$6C]
0067518C   3136                   xor     [esi], esi
0067518E   2003                   and     [ebx], al
00675190   0000                   add     [eax], al

*)
end;

procedure TForm47._PROC_0067558E(Sender : TObject);
begin
(*
0067558E   670007                 add     [bx], al
00675591   07                     pop     es
00675592   54                     push    esp
00675593   46                     inc     esi
00675594   6F                     outsd
00675595   726D                   jb      00675604
00675597   3438                   xor     al, $38
00675599   F4                     hlt
0067559A   4F                     dec     edi
0067559B   6700C0                 add     al, al
0067559E   B547                   mov     ch, $47
006755A0   005E00                 add     [esi+$00], bl
006755A3   06                     push    es
006755A4   55                     push    ebp
006755A5   6E                     outsb
006755A6   697434380000558B       imul    esi, [esp+esi+$38], $8B550000
006755AE   EC                     in      al, dx
006755AF   33C0                   xor     eax, eax
006755B1   55                     push    ebp

* Possible String Reference to: 'éŽîØÿëø]Ã‹Àƒ-`6k'
|
006755B2   68D1556700             push    $006755D1
006755B7   64FF30                 push    dword ptr fs:[eax]
006755BA   648920                 mov     fs:[eax], esp
006755BD   FF0560366B00           inc     dword ptr [$006B3660]
006755C3   33C0                   xor     eax, eax
006755C5   5A                     pop     edx
006755C6   59                     pop     ecx
006755C7   59                     pop     ecx
006755C8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-`6k'
|
006755CB   68D8556700             push    $006755D8
006755D0   C3                     ret

006755D1   E98EEED8FF             jmp     00404464
006755D6   EBF8                   jmp     006755D0

****** END
|
006755D8   5D                     pop     ebp
006755D9   C3                     ret

006755DA   8BC0                   mov     eax, eax
006755DC   832D60366B0001         sub     dword ptr [$006B3660], +$01
006755E3   C3                     ret

006755E4   305667                 xor     [esi+$67], dl
006755E7   0000                   add     [eax], al

006755E9   0000                   add     [eax], al

006755EB   0000                   add     [eax], al

006755ED   0000                   add     [eax], al

006755EF   0000                   add     [eax], al

006755F1   0000                   add     [eax], al

006755F3   0010                   add     [eax], dl
006755F5   5B                     pop     ebx
006755F6   670024                 add     [si], ah
006755F9   57                     push    edi
006755FA   670000                 add     [bx+si], al
006755FD   0000                   add     [eax], al

006755FF   0000                   add     [eax], al

00675601   0000                   add     [eax], al

00675603   00EC                   add     ah, ch
00675605   5A                     pop     edx
00675606   6700EC                 add     ah, ch
00675609   0300                   add     eax, [eax]
0067560B   0078B4                 add     [eax-$4C], bh
0067560E   47                     inc     edi
0067560F   000C69                 add     [ecx+ebp*2], cl
00675612   42                     inc     edx
00675613   00D4                   add     ah, dl
00675615   E447                   in      al, $47
00675617   0088E647002C           add     [eax+$2C0047E6], cl
0067561D   3F                     aas
0067561E   40                     inc     eax
0067561F   00F4                   add     ah, dh
00675621   0A4800                 or      cl, byte ptr [eax+$00]
00675624   683C400084             push    $8400403C
00675629   3C40                   cmp     al, $40
0067562B   00F0                   add     al, dh
0067562D   E647                   out     $47, al
0067562F   00A8B6460060           add     [eax+$600046B6], ch
00675635   EC                     in      al, dx
00675636   47                     inc     edi
00675637   0088E14100B0           add     [eax+$B00041E1], cl
0067563D   E84700ECE8             call    E9535689
00675642   47                     inc     edi
00675643   00F8                   add     al, bh
00675645   E94700103F             jmp     3F775691
0067564A   46                     inc     esi
0067564B   002469                 add     [ecx+ebp*2], ah
0067564E   42                     inc     edx
0067564F   0070F2                 add     [eax-$0E], dh
00675652   47                     inc     edi
00675653   000466                 add     [esi], al
00675656   42                     inc     edx
00675657   0010                   add     [eax], dl
00675659   2E48                   dec     eax
0067565B   0048E3                 add     [eax-$1D], cl
0067565E   47                     inc     edi
0067565F   00BCB14600D8B6         add     [ecx+esi*4+$B6D80046], bh
00675666   46                     inc     esi
00675667   0024B6                 add     [esi+esi*4], ah
0067566A   46                     inc     esi
0067566B   00443446               add     [esp+esi+$46], al
0067566F   0038                   add     [eax], bh
00675671   AC                     lodsb
00675672   46                     inc     esi
00675673   0050EF                 add     [eax-$11], dl
00675676   47                     inc     edi
00675677   0038                   add     [eax], bh
00675679   A946008C33             test    eax, $338C0046
0067567E   46                     inc     esi
0067567F   009033460044           add     [eax+$44004633], dl
00675685   F0                     lock
00675686   47                     inc     edi
00675687   0030                   add     [eax], dh
00675689   6446                   inc     esi
0067568B   00F8                   add     al, bh
0067568D   3E46                   inc     esi
0067568F   0008                   add     [eax], cl
00675691   3546008440             xor     eax, $40840046
00675696   46                     inc     esi
00675697   0038                   add     [eax], bh
00675699   F2                     repne
0067569A   47                     inc     edi
0067569B   0004F1                 add     [ecx+esi*8], al
0067569E   47                     inc     edi
0067569F   00BC414600B0F2         add     [ecx+eax*2+$F2B00046], bh
006756A6   47                     inc     edi
006756A7   00B4644600C4A9         add     [esp+$A9C40046], dh
006756AE   46                     inc     esi
006756AF   0080AA460044           add     [eax+$440046AA], al
006756B5   A5                     movsd
006756B6   46                     inc     esi
006756B7   0064AA46               add     [edx+ebp*4+$46], ah
006756BB   0030                   add     [eax], dh
006756BD   DE4700                 fiadd   word ptr [edi+$00]
006756C0   54                     push    esp
006756C1   F9                     stc
006756C2   47                     inc     edi
006756C3   00147F                 add     [edi+edi*2], dl
006756C6   46                     inc     esi
006756C7   0018                   add     [eax], bl
006756C9   06                     push    es
006756CA   48                     dec     eax
006756CB   007809                 add     [eax+$09], bh
006756CE   48                     dec     eax
006756CF   003408                 add     [eax+ecx], dh
006756D2   48                     dec     eax
006756D3   00AC7F4600B07F         add     [edi+edi*2+$7FB00046], ch
006756DA   46                     inc     esi
006756DB   00B00A480010           add     [eax+$1000480A], dh
006756E1   7E46                   jle     00675729
006756E3   00A4AB4600A411         add     [ebx+ebp*4+$11A40046], ah
006756EA   48                     dec     eax
006756EB   0098BD4600E8           add     [eax+$E80046BD], bl
006756F1   A7                     cmpsd
006756F2   46                     inc     esi
006756F3   00B826480024           add     [eax+$24004826], bh
006756F9   D84700                 fadd    dword ptr [edi+$00]
006756FC   D4                     aam
006756FD   DA4700                 fiadd   dword ptr [edi+$00]
00675700   98                     cwde 
00675701   17                     pop     ss
00675702   48                     dec     eax
00675703   00D4                   add     ah, dl
00675705   E747                   out     $47, eax
00675707   0050E8                 add     [eax-$18], dl
0067570A   47                     inc     edi
0067570B   00982A48000C           add     [eax+$C00482A], bl
00675711   E547                   in      eax, $47
00675713   009C2548007C0C         add     [ebp+$C7C0048], bl
0067571A   48                     dec     eax
0067571B   005027                 add     [eax+$27], dl
0067571E   48                     dec     eax
0067571F   0034F2                 add     [edx+esi*8], dh
00675722   47                     inc     edi
00675723   003D00F45A67           add     [$675AF400], bh
00675729   00F8                   add     al, bh
0067572B   0200                   add     al, byte ptr [eax]
0067572D   0000                   add     [eax], al

*)
end;

end.