unit Unit25;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QuickRpt, QRCtrls, ExtCtrls ;
type
  TForm25=class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape10: TQRShape;
    QRShape8: TQRShape;
    QRLabel1: TQRLabel;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRLabel2: TQRLabel;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRShape9: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRLabel7: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRShape13: TQRShape;
    QRShape15: TQRShape;
    QRLabel15: TQRLabel;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    QRLabel46: TQRLabel;
    QRShape50: TQRShape;
    QRLabel53: TQRLabel;
    QRLabel54: TQRLabel;
    QRShape7: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel8: TQRLabel;
    QRSubDetail3: TQRSubDetail;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRShape49: TQRShape;
    QRDBText18: TQRDBText;
    QRDBText21: TQRDBText;
    QRDBText22: TQRDBText;
    QRDBText2: TQRDBText;
    QRShape14: TQRShape;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText20: TQRDBText;
    QRDBText3: TQRDBText;
    SummaryBand1: TQRBand;
    QRShape34: TQRShape;
    QRShape43: TQRShape;
    QRShape45: TQRShape;
    QRShape47: TQRShape;
    QRLabel48: TQRLabel;
    QRLabel50: TQRLabel;
    QRLabel51: TQRLabel;
    QRLabel52: TQRLabel;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText45: TQRDBText;
    QRDBText46: TQRDBText;
    QRDBText47: TQRDBText;
    QRLabel14: TQRLabel;
    QRDBText40: TQRDBText;
    QRLabel3: TQRLabel;
    QRDBText49: TQRDBText;
    QRLabel4: TQRLabel;
    QRDBText1: TQRDBText;
    procedure _PROC_0066A0EC(Sender : TObject);
    procedure _PROC_0066A0F4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form25: TForm25;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm25._PROC_0066A0EC(Sender : TObject);
begin
(*
0066A0EC   832DA0356B0001         sub     dword ptr [$006B35A0], +$01
0066A0F3   C3                     ret

*)
end;

procedure TForm25._PROC_0066A0F4(Sender : TObject);
begin
(*
0066A0F4   40                     inc     eax
0066A0F5   A166000000             mov     eax, dword ptr [$00000066]
0066A0FA   0000                   add     [eax], al

*)
end;

end.