unit Unit50;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, sComboBox, Buttons, sBitBtn, acPNG,
  ExtCtrls, acImage, sLabel, sPanel;
type
  TForm50=class(TForm)
    sPanel1: TsPanel;
    sLabelFX1: TsLabelFX;
    sImage1: TsImage;
    sPanel2: TsPanel;
    sBitBtn5: TsBitBtn;
    sBitBtn6: TsBitBtn;
    sComboBox1: TsComboBox;
    Edit1: TEdit;
    Edit2: TEdit;
    procedure sBitBtn6Click(Sender : TObject);
    procedure sBitBtn5Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_00673531(Sender : TObject);
    procedure _PROC_00673588(Sender : TObject);
    procedure _PROC_00673590(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form50: TForm50;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm50.sBitBtn6Click(Sender : TObject);
begin
(*
006723F8   55                     push    ebp
006723F9   8BEC                   mov     ebp, esp
006723FB   81C450FFFFFF           add     esp, $FFFFFF50
00672401   56                     push    esi
00672402   57                     push    edi
00672403   33C9                   xor     ecx, ecx
00672405   894DD4                 mov     [ebp-$2C], ecx
00672408   894DD8                 mov     [ebp-$28], ecx
0067240B   894DDC                 mov     [ebp-$24], ecx
0067240E   894DE0                 mov     [ebp-$20], ecx
00672411   894DE4                 mov     [ebp-$1C], ecx
00672414   894DE8                 mov     [ebp-$18], ecx
00672417   894DEC                 mov     [ebp-$14], ecx
0067241A   894DF0                 mov     [ebp-$10], ecx
0067241D   894DF4                 mov     [ebp-$0C], ecx
00672420   8955F8                 mov     [ebp-$08], edx
00672423   8945FC                 mov     [ebp-$04], eax

* Reference to TData instance
|
00672426   8B35D8F06A00           mov     esi, [$006AF0D8]
0067242C   33C0                   xor     eax, eax
0067242E   55                     push    ebp
0067242F   68DA346700             push    $006734DA
00672434   64FF30                 push    dword ptr fs:[eax]
00672437   648920                 mov     fs:[eax], esp
0067243A   33FF                   xor     edi, edi
0067243C   8B06                   mov     eax, [esi]
0067243E   8B80D0070000           mov     eax, [eax+$07D0]

|
00672444   E8E3C0F2FF             call    0059E52C
00672449   8D55F4                 lea     edx, [ebp-$0C]

* Reference to Form50
|
0067244C   A12C366B00             mov     eax, dword ptr [$006B362C]

* Reference to field Form50.OFFS_0310
|
00672451   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.TControl.GetText()
|
00672457   E8CC1CDFFF             call    00464128
0067245C   8B55F4                 mov     edx, [ebp-$0C]
0067245F   8B06                   mov     eax, [esi]
00672461   8B80E4070000           mov     eax, [eax+$07E4]
00672467   8B08                   mov     ecx, [eax]
00672469   FF91B0000000           call    dword ptr [ecx+$00B0]
0067246F   8B06                   mov     eax, [esi]
00672471   8B80D0070000           mov     eax, [eax+$07D0]
00672477   8B10                   mov     edx, [eax]
00672479   FF924C020000           call    dword ptr [edx+$024C]
0067247F   8B06                   mov     eax, [esi]
00672481   8B808C060000           mov     eax, [eax+$068C]

|
00672487   E850BBF2FF             call    0059DFDC
0067248C   E9F50F0000             jmp     00673486
00672491   8B06                   mov     eax, [esi]
00672493   8B80D4070000           mov     eax, [eax+$07D4]

|
00672499   E88EC0F2FF             call    0059E52C
0067249E   47                     inc     edi
0067249F   8B06                   mov     eax, [esi]
006724A1   8B80A4080000           mov     eax, [eax+$08A4]
006724A7   8BD7                   mov     edx, edi
006724A9   8B08                   mov     ecx, [eax]
006724AB   FF91A8000000           call    dword ptr [ecx+$00A8]
006724B1   8D55F0                 lea     edx, [ebp-$10]
006724B4   8B06                   mov     eax, [esi]
006724B6   8B8064090000           mov     eax, [eax+$0964]
006724BC   8B08                   mov     ecx, [eax]
006724BE   FF5160                 call    dword ptr [ecx+$60]
006724C1   8B55F0                 mov     edx, [ebp-$10]
006724C4   8B06                   mov     eax, [esi]
006724C6   8B80A8080000           mov     eax, [eax+$08A8]
006724CC   8B08                   mov     ecx, [eax]
006724CE   FF91B0000000           call    dword ptr [ecx+$00B0]
006724D4   8D55EC                 lea     edx, [ebp-$14]
006724D7   8B06                   mov     eax, [esi]
006724D9   8B80CC090000           mov     eax, [eax+$09CC]
006724DF   8B08                   mov     ecx, [eax]
006724E1   FF5160                 call    dword ptr [ecx+$60]
006724E4   8B55EC                 mov     edx, [ebp-$14]
006724E7   8B06                   mov     eax, [esi]
006724E9   8B80AC080000           mov     eax, [eax+$08AC]
006724EF   8B08                   mov     ecx, [eax]
006724F1   FF91B0000000           call    dword ptr [ecx+$00B0]
006724F7   8D55E8                 lea     edx, [ebp-$18]
006724FA   8B06                   mov     eax, [esi]
006724FC   8B80D0090000           mov     eax, [eax+$09D0]
00672502   8B08                   mov     ecx, [eax]
00672504   FF5160                 call    dword ptr [ecx+$60]
00672507   8B55E8                 mov     edx, [ebp-$18]
0067250A   8B06                   mov     eax, [esi]
0067250C   8B80B0080000           mov     eax, [eax+$08B0]
00672512   8B08                   mov     ecx, [eax]
00672514   FF91B0000000           call    dword ptr [ecx+$00B0]
0067251A   8D55E4                 lea     edx, [ebp-$1C]
0067251D   8B06                   mov     eax, [esi]
0067251F   8B80B0090000           mov     eax, [eax+$09B0]
00672525   8B08                   mov     ecx, [eax]
00672527   FF5160                 call    dword ptr [ecx+$60]
0067252A   8B55E4                 mov     edx, [ebp-$1C]
0067252D   8B06                   mov     eax, [esi]
0067252F   8B80B4080000           mov     eax, [eax+$08B4]
00672535   8B08                   mov     ecx, [eax]
00672537   FF91B0000000           call    dword ptr [ecx+$00B0]
0067253D   8D55E0                 lea     edx, [ebp-$20]
00672540   8B06                   mov     eax, [esi]
00672542   8B80B4090000           mov     eax, [eax+$09B4]
00672548   8B08                   mov     ecx, [eax]
0067254A   FF5160                 call    dword ptr [ecx+$60]
0067254D   8B55E0                 mov     edx, [ebp-$20]
00672550   8B06                   mov     eax, [esi]
00672552   8B80B8080000           mov     eax, [eax+$08B8]
00672558   8B08                   mov     ecx, [eax]
0067255A   FF91B0000000           call    dword ptr [ecx+$00B0]
00672560   8D55DC                 lea     edx, [ebp-$24]
00672563   8B06                   mov     eax, [esi]
00672565   8B80DC090000           mov     eax, [eax+$09DC]
0067256B   8B08                   mov     ecx, [eax]
0067256D   FF5160                 call    dword ptr [ecx+$60]
00672570   8B55DC                 mov     edx, [ebp-$24]
00672573   8B06                   mov     eax, [esi]
00672575   8B80BC080000           mov     eax, [eax+$08BC]
0067257B   8B08                   mov     ecx, [eax]
0067257D   FF91B0000000           call    dword ptr [ecx+$00B0]
00672583   8D55D8                 lea     edx, [ebp-$28]
00672586   8B06                   mov     eax, [esi]
00672588   8B80BC070000           mov     eax, [eax+$07BC]
0067258E   8B08                   mov     ecx, [eax]
00672590   FF5160                 call    dword ptr [ecx+$60]
00672593   8B55D8                 mov     edx, [ebp-$28]
00672596   8B06                   mov     eax, [esi]
00672598   8B80C0080000           mov     eax, [eax+$08C0]
0067259E   8B08                   mov     ecx, [eax]
006725A0   FF91B0000000           call    dword ptr [ecx+$00B0]
006725A6   8D55D4                 lea     edx, [ebp-$2C]
006725A9   8B06                   mov     eax, [esi]
006725AB   8B80C8090000           mov     eax, [eax+$09C8]
006725B1   8B08                   mov     ecx, [eax]
006725B3   FF5160                 call    dword ptr [ecx+$60]
006725B6   8B55D4                 mov     edx, [ebp-$2C]
006725B9   8B06                   mov     eax, [esi]
006725BB   8B80C4080000           mov     eax, [eax+$08C4]
006725C1   8B08                   mov     ecx, [eax]
006725C3   FF91B0000000           call    dword ptr [ecx+$00B0]
006725C9   8B06                   mov     eax, [esi]
006725CB   8B80D0090000           mov     eax, [eax+$09D0]
006725D1   8B10                   mov     edx, [eax]
006725D3   FF5258                 call    dword ptr [edx+$58]
006725D6   8D0480                 lea     eax, [eax+eax*4]
006725D9   8D04C0                 lea     eax, [eax+eax*8]
006725DC   C1E002                 shl     eax, $02
006725DF   8D0440                 lea     eax, [eax+eax*2]
006725E2   8945D0                 mov     [ebp-$30], eax
006725E5   DB45D0                 fild    dword ptr [ebp-$30]
006725E8   D80DE8346700           fmul    dword ptr [$006734E8]
006725EE   83C4F8                 add     esp, -$08
006725F1   DF3C24                 fistp   qword ptr [esp]
006725F4   9B                     wait
006725F5   8B06                   mov     eax, [esi]
006725F7   8B80CC080000           mov     eax, [eax+$08CC]
006725FD   8B10                   mov     edx, [eax]
006725FF   FF929C000000           call    dword ptr [edx+$009C]
00672605   8B06                   mov     eax, [esi]
00672607   8B80B4090000           mov     eax, [eax+$09B4]
0067260D   8B10                   mov     edx, [eax]
0067260F   FF5258                 call    dword ptr [edx+$58]
00672612   8D0480                 lea     eax, [eax+eax*4]
00672615   8D04C0                 lea     eax, [eax+eax*8]
00672618   C1E002                 shl     eax, $02
0067261B   8D0440                 lea     eax, [eax+eax*2]
0067261E   8945D0                 mov     [ebp-$30], eax
00672621   DB45D0                 fild    dword ptr [ebp-$30]
00672624   D80DE8346700           fmul    dword ptr [$006734E8]
0067262A   83C4F8                 add     esp, -$08
0067262D   DF3C24                 fistp   qword ptr [esp]
00672630   9B                     wait
00672631   8B06                   mov     eax, [esi]
00672633   8B80D0080000           mov     eax, [eax+$08D0]
00672639   8B10                   mov     edx, [eax]
0067263B   FF929C000000           call    dword ptr [edx+$009C]
00672641   8B06                   mov     eax, [esi]
00672643   8B80DC090000           mov     eax, [eax+$09DC]
00672649   8B10                   mov     edx, [eax]
0067264B   FF5258                 call    dword ptr [edx+$58]
0067264E   8D0480                 lea     eax, [eax+eax*4]
00672651   8D04C0                 lea     eax, [eax+eax*8]
00672654   C1E002                 shl     eax, $02
00672657   8D0440                 lea     eax, [eax+eax*2]
0067265A   8945D0                 mov     [ebp-$30], eax
0067265D   DB45D0                 fild    dword ptr [ebp-$30]
00672660   D80DE8346700           fmul    dword ptr [$006734E8]
00672666   83C4F8                 add     esp, -$08
00672669   DF3C24                 fistp   qword ptr [esp]
0067266C   9B                     wait
0067266D   8B06                   mov     eax, [esi]
0067266F   8B80D4080000           mov     eax, [eax+$08D4]
00672675   8B10                   mov     edx, [eax]
00672677   FF929C000000           call    dword ptr [edx+$009C]
0067267D   8B06                   mov     eax, [esi]
0067267F   8B80B0070000           mov     eax, [eax+$07B0]
00672685   8B10                   mov     edx, [eax]
00672687   FF5258                 call    dword ptr [edx+$58]
0067268A   C1E002                 shl     eax, $02
0067268D   8D0440                 lea     eax, [eax+eax*2]
00672690   8945D0                 mov     [ebp-$30], eax
00672693   DB45D0                 fild    dword ptr [ebp-$30]
00672696   D80DE8346700           fmul    dword ptr [$006734E8]
0067269C   83C4F8                 add     esp, -$08
0067269F   DF3C24                 fistp   qword ptr [esp]
006726A2   9B                     wait
006726A3   8B06                   mov     eax, [esi]
006726A5   8B80D8080000           mov     eax, [eax+$08D8]
006726AB   8B10                   mov     edx, [eax]
006726AD   FF929C000000           call    dword ptr [edx+$009C]
006726B3   6A00                   push    $00
006726B5   6A00                   push    $00
006726B7   8B06                   mov     eax, [esi]
006726B9   8B80DC080000           mov     eax, [eax+$08DC]
006726BF   8B10                   mov     edx, [eax]
006726C1   FF929C000000           call    dword ptr [edx+$009C]
006726C7   6A00                   push    $00
006726C9   6A00                   push    $00
006726CB   8B06                   mov     eax, [esi]
006726CD   8B80E0080000           mov     eax, [eax+$08E0]
006726D3   8B10                   mov     edx, [eax]
006726D5   FF929C000000           call    dword ptr [edx+$009C]
006726DB   8B06                   mov     eax, [esi]
006726DD   8B80CC080000           mov     eax, [eax+$08CC]
006726E3   8B10                   mov     edx, [eax]
006726E5   FF524C                 call    dword ptr [edx+$4C]
006726E8   DF7DC8                 fistp   qword ptr [ebp-$38]
006726EB   9B                     wait
006726EC   8B06                   mov     eax, [esi]
006726EE   8B80D0080000           mov     eax, [eax+$08D0]
006726F4   8B10                   mov     edx, [eax]
006726F6   FF524C                 call    dword ptr [edx+$4C]
006726F9   DF6DC8                 fild    qword ptr [ebp-$38]
006726FC   DEC1                   faddp   st(1), st(0)
006726FE   DB7DBC                 fstp    tbyte ptr [ebp-$44]
00672701   9B                     wait
00672702   8B06                   mov     eax, [esi]
00672704   8B80D4080000           mov     eax, [eax+$08D4]
0067270A   8B10                   mov     edx, [eax]
0067270C   FF524C                 call    dword ptr [edx+$4C]
0067270F   DB6DBC                 fld     tbyte ptr [ebp-$44]
00672712   DEC1                   faddp   st(1), st(0)
00672714   DB7DB0                 fstp    tbyte ptr [ebp-$50]
00672717   9B                     wait
00672718   8B06                   mov     eax, [esi]
0067271A   8B80D8080000           mov     eax, [eax+$08D8]
00672720   8B10                   mov     edx, [eax]
00672722   FF524C                 call    dword ptr [edx+$4C]
00672725   DB6DB0                 fld     tbyte ptr [ebp-$50]
00672728   DEC1                   faddp   st(1), st(0)
0067272A   DB7DA4                 fstp    tbyte ptr [ebp-$5C]
0067272D   9B                     wait
0067272E   8B06                   mov     eax, [esi]
00672730   8B80DC080000           mov     eax, [eax+$08DC]
00672736   8B10                   mov     edx, [eax]
00672738   FF524C                 call    dword ptr [edx+$4C]
0067273B   DB6DA4                 fld     tbyte ptr [ebp-$5C]
0067273E   DEC1                   faddp   st(1), st(0)
00672740   DB7D98                 fstp    tbyte ptr [ebp-$68]
00672743   9B                     wait
00672744   8B06                   mov     eax, [esi]
00672746   8B80E0080000           mov     eax, [eax+$08E0]
0067274C   8B10                   mov     edx, [eax]
0067274E   FF524C                 call    dword ptr [edx+$4C]
00672751   DB6D98                 fld     tbyte ptr [ebp-$68]
00672754   DEC1                   faddp   st(1), st(0)
00672756   83C4F8                 add     esp, -$08
00672759   DF3C24                 fistp   qword ptr [esp]
0067275C   9B                     wait
0067275D   8B06                   mov     eax, [esi]
0067275F   8B80E4080000           mov     eax, [eax+$08E4]
00672765   8B10                   mov     edx, [eax]
00672767   FF929C000000           call    dword ptr [edx+$009C]
0067276D   8B06                   mov     eax, [esi]
0067276F   8B80E4080000           mov     eax, [eax+$08E4]
00672775   8B10                   mov     edx, [eax]
00672777   FF524C                 call    dword ptr [edx+$4C]
0067277A   D835EC346700           fdiv    dword ptr [$006734EC]
00672780   83C4F8                 add     esp, -$08
00672783   DF3C24                 fistp   qword ptr [esp]
00672786   9B                     wait
00672787   8B06                   mov     eax, [esi]
00672789   8B80E8080000           mov     eax, [eax+$08E8]
0067278F   8B10                   mov     edx, [eax]
00672791   FF929C000000           call    dword ptr [edx+$009C]
00672797   8B06                   mov     eax, [esi]
00672799   8B80D0090000           mov     eax, [eax+$09D0]
0067279F   8B10                   mov     edx, [eax]
006727A1   FF5258                 call    dword ptr [edx+$58]
006727A4   8D0480                 lea     eax, [eax+eax*4]
006727A7   8D04C0                 lea     eax, [eax+eax*8]
006727AA   C1E002                 shl     eax, $02
006727AD   8D0440                 lea     eax, [eax+eax*2]
006727B0   8945D0                 mov     [ebp-$30], eax
006727B3   DB45D0                 fild    dword ptr [ebp-$30]
006727B6   D80DE8346700           fmul    dword ptr [$006734E8]
006727BC   83C4F8                 add     esp, -$08
006727BF   DF3C24                 fistp   qword ptr [esp]
006727C2   9B                     wait
006727C3   8B06                   mov     eax, [esi]
006727C5   8B80EC080000           mov     eax, [eax+$08EC]
006727CB   8B10                   mov     edx, [eax]
006727CD   FF929C000000           call    dword ptr [edx+$009C]
006727D3   8B06                   mov     eax, [esi]
006727D5   8B8058070000           mov     eax, [eax+$0758]
006727DB   8B10                   mov     edx, [eax]
006727DD   FF524C                 call    dword ptr [edx+$4C]
006727E0   D80DEC346700           fmul    dword ptr [$006734EC]
006727E6   83C4F8                 add     esp, -$08
006727E9   DF3C24                 fistp   qword ptr [esp]
006727EC   9B                     wait
006727ED   8B06                   mov     eax, [esi]
006727EF   8B80F0080000           mov     eax, [eax+$08F0]
006727F5   8B10                   mov     edx, [eax]
006727F7   FF929C000000           call    dword ptr [edx+$009C]
006727FD   8B06                   mov     eax, [esi]
006727FF   8B805C070000           mov     eax, [eax+$075C]
00672805   8B10                   mov     edx, [eax]
00672807   FF524C                 call    dword ptr [edx+$4C]
0067280A   D80DEC346700           fmul    dword ptr [$006734EC]
00672810   83C4F8                 add     esp, -$08
00672813   DF3C24                 fistp   qword ptr [esp]
00672816   9B                     wait
00672817   8B06                   mov     eax, [esi]
00672819   8B80F4080000           mov     eax, [eax+$08F4]
0067281F   8B10                   mov     edx, [eax]
00672821   FF929C000000           call    dword ptr [edx+$009C]
00672827   8B06                   mov     eax, [esi]
00672829   8B8060070000           mov     eax, [eax+$0760]
0067282F   8B10                   mov     edx, [eax]
00672831   FF524C                 call    dword ptr [edx+$4C]
00672834   D80DEC346700           fmul    dword ptr [$006734EC]
0067283A   83C4F8                 add     esp, -$08
0067283D   DF3C24                 fistp   qword ptr [esp]
00672840   9B                     wait
00672841   8B06                   mov     eax, [esi]
00672843   8B80F8080000           mov     eax, [eax+$08F8]
00672849   8B10                   mov     edx, [eax]
0067284B   FF929C000000           call    dword ptr [edx+$009C]
00672851   8B06                   mov     eax, [esi]
00672853   8B8088070000           mov     eax, [eax+$0788]
00672859   8B10                   mov     edx, [eax]
0067285B   FF524C                 call    dword ptr [edx+$4C]
0067285E   D80DEC346700           fmul    dword ptr [$006734EC]
00672864   83C4F8                 add     esp, -$08
00672867   DF3C24                 fistp   qword ptr [esp]
0067286A   9B                     wait
0067286B   8B06                   mov     eax, [esi]
0067286D   8B80FC080000           mov     eax, [eax+$08FC]
00672873   8B10                   mov     edx, [eax]
00672875   FF929C000000           call    dword ptr [edx+$009C]
0067287B   8B06                   mov     eax, [esi]
0067287D   8B8064070000           mov     eax, [eax+$0764]
00672883   8B10                   mov     edx, [eax]
00672885   FF524C                 call    dword ptr [edx+$4C]
00672888   D80DEC346700           fmul    dword ptr [$006734EC]
0067288E   83C4F8                 add     esp, -$08
00672891   DF3C24                 fistp   qword ptr [esp]
00672894   9B                     wait
00672895   8B06                   mov     eax, [esi]
00672897   8B8000090000           mov     eax, [eax+$0900]
0067289D   8B10                   mov     edx, [eax]
0067289F   FF929C000000           call    dword ptr [edx+$009C]
006728A5   8B06                   mov     eax, [esi]
006728A7   8B8068070000           mov     eax, [eax+$0768]
006728AD   8B10                   mov     edx, [eax]
006728AF   FF524C                 call    dword ptr [edx+$4C]
006728B2   D80DEC346700           fmul    dword ptr [$006734EC]
006728B8   83C4F8                 add     esp, -$08
006728BB   DF3C24                 fistp   qword ptr [esp]
006728BE   9B                     wait
006728BF   8B06                   mov     eax, [esi]
006728C1   8B8004090000           mov     eax, [eax+$0904]
006728C7   8B10                   mov     edx, [eax]
006728C9   FF929C000000           call    dword ptr [edx+$009C]
006728CF   8B06                   mov     eax, [esi]
006728D1   8B806C070000           mov     eax, [eax+$076C]
006728D7   8B10                   mov     edx, [eax]
006728D9   FF524C                 call    dword ptr [edx+$4C]
006728DC   D80DEC346700           fmul    dword ptr [$006734EC]
006728E2   83C4F8                 add     esp, -$08
006728E5   DF3C24                 fistp   qword ptr [esp]
006728E8   9B                     wait
006728E9   8B06                   mov     eax, [esi]
006728EB   8B8008090000           mov     eax, [eax+$0908]
006728F1   8B10                   mov     edx, [eax]
006728F3   FF929C000000           call    dword ptr [edx+$009C]
006728F9   8B06                   mov     eax, [esi]
006728FB   8B8070070000           mov     eax, [eax+$0770]
00672901   8B10                   mov     edx, [eax]
00672903   FF524C                 call    dword ptr [edx+$4C]
00672906   D80DEC346700           fmul    dword ptr [$006734EC]
0067290C   83C4F8                 add     esp, -$08
0067290F   DF3C24                 fistp   qword ptr [esp]
00672912   9B                     wait
00672913   8B06                   mov     eax, [esi]
00672915   8B800C090000           mov     eax, [eax+$090C]
0067291B   8B10                   mov     edx, [eax]
0067291D   FF929C000000           call    dword ptr [edx+$009C]
00672923   8B06                   mov     eax, [esi]
00672925   8B8074070000           mov     eax, [eax+$0774]
0067292B   8B10                   mov     edx, [eax]
0067292D   FF524C                 call    dword ptr [edx+$4C]
00672930   D80DEC346700           fmul    dword ptr [$006734EC]
00672936   83C4F8                 add     esp, -$08
00672939   DF3C24                 fistp   qword ptr [esp]
0067293C   9B                     wait
0067293D   8B06                   mov     eax, [esi]
0067293F   8B8010090000           mov     eax, [eax+$0910]
00672945   8B10                   mov     edx, [eax]
00672947   FF929C000000           call    dword ptr [edx+$009C]
0067294D   8B06                   mov     eax, [esi]
0067294F   8B8078070000           mov     eax, [eax+$0778]
00672955   8B10                   mov     edx, [eax]
00672957   FF524C                 call    dword ptr [edx+$4C]
0067295A   D80DEC346700           fmul    dword ptr [$006734EC]
00672960   83C4F8                 add     esp, -$08
00672963   DF3C24                 fistp   qword ptr [esp]
00672966   9B                     wait
00672967   8B06                   mov     eax, [esi]
00672969   8B8014090000           mov     eax, [eax+$0914]
0067296F   8B10                   mov     edx, [eax]
00672971   FF929C000000           call    dword ptr [edx+$009C]
00672977   8B06                   mov     eax, [esi]
00672979   8B8080070000           mov     eax, [eax+$0780]
0067297F   8B10                   mov     edx, [eax]
00672981   FF524C                 call    dword ptr [edx+$4C]
00672984   D80DEC346700           fmul    dword ptr [$006734EC]
0067298A   83C4F8                 add     esp, -$08
0067298D   DF3C24                 fistp   qword ptr [esp]
00672990   9B                     wait
00672991   8B06                   mov     eax, [esi]
00672993   8B8018090000           mov     eax, [eax+$0918]
00672999   8B10                   mov     edx, [eax]
0067299B   FF929C000000           call    dword ptr [edx+$009C]
006729A1   8B06                   mov     eax, [esi]
006729A3   8B807C070000           mov     eax, [eax+$077C]
006729A9   8B10                   mov     edx, [eax]
006729AB   FF524C                 call    dword ptr [edx+$4C]
006729AE   D80DEC346700           fmul    dword ptr [$006734EC]
006729B4   83C4F8                 add     esp, -$08
006729B7   DF3C24                 fistp   qword ptr [esp]
006729BA   9B                     wait
006729BB   8B06                   mov     eax, [esi]
006729BD   8B801C090000           mov     eax, [eax+$091C]
006729C3   8B10                   mov     edx, [eax]
006729C5   FF929C000000           call    dword ptr [edx+$009C]
006729CB   8B06                   mov     eax, [esi]
006729CD   8B80F0080000           mov     eax, [eax+$08F0]
006729D3   8B10                   mov     edx, [eax]
006729D5   FF524C                 call    dword ptr [edx+$4C]
006729D8   DF7DC8                 fistp   qword ptr [ebp-$38]
006729DB   9B                     wait
006729DC   8B06                   mov     eax, [esi]
006729DE   8B80F4080000           mov     eax, [eax+$08F4]
006729E4   8B10                   mov     edx, [eax]
006729E6   FF524C                 call    dword ptr [edx+$4C]
006729E9   DF6DC8                 fild    qword ptr [ebp-$38]
006729EC   DEC1                   faddp   st(1), st(0)
006729EE   DB7DBC                 fstp    tbyte ptr [ebp-$44]
006729F1   9B                     wait
006729F2   8B06                   mov     eax, [esi]
006729F4   8B80F8080000           mov     eax, [eax+$08F8]
006729FA   8B10                   mov     edx, [eax]
006729FC   FF524C                 call    dword ptr [edx+$4C]
006729FF   DB6DBC                 fld     tbyte ptr [ebp-$44]
00672A02   DEC1                   faddp   st(1), st(0)
00672A04   DB7DB0                 fstp    tbyte ptr [ebp-$50]
00672A07   9B                     wait
00672A08   8B06                   mov     eax, [esi]
00672A0A   8B80FC080000           mov     eax, [eax+$08FC]
00672A10   8B10                   mov     edx, [eax]
00672A12   FF524C                 call    dword ptr [edx+$4C]
00672A15   DB6DB0                 fld     tbyte ptr [ebp-$50]
00672A18   DEC1                   faddp   st(1), st(0)
00672A1A   DB7DA4                 fstp    tbyte ptr [ebp-$5C]
00672A1D   9B                     wait
00672A1E   8B06                   mov     eax, [esi]
00672A20   8B8000090000           mov     eax, [eax+$0900]
00672A26   8B10                   mov     edx, [eax]
00672A28   FF524C                 call    dword ptr [edx+$4C]
00672A2B   DB6DA4                 fld     tbyte ptr [ebp-$5C]
00672A2E   DEC1                   faddp   st(1), st(0)
00672A30   DB7D98                 fstp    tbyte ptr [ebp-$68]
00672A33   9B                     wait
00672A34   8B06                   mov     eax, [esi]
00672A36   8B8004090000           mov     eax, [eax+$0904]
00672A3C   8B10                   mov     edx, [eax]
00672A3E   FF524C                 call    dword ptr [edx+$4C]
00672A41   DB6D98                 fld     tbyte ptr [ebp-$68]
00672A44   DEC1                   faddp   st(1), st(0)
00672A46   DB7D8C                 fstp    tbyte ptr [ebp-$74]
00672A49   9B                     wait
00672A4A   8B06                   mov     eax, [esi]
00672A4C   8B8008090000           mov     eax, [eax+$0908]
00672A52   8B10                   mov     edx, [eax]
00672A54   FF524C                 call    dword ptr [edx+$4C]
00672A57   DB6D8C                 fld     tbyte ptr [ebp-$74]
00672A5A   DEC1                   faddp   st(1), st(0)
00672A5C   DB7D80                 fstp    tbyte ptr [ebp-$80]
00672A5F   9B                     wait
00672A60   8B06                   mov     eax, [esi]
00672A62   8B800C090000           mov     eax, [eax+$090C]
00672A68   8B10                   mov     edx, [eax]
00672A6A   FF524C                 call    dword ptr [edx+$4C]
00672A6D   DB6D80                 fld     tbyte ptr [ebp-$80]
00672A70   DEC1                   faddp   st(1), st(0)
00672A72   DBBD74FFFFFF           fstp    tbyte ptr [ebp+$FFFFFF74]
00672A78   9B                     wait
00672A79   8B06                   mov     eax, [esi]
00672A7B   8B8010090000           mov     eax, [eax+$0910]
00672A81   8B10                   mov     edx, [eax]
00672A83   FF524C                 call    dword ptr [edx+$4C]
00672A86   DBAD74FFFFFF           fld     tbyte ptr [ebp+$FFFFFF74]
00672A8C   DEC1                   faddp   st(1), st(0)
00672A8E   DBBD68FFFFFF           fstp    tbyte ptr [ebp+$FFFFFF68]
00672A94   9B                     wait
00672A95   8B06                   mov     eax, [esi]
00672A97   8B8014090000           mov     eax, [eax+$0914]
00672A9D   8B10                   mov     edx, [eax]
00672A9F   FF524C                 call    dword ptr [edx+$4C]
00672AA2   DBAD68FFFFFF           fld     tbyte ptr [ebp+$FFFFFF68]
00672AA8   DEC1                   faddp   st(1), st(0)
00672AAA   DBBD5CFFFFFF           fstp    tbyte ptr [ebp+$FFFFFF5C]
00672AB0   9B                     wait
00672AB1   8B06                   mov     eax, [esi]
00672AB3   8B8018090000           mov     eax, [eax+$0918]
00672AB9   8B10                   mov     edx, [eax]
00672ABB   FF524C                 call    dword ptr [edx+$4C]
00672ABE   DBAD5CFFFFFF           fld     tbyte ptr [ebp+$FFFFFF5C]
00672AC4   DEC1                   faddp   st(1), st(0)
00672AC6   DBBD50FFFFFF           fstp    tbyte ptr [ebp+$FFFFFF50]
00672ACC   9B                     wait
00672ACD   8B06                   mov     eax, [esi]
00672ACF   8B801C090000           mov     eax, [eax+$091C]
00672AD5   8B10                   mov     edx, [eax]
00672AD7   FF524C                 call    dword ptr [edx+$4C]
00672ADA   DBAD50FFFFFF           fld     tbyte ptr [ebp+$FFFFFF50]
00672AE0   DEC1                   faddp   st(1), st(0)
00672AE2   83C4F8                 add     esp, -$08
00672AE5   DF3C24                 fistp   qword ptr [esp]
00672AE8   9B                     wait
00672AE9   8B06                   mov     eax, [esi]
00672AEB   8B8020090000           mov     eax, [eax+$0920]
00672AF1   8B10                   mov     edx, [eax]
00672AF3   FF929C000000           call    dword ptr [edx+$009C]
00672AF9   8B06                   mov     eax, [esi]
00672AFB   8B8020090000           mov     eax, [eax+$0920]
00672B01   8B10                   mov     edx, [eax]
00672B03   FF524C                 call    dword ptr [edx+$4C]
00672B06   D835EC346700           fdiv    dword ptr [$006734EC]
00672B0C   83C4F8                 add     esp, -$08
00672B0F   DF3C24                 fistp   qword ptr [esp]
00672B12   9B                     wait
00672B13   8B06                   mov     eax, [esi]
00672B15   8B8024090000           mov     eax, [eax+$0924]
00672B1B   8B10                   mov     edx, [eax]
00672B1D   FF929C000000           call    dword ptr [edx+$009C]
00672B23   8B06                   mov     eax, [esi]
00672B25   8B80C0070000           mov     eax, [eax+$07C0]
00672B2B   8B10                   mov     edx, [eax]
00672B2D   FF524C                 call    dword ptr [edx+$4C]
00672B30   D80DEC346700           fmul    dword ptr [$006734EC]
00672B36   83C4F8                 add     esp, -$08
00672B39   DF3C24                 fistp   qword ptr [esp]
00672B3C   9B                     wait
00672B3D   8B06                   mov     eax, [esi]
00672B3F   8B8028090000           mov     eax, [eax+$0928]
00672B45   8B10                   mov     edx, [eax]
00672B47   FF929C000000           call    dword ptr [edx+$009C]
00672B4D   8B06                   mov     eax, [esi]
00672B4F   8B8050070000           mov     eax, [eax+$0750]
00672B55   8B10                   mov     edx, [eax]
00672B57   FF524C                 call    dword ptr [edx+$4C]
00672B5A   D81DF0346700           fcomp   dword ptr [$006734F0]
00672B60   DFE0                   fstsw   ax
00672B62   9E                     sahf
00672B63   7376                   jnb     00672BDB
00672B65   8B06                   mov     eax, [esi]
00672B67   8B8050070000           mov     eax, [eax+$0750]
00672B6D   8B10                   mov     edx, [eax]
00672B6F   FF524C                 call    dword ptr [edx+$4C]
00672B72   D80DF4346700           fmul    dword ptr [$006734F4]
00672B78   DB7DBC                 fstp    tbyte ptr [ebp-$44]
00672B7B   9B                     wait
00672B7C   8B06                   mov     eax, [esi]
00672B7E   8B8084070000           mov     eax, [eax+$0784]
00672B84   8B10                   mov     edx, [eax]
00672B86   FF524C                 call    dword ptr [edx+$4C]
00672B89   DB6DBC                 fld     tbyte ptr [ebp-$44]
00672B8C   DEE9                   fsubp   st(1), st(0)
00672B8E   D80DEC346700           fmul    dword ptr [$006734EC]
00672B94   83C4F8                 add     esp, -$08
00672B97   DF3C24                 fistp   qword ptr [esp]
00672B9A   9B                     wait
00672B9B   8B06                   mov     eax, [esi]
00672B9D   8B802C090000           mov     eax, [eax+$092C]
00672BA3   8B10                   mov     edx, [eax]
00672BA5   FF929C000000           call    dword ptr [edx+$009C]
00672BAB   8B06                   mov     eax, [esi]
00672BAD   8B8050070000           mov     eax, [eax+$0750]
00672BB3   8B10                   mov     edx, [eax]
00672BB5   FF524C                 call    dword ptr [edx+$4C]
00672BB8   D80DF4346700           fmul    dword ptr [$006734F4]
00672BBE   D80DEC346700           fmul    dword ptr [$006734EC]
00672BC4   83C4F8                 add     esp, -$08
00672BC7   DF3C24                 fistp   qword ptr [esp]
00672BCA   9B                     wait
00672BCB   8B06                   mov     eax, [esi]
00672BCD   8B8030090000           mov     eax, [eax+$0930]
00672BD3   8B10                   mov     edx, [eax]
00672BD5   FF929C000000           call    dword ptr [edx+$009C]
00672BDB   8B06                   mov     eax, [esi]
00672BDD   8B8050070000           mov     eax, [eax+$0750]
00672BE3   8B10                   mov     edx, [eax]
00672BE5   FF524C                 call    dword ptr [edx+$4C]
00672BE8   D81DF0346700           fcomp   dword ptr [$006734F0]
00672BEE   DFE0                   fstsw   ax
00672BF0   9E                     sahf
00672BF1   7247                   jb      00672C3A
00672BF3   8B06                   mov     eax, [esi]
00672BF5   8B8084070000           mov     eax, [eax+$0784]
00672BFB   8B10                   mov     edx, [eax]
00672BFD   FF524C                 call    dword ptr [edx+$4C]
00672C00   D825F8346700           fsub    dword ptr [$006734F8]
00672C06   D80DEC346700           fmul    dword ptr [$006734EC]
00672C0C   83C4F8                 add     esp, -$08
00672C0F   DF3C24                 fistp   qword ptr [esp]
00672C12   9B                     wait
00672C13   8B06                   mov     eax, [esi]
00672C15   8B802C090000           mov     eax, [eax+$092C]
00672C1B   8B10                   mov     edx, [eax]
00672C1D   FF929C000000           call    dword ptr [edx+$009C]
00672C23   6A00                   push    $00
00672C25   6850CC3D00             push    $003DCC50
00672C2A   8B06                   mov     eax, [esi]
00672C2C   8B8030090000           mov     eax, [eax+$0930]
00672C32   8B10                   mov     edx, [eax]
00672C34   FF929C000000           call    dword ptr [edx+$009C]
00672C3A   8B06                   mov     eax, [esi]
00672C3C   8B8028090000           mov     eax, [eax+$0928]
00672C42   8B10                   mov     edx, [eax]
00672C44   FF524C                 call    dword ptr [edx+$4C]
00672C47   DF7DC8                 fistp   qword ptr [ebp-$38]
00672C4A   9B                     wait
00672C4B   8B06                   mov     eax, [esi]
00672C4D   8B802C090000           mov     eax, [eax+$092C]
00672C53   8B10                   mov     edx, [eax]
00672C55   FF524C                 call    dword ptr [edx+$4C]
00672C58   DF6DC8                 fild    qword ptr [ebp-$38]
00672C5B   DEC1                   faddp   st(1), st(0)
00672C5D   DB7DBC                 fstp    tbyte ptr [ebp-$44]
00672C60   9B                     wait
00672C61   8B06                   mov     eax, [esi]
00672C63   8B8030090000           mov     eax, [eax+$0930]
00672C69   8B10                   mov     edx, [eax]
00672C6B   FF524C                 call    dword ptr [edx+$4C]
00672C6E   DB6DBC                 fld     tbyte ptr [ebp-$44]
00672C71   DEC1                   faddp   st(1), st(0)
00672C73   83C4F8                 add     esp, -$08
00672C76   DF3C24                 fistp   qword ptr [esp]
00672C79   9B                     wait
00672C7A   8B06                   mov     eax, [esi]
00672C7C   8B8038090000           mov     eax, [eax+$0938]
00672C82   8B10                   mov     edx, [eax]
00672C84   FF929C000000           call    dword ptr [edx+$009C]
00672C8A   8B06                   mov     eax, [esi]
00672C8C   8B8038090000           mov     eax, [eax+$0938]
00672C92   8B10                   mov     edx, [eax]
00672C94   FF524C                 call    dword ptr [edx+$4C]
00672C97   D835EC346700           fdiv    dword ptr [$006734EC]
00672C9D   83C4F8                 add     esp, -$08
00672CA0   DF3C24                 fistp   qword ptr [esp]
00672CA3   9B                     wait
00672CA4   8B06                   mov     eax, [esi]
00672CA6   8B803C090000           mov     eax, [eax+$093C]
00672CAC   8B10                   mov     edx, [eax]
00672CAE   FF929C000000           call    dword ptr [edx+$009C]
00672CB4   8B06                   mov     eax, [esi]
00672CB6   8B8040090000           mov     eax, [eax+$0940]
00672CBC   8B10                   mov     edx, [eax]
00672CBE   FF524C                 call    dword ptr [edx+$4C]
00672CC1   DF7DC8                 fistp   qword ptr [ebp-$38]
00672CC4   9B                     wait
00672CC5   8B06                   mov     eax, [esi]
00672CC7   8B80E4080000           mov     eax, [eax+$08E4]
00672CCD   8B10                   mov     edx, [eax]
00672CCF   FF524C                 call    dword ptr [edx+$4C]
00672CD2   DF6DC8                 fild    qword ptr [ebp-$38]
00672CD5   DEC1                   faddp   st(1), st(0)
00672CD7   DB7DBC                 fstp    tbyte ptr [ebp-$44]
00672CDA   9B                     wait
00672CDB   8B06                   mov     eax, [esi]
00672CDD   8B8020090000           mov     eax, [eax+$0920]
00672CE3   8B10                   mov     edx, [eax]
00672CE5   FF524C                 call    dword ptr [edx+$4C]
00672CE8   DB6DBC                 fld     tbyte ptr [ebp-$44]
00672CEB   DEC1                   faddp   st(1), st(0)
00672CED   DB7DB0                 fstp    tbyte ptr [ebp-$50]
00672CF0   9B                     wait
00672CF1   8B06                   mov     eax, [esi]
00672CF3   8B8038090000           mov     eax, [eax+$0938]
00672CF9   8B10                   mov     edx, [eax]
00672CFB   FF524C                 call    dword ptr [edx+$4C]
00672CFE   DB6DB0                 fld     tbyte ptr [ebp-$50]
00672D01   DEC1                   faddp   st(1), st(0)
00672D03   83C4F8                 add     esp, -$08
00672D06   DF3C24                 fistp   qword ptr [esp]
00672D09   9B                     wait
00672D0A   8B06                   mov     eax, [esi]
00672D0C   8B8040090000           mov     eax, [eax+$0940]
00672D12   8B10                   mov     edx, [eax]
00672D14   FF929C000000           call    dword ptr [edx+$009C]
00672D1A   8B06                   mov     eax, [esi]
00672D1C   8B8044090000           mov     eax, [eax+$0944]
00672D22   8B10                   mov     edx, [eax]
00672D24   FF524C                 call    dword ptr [edx+$4C]
00672D27   DF7DC8                 fistp   qword ptr [ebp-$38]
00672D2A   9B                     wait
00672D2B   8B06                   mov     eax, [esi]
00672D2D   8B80E8080000           mov     eax, [eax+$08E8]
00672D33   8B10                   mov     edx, [eax]
00672D35   FF524C                 call    dword ptr [edx+$4C]
00672D38   DF6DC8                 fild    qword ptr [ebp-$38]
00672D3B   DEC1                   faddp   st(1), st(0)
00672D3D   DB7DBC                 fstp    tbyte ptr [ebp-$44]
00672D40   9B                     wait
00672D41   8B06                   mov     eax, [esi]
00672D43   8B8024090000           mov     eax, [eax+$0924]
00672D49   8B10                   mov     edx, [eax]
00672D4B   FF524C                 call    dword ptr [edx+$4C]
00672D4E   DB6DBC                 fld     tbyte ptr [ebp-$44]
00672D51   DEC1                   faddp   st(1), st(0)
00672D53   DB7DB0                 fstp    tbyte ptr [ebp-$50]
00672D56   9B                     wait
00672D57   8B06                   mov     eax, [esi]
00672D59   8B803C090000           mov     eax, [eax+$093C]
00672D5F   8B10                   mov     edx, [eax]
00672D61   FF524C                 call    dword ptr [edx+$4C]
00672D64   DB6DB0                 fld     tbyte ptr [ebp-$50]
00672D67   DEC1                   faddp   st(1), st(0)
00672D69   83C4F8                 add     esp, -$08
00672D6C   DF3C24                 fistp   qword ptr [esp]
00672D6F   9B                     wait
00672D70   8B06                   mov     eax, [esi]
00672D72   8B8044090000           mov     eax, [eax+$0944]
00672D78   8B10                   mov     edx, [eax]
00672D7A   FF929C000000           call    dword ptr [edx+$009C]
00672D80   8B06                   mov     eax, [esi]
00672D82   8B80D4070000           mov     eax, [eax+$07D4]
00672D88   8B10                   mov     edx, [eax]
00672D8A   FF924C020000           call    dword ptr [edx+$024C]
00672D90   8B06                   mov     eax, [esi]
00672D92   8B80D0070000           mov     eax, [eax+$07D0]

|
00672D98   E84BB6F2FF             call    0059E3E8
00672D9D   8B06                   mov     eax, [esi]
00672D9F   8B8018080000           mov     eax, [eax+$0818]
00672DA5   8B10                   mov     edx, [eax]
00672DA7   FF524C                 call    dword ptr [edx+$4C]
00672DAA   DF7DC8                 fistp   qword ptr [ebp-$38]
00672DAD   9B                     wait
00672DAE   8B06                   mov     eax, [esi]
00672DB0   8B80CC080000           mov     eax, [eax+$08CC]
00672DB6   8B10                   mov     edx, [eax]
00672DB8   FF524C                 call    dword ptr [edx+$4C]
00672DBB   DF6DC8                 fild    qword ptr [ebp-$38]
00672DBE   DEC1                   faddp   st(1), st(0)
00672DC0   83C4F8                 add     esp, -$08
00672DC3   DF3C24                 fistp   qword ptr [esp]
00672DC6   9B                     wait
00672DC7   8B06                   mov     eax, [esi]
00672DC9   8B8018080000           mov     eax, [eax+$0818]
00672DCF   8B10                   mov     edx, [eax]
00672DD1   FF929C000000           call    dword ptr [edx+$009C]
00672DD7   8B06                   mov     eax, [esi]
00672DD9   8B801C080000           mov     eax, [eax+$081C]
00672DDF   8B10                   mov     edx, [eax]
00672DE1   FF524C                 call    dword ptr [edx+$4C]
00672DE4   DF7DC8                 fistp   qword ptr [ebp-$38]
00672DE7   9B                     wait
00672DE8   8B06                   mov     eax, [esi]
00672DEA   8B80D0080000           mov     eax, [eax+$08D0]
00672DF0   8B10                   mov     edx, [eax]
00672DF2   FF524C                 call    dword ptr [edx+$4C]
00672DF5   DF6DC8                 fild    qword ptr [ebp-$38]
00672DF8   DEC1                   faddp   st(1), st(0)
00672DFA   83C4F8                 add     esp, -$08
00672DFD   DF3C24                 fistp   qword ptr [esp]
00672E00   9B                     wait
00672E01   8B06                   mov     eax, [esi]
00672E03   8B801C080000           mov     eax, [eax+$081C]
00672E09   8B10                   mov     edx, [eax]
00672E0B   FF929C000000           call    dword ptr [edx+$009C]
00672E11   8B06                   mov     eax, [esi]
00672E13   8B8020080000           mov     eax, [eax+$0820]
00672E19   8B10                   mov     edx, [eax]
00672E1B   FF524C                 call    dword ptr [edx+$4C]
00672E1E   DF7DC8                 fistp   qword ptr [ebp-$38]
00672E21   9B                     wait
00672E22   8B06                   mov     eax, [esi]
00672E24   8B80D4080000           mov     eax, [eax+$08D4]
00672E2A   8B10                   mov     edx, [eax]
00672E2C   FF524C                 call    dword ptr [edx+$4C]
00672E2F   DF6DC8                 fild    qword ptr [ebp-$38]
00672E32   DEC1                   faddp   st(1), st(0)
00672E34   83C4F8                 add     esp, -$08
00672E37   DF3C24                 fistp   qword ptr [esp]
00672E3A   9B                     wait
00672E3B   8B06                   mov     eax, [esi]
00672E3D   8B8020080000           mov     eax, [eax+$0820]
00672E43   8B10                   mov     edx, [eax]
00672E45   FF929C000000           call    dword ptr [edx+$009C]
00672E4B   8B06                   mov     eax, [esi]
00672E4D   8B8024080000           mov     eax, [eax+$0824]
00672E53   8B10                   mov     edx, [eax]
00672E55   FF524C                 call    dword ptr [edx+$4C]
00672E58   DF7DC8                 fistp   qword ptr [ebp-$38]
00672E5B   9B                     wait
00672E5C   8B06                   mov     eax, [esi]
00672E5E   8B80D8080000           mov     eax, [eax+$08D8]
00672E64   8B10                   mov     edx, [eax]
00672E66   FF524C                 call    dword ptr [edx+$4C]
00672E69   DF6DC8                 fild    qword ptr [ebp-$38]
00672E6C   DEC1                   faddp   st(1), st(0)
00672E6E   83C4F8                 add     esp, -$08
00672E71   DF3C24                 fistp   qword ptr [esp]
00672E74   9B                     wait
00672E75   8B06                   mov     eax, [esi]
00672E77   8B8024080000           mov     eax, [eax+$0824]
00672E7D   8B10                   mov     edx, [eax]
00672E7F   FF929C000000           call    dword ptr [edx+$009C]
00672E85   8B06                   mov     eax, [esi]
00672E87   8B8028080000           mov     eax, [eax+$0828]
00672E8D   8B10                   mov     edx, [eax]
00672E8F   FF524C                 call    dword ptr [edx+$4C]
00672E92   DF7DC8                 fistp   qword ptr [ebp-$38]
00672E95   9B                     wait
00672E96   8B06                   mov     eax, [esi]
00672E98   8B80DC080000           mov     eax, [eax+$08DC]
00672E9E   8B10                   mov     edx, [eax]
00672EA0   FF524C                 call    dword ptr [edx+$4C]
00672EA3   DF6DC8                 fild    qword ptr [ebp-$38]
00672EA6   DEC1                   faddp   st(1), st(0)
00672EA8   83C4F8                 add     esp, -$08
00672EAB   DF3C24                 fistp   qword ptr [esp]
00672EAE   9B                     wait
00672EAF   8B06                   mov     eax, [esi]
00672EB1   8B8028080000           mov     eax, [eax+$0828]
00672EB7   8B10                   mov     edx, [eax]
00672EB9   FF929C000000           call    dword ptr [edx+$009C]
00672EBF   8B06                   mov     eax, [esi]
00672EC1   8B802C080000           mov     eax, [eax+$082C]
00672EC7   8B10                   mov     edx, [eax]
00672EC9   FF524C                 call    dword ptr [edx+$4C]
00672ECC   DF7DC8                 fistp   qword ptr [ebp-$38]
00672ECF   9B                     wait
00672ED0   8B06                   mov     eax, [esi]
00672ED2   8B80E0080000           mov     eax, [eax+$08E0]
00672ED8   8B10                   mov     edx, [eax]
00672EDA   FF524C                 call    dword ptr [edx+$4C]
00672EDD   DF6DC8                 fild    qword ptr [ebp-$38]
00672EE0   DEC1                   faddp   st(1), st(0)
00672EE2   83C4F8                 add     esp, -$08
00672EE5   DF3C24                 fistp   qword ptr [esp]
00672EE8   9B                     wait
00672EE9   8B06                   mov     eax, [esi]
00672EEB   8B802C080000           mov     eax, [eax+$082C]
00672EF1   8B10                   mov     edx, [eax]
00672EF3   FF929C000000           call    dword ptr [edx+$009C]
00672EF9   8B06                   mov     eax, [esi]
00672EFB   8B8030080000           mov     eax, [eax+$0830]
00672F01   8B10                   mov     edx, [eax]
00672F03   FF524C                 call    dword ptr [edx+$4C]
00672F06   DF7DC8                 fistp   qword ptr [ebp-$38]
00672F09   9B                     wait
00672F0A   8B06                   mov     eax, [esi]
00672F0C   8B80E4080000           mov     eax, [eax+$08E4]
00672F12   8B10                   mov     edx, [eax]
00672F14   FF524C                 call    dword ptr [edx+$4C]
00672F17   DF6DC8                 fild    qword ptr [ebp-$38]
00672F1A   DEC1                   faddp   st(1), st(0)
00672F1C   83C4F8                 add     esp, -$08
00672F1F   DF3C24                 fistp   qword ptr [esp]
00672F22   9B                     wait
00672F23   8B06                   mov     eax, [esi]
00672F25   8B8030080000           mov     eax, [eax+$0830]
00672F2B   8B10                   mov     edx, [eax]
00672F2D   FF929C000000           call    dword ptr [edx+$009C]
00672F33   8B06                   mov     eax, [esi]
00672F35   8B8034080000           mov     eax, [eax+$0834]
00672F3B   8B10                   mov     edx, [eax]
00672F3D   FF524C                 call    dword ptr [edx+$4C]
00672F40   DF7DC8                 fistp   qword ptr [ebp-$38]
00672F43   9B                     wait
00672F44   8B06                   mov     eax, [esi]
00672F46   8B80E8080000           mov     eax, [eax+$08E8]
00672F4C   8B10                   mov     edx, [eax]
00672F4E   FF524C                 call    dword ptr [edx+$4C]
00672F51   DF6DC8                 fild    qword ptr [ebp-$38]
00672F54   DEC1                   faddp   st(1), st(0)
00672F56   83C4F8                 add     esp, -$08
00672F59   DF3C24                 fistp   qword ptr [esp]
00672F5C   9B                     wait
00672F5D   8B06                   mov     eax, [esi]
00672F5F   8B8034080000           mov     eax, [eax+$0834]
00672F65   8B10                   mov     edx, [eax]
00672F67   FF929C000000           call    dword ptr [edx+$009C]
00672F6D   8B06                   mov     eax, [esi]
00672F6F   8B8038080000           mov     eax, [eax+$0838]
00672F75   8B10                   mov     edx, [eax]
00672F77   FF524C                 call    dword ptr [edx+$4C]
00672F7A   DF7DC8                 fistp   qword ptr [ebp-$38]
00672F7D   9B                     wait
00672F7E   8B06                   mov     eax, [esi]
00672F80   8B80EC080000           mov     eax, [eax+$08EC]
00672F86   8B10                   mov     edx, [eax]
00672F88   FF524C                 call    dword ptr [edx+$4C]
00672F8B   DF6DC8                 fild    qword ptr [ebp-$38]
00672F8E   DEC1                   faddp   st(1), st(0)
00672F90   83C4F8                 add     esp, -$08
00672F93   DF3C24                 fistp   qword ptr [esp]
00672F96   9B                     wait
00672F97   8B06                   mov     eax, [esi]
00672F99   8B8038080000           mov     eax, [eax+$0838]
00672F9F   8B10                   mov     edx, [eax]
00672FA1   FF929C000000           call    dword ptr [edx+$009C]
00672FA7   8B06                   mov     eax, [esi]
00672FA9   8B803C080000           mov     eax, [eax+$083C]
00672FAF   8B10                   mov     edx, [eax]
00672FB1   FF524C                 call    dword ptr [edx+$4C]
00672FB4   DF7DC8                 fistp   qword ptr [ebp-$38]
00672FB7   9B                     wait
00672FB8   8B06                   mov     eax, [esi]
00672FBA   8B80F0080000           mov     eax, [eax+$08F0]
00672FC0   8B10                   mov     edx, [eax]
00672FC2   FF524C                 call    dword ptr [edx+$4C]
00672FC5   DF6DC8                 fild    qword ptr [ebp-$38]
00672FC8   DEC1                   faddp   st(1), st(0)
00672FCA   83C4F8                 add     esp, -$08
00672FCD   DF3C24                 fistp   qword ptr [esp]
00672FD0   9B                     wait
00672FD1   8B06                   mov     eax, [esi]
00672FD3   8B803C080000           mov     eax, [eax+$083C]
00672FD9   8B10                   mov     edx, [eax]
00672FDB   FF929C000000           call    dword ptr [edx+$009C]
00672FE1   8B06                   mov     eax, [esi]
00672FE3   8B8040080000           mov     eax, [eax+$0840]
00672FE9   8B10                   mov     edx, [eax]
00672FEB   FF524C                 call    dword ptr [edx+$4C]
00672FEE   DF7DC8                 fistp   qword ptr [ebp-$38]
00672FF1   9B                     wait
00672FF2   8B06                   mov     eax, [esi]
00672FF4   8B80F4080000           mov     eax, [eax+$08F4]
00672FFA   8B10                   mov     edx, [eax]
00672FFC   FF524C                 call    dword ptr [edx+$4C]
00672FFF   DF6DC8                 fild    qword ptr [ebp-$38]
00673002   DEC1                   faddp   st(1), st(0)
00673004   83C4F8                 add     esp, -$08
00673007   DF3C24                 fistp   qword ptr [esp]
0067300A   9B                     wait
0067300B   8B06                   mov     eax, [esi]
0067300D   8B8040080000           mov     eax, [eax+$0840]
00673013   8B10                   mov     edx, [eax]
00673015   FF929C000000           call    dword ptr [edx+$009C]
0067301B   8B06                   mov     eax, [esi]
0067301D   8B8044080000           mov     eax, [eax+$0844]
00673023   8B10                   mov     edx, [eax]
00673025   FF524C                 call    dword ptr [edx+$4C]
00673028   DF7DC8                 fistp   qword ptr [ebp-$38]
0067302B   9B                     wait
0067302C   8B06                   mov     eax, [esi]
0067302E   8B80F8080000           mov     eax, [eax+$08F8]
00673034   8B10                   mov     edx, [eax]
00673036   FF524C                 call    dword ptr [edx+$4C]
00673039   DF6DC8                 fild    qword ptr [ebp-$38]
0067303C   DEC1                   faddp   st(1), st(0)
0067303E   83C4F8                 add     esp, -$08
00673041   DF3C24                 fistp   qword ptr [esp]
00673044   9B                     wait
00673045   8B06                   mov     eax, [esi]
00673047   8B8044080000           mov     eax, [eax+$0844]
0067304D   8B10                   mov     edx, [eax]
0067304F   FF929C000000           call    dword ptr [edx+$009C]
00673055   8B06                   mov     eax, [esi]
00673057   8B8048080000           mov     eax, [eax+$0848]
0067305D   8B10                   mov     edx, [eax]
0067305F   FF524C                 call    dword ptr [edx+$4C]
00673062   DF7DC8                 fistp   qword ptr [ebp-$38]
00673065   9B                     wait
00673066   8B06                   mov     eax, [esi]
00673068   8B80FC080000           mov     eax, [eax+$08FC]
0067306E   8B10                   mov     edx, [eax]
00673070   FF524C                 call    dword ptr [edx+$4C]
00673073   DF6DC8                 fild    qword ptr [ebp-$38]
00673076   DEC1                   faddp   st(1), st(0)
00673078   83C4F8                 add     esp, -$08
0067307B   DF3C24                 fistp   qword ptr [esp]
0067307E   9B                     wait
0067307F   8B06                   mov     eax, [esi]
00673081   8B8048080000           mov     eax, [eax+$0848]
00673087   8B10                   mov     edx, [eax]
00673089   FF929C000000           call    dword ptr [edx+$009C]
0067308F   8B06                   mov     eax, [esi]
00673091   8B804C080000           mov     eax, [eax+$084C]
00673097   8B10                   mov     edx, [eax]
00673099   FF524C                 call    dword ptr [edx+$4C]
0067309C   DF7DC8                 fistp   qword ptr [ebp-$38]
0067309F   9B                     wait
006730A0   8B06                   mov     eax, [esi]
006730A2   8B8000090000           mov     eax, [eax+$0900]
006730A8   8B10                   mov     edx, [eax]
006730AA   FF524C                 call    dword ptr [edx+$4C]
006730AD   DF6DC8                 fild    qword ptr [ebp-$38]
006730B0   DEC1                   faddp   st(1), st(0)
006730B2   83C4F8                 add     esp, -$08
006730B5   DF3C24                 fistp   qword ptr [esp]
006730B8   9B                     wait
006730B9   8B06                   mov     eax, [esi]
006730BB   8B804C080000           mov     eax, [eax+$084C]
006730C1   8B10                   mov     edx, [eax]
006730C3   FF929C000000           call    dword ptr [edx+$009C]
006730C9   8B06                   mov     eax, [esi]
006730CB   8B8050080000           mov     eax, [eax+$0850]
006730D1   8B10                   mov     edx, [eax]
006730D3   FF524C                 call    dword ptr [edx+$4C]
006730D6   DF7DC8                 fistp   qword ptr [ebp-$38]
006730D9   9B                     wait
006730DA   8B06                   mov     eax, [esi]
006730DC   8B8004090000           mov     eax, [eax+$0904]
006730E2   8B10                   mov     edx, [eax]
006730E4   FF524C                 call    dword ptr [edx+$4C]
006730E7   DF6DC8                 fild    qword ptr [ebp-$38]
006730EA   DEC1                   faddp   st(1), st(0)
006730EC   83C4F8                 add     esp, -$08
006730EF   DF3C24                 fistp   qword ptr [esp]
006730F2   9B                     wait
006730F3   8B06                   mov     eax, [esi]
006730F5   8B8050080000           mov     eax, [eax+$0850]
006730FB   8B10                   mov     edx, [eax]
006730FD   FF929C000000           call    dword ptr [edx+$009C]
00673103   8B06                   mov     eax, [esi]
00673105   8B8054080000           mov     eax, [eax+$0854]
0067310B   8B10                   mov     edx, [eax]
0067310D   FF524C                 call    dword ptr [edx+$4C]
00673110   DF7DC8                 fistp   qword ptr [ebp-$38]
00673113   9B                     wait
00673114   8B06                   mov     eax, [esi]
00673116   8B8008090000           mov     eax, [eax+$0908]
0067311C   8B10                   mov     edx, [eax]
0067311E   FF524C                 call    dword ptr [edx+$4C]
00673121   DF6DC8                 fild    qword ptr [ebp-$38]
00673124   DEC1                   faddp   st(1), st(0)
00673126   83C4F8                 add     esp, -$08
00673129   DF3C24                 fistp   qword ptr [esp]
0067312C   9B                     wait
0067312D   8B06                   mov     eax, [esi]
0067312F   8B8054080000           mov     eax, [eax+$0854]
00673135   8B10                   mov     edx, [eax]
00673137   FF929C000000           call    dword ptr [edx+$009C]
0067313D   8B06                   mov     eax, [esi]
0067313F   8B8058080000           mov     eax, [eax+$0858]
00673145   8B10                   mov     edx, [eax]
00673147   FF524C                 call    dword ptr [edx+$4C]
0067314A   DF7DC8                 fistp   qword ptr [ebp-$38]
0067314D   9B                     wait
0067314E   8B06                   mov     eax, [esi]
00673150   8B800C090000           mov     eax, [eax+$090C]
00673156   8B10                   mov     edx, [eax]
00673158   FF524C                 call    dword ptr [edx+$4C]
0067315B   DF6DC8                 fild    qword ptr [ebp-$38]
0067315E   DEC1                   faddp   st(1), st(0)
00673160   83C4F8                 add     esp, -$08
00673163   DF3C24                 fistp   qword ptr [esp]
00673166   9B                     wait
00673167   8B06                   mov     eax, [esi]
00673169   8B8058080000           mov     eax, [eax+$0858]
0067316F   8B10                   mov     edx, [eax]
00673171   FF929C000000           call    dword ptr [edx+$009C]
00673177   8B06                   mov     eax, [esi]
00673179   8B805C080000           mov     eax, [eax+$085C]
0067317F   8B10                   mov     edx, [eax]
00673181   FF524C                 call    dword ptr [edx+$4C]
00673184   DF7DC8                 fistp   qword ptr [ebp-$38]
00673187   9B                     wait
00673188   8B06                   mov     eax, [esi]
0067318A   8B8010090000           mov     eax, [eax+$0910]
00673190   8B10                   mov     edx, [eax]
00673192   FF524C                 call    dword ptr [edx+$4C]
00673195   DF6DC8                 fild    qword ptr [ebp-$38]
00673198   DEC1                   faddp   st(1), st(0)
0067319A   83C4F8                 add     esp, -$08
0067319D   DF3C24                 fistp   qword ptr [esp]
006731A0   9B                     wait
006731A1   8B06                   mov     eax, [esi]
006731A3   8B805C080000           mov     eax, [eax+$085C]
006731A9   8B10                   mov     edx, [eax]
006731AB   FF929C000000           call    dword ptr [edx+$009C]
006731B1   8B06                   mov     eax, [esi]
006731B3   8B8060080000           mov     eax, [eax+$0860]
006731B9   8B10                   mov     edx, [eax]
006731BB   FF524C                 call    dword ptr [edx+$4C]
006731BE   DF7DC8                 fistp   qword ptr [ebp-$38]
006731C1   9B                     wait
006731C2   8B06                   mov     eax, [esi]
006731C4   8B8014090000           mov     eax, [eax+$0914]
006731CA   8B10                   mov     edx, [eax]
006731CC   FF524C                 call    dword ptr [edx+$4C]
006731CF   DF6DC8                 fild    qword ptr [ebp-$38]
006731D2   DEC1                   faddp   st(1), st(0)
006731D4   83C4F8                 add     esp, -$08
006731D7   DF3C24                 fistp   qword ptr [esp]
006731DA   9B                     wait
006731DB   8B06                   mov     eax, [esi]
006731DD   8B8060080000           mov     eax, [eax+$0860]
006731E3   8B10                   mov     edx, [eax]
006731E5   FF929C000000           call    dword ptr [edx+$009C]
006731EB   8B06                   mov     eax, [esi]
006731ED   8B8064080000           mov     eax, [eax+$0864]
006731F3   8B10                   mov     edx, [eax]
006731F5   FF524C                 call    dword ptr [edx+$4C]
006731F8   DF7DC8                 fistp   qword ptr [ebp-$38]
006731FB   9B                     wait
006731FC   8B06                   mov     eax, [esi]
006731FE   8B8018090000           mov     eax, [eax+$0918]
00673204   8B10                   mov     edx, [eax]
00673206   FF524C                 call    dword ptr [edx+$4C]
00673209   DF6DC8                 fild    qword ptr [ebp-$38]
0067320C   DEC1                   faddp   st(1), st(0)
0067320E   83C4F8                 add     esp, -$08
00673211   DF3C24                 fistp   qword ptr [esp]
00673214   9B                     wait
00673215   8B06                   mov     eax, [esi]
00673217   8B8064080000           mov     eax, [eax+$0864]
0067321D   8B10                   mov     edx, [eax]
0067321F   FF929C000000           call    dword ptr [edx+$009C]
00673225   8B06                   mov     eax, [esi]
00673227   8B8068080000           mov     eax, [eax+$0868]
0067322D   8B10                   mov     edx, [eax]
0067322F   FF524C                 call    dword ptr [edx+$4C]
00673232   DF7DC8                 fistp   qword ptr [ebp-$38]
00673235   9B                     wait
00673236   8B06                   mov     eax, [esi]
00673238   8B801C090000           mov     eax, [eax+$091C]
0067323E   8B10                   mov     edx, [eax]
00673240   FF524C                 call    dword ptr [edx+$4C]
00673243   DF6DC8                 fild    qword ptr [ebp-$38]
00673246   DEC1                   faddp   st(1), st(0)
00673248   83C4F8                 add     esp, -$08
0067324B   DF3C24                 fistp   qword ptr [esp]
0067324E   9B                     wait
0067324F   8B06                   mov     eax, [esi]
00673251   8B8068080000           mov     eax, [eax+$0868]
00673257   8B10                   mov     edx, [eax]
00673259   FF929C000000           call    dword ptr [edx+$009C]
0067325F   8B06                   mov     eax, [esi]
00673261   8B806C080000           mov     eax, [eax+$086C]
00673267   8B10                   mov     edx, [eax]
00673269   FF524C                 call    dword ptr [edx+$4C]
0067326C   DF7DC8                 fistp   qword ptr [ebp-$38]
0067326F   9B                     wait
00673270   8B06                   mov     eax, [esi]
00673272   8B8020090000           mov     eax, [eax+$0920]
00673278   8B10                   mov     edx, [eax]
0067327A   FF524C                 call    dword ptr [edx+$4C]
0067327D   DF6DC8                 fild    qword ptr [ebp-$38]
00673280   DEC1                   faddp   st(1), st(0)
00673282   83C4F8                 add     esp, -$08
00673285   DF3C24                 fistp   qword ptr [esp]
00673288   9B                     wait
00673289   8B06                   mov     eax, [esi]
0067328B   8B806C080000           mov     eax, [eax+$086C]
00673291   8B10                   mov     edx, [eax]
00673293   FF929C000000           call    dword ptr [edx+$009C]
00673299   8B06                   mov     eax, [esi]
0067329B   8B8070080000           mov     eax, [eax+$0870]
006732A1   8B10                   mov     edx, [eax]
006732A3   FF524C                 call    dword ptr [edx+$4C]
006732A6   DF7DC8                 fistp   qword ptr [ebp-$38]
006732A9   9B                     wait
006732AA   8B06                   mov     eax, [esi]
006732AC   8B8024090000           mov     eax, [eax+$0924]
006732B2   8B10                   mov     edx, [eax]
006732B4   FF524C                 call    dword ptr [edx+$4C]
006732B7   DF6DC8                 fild    qword ptr [ebp-$38]
006732BA   DEC1                   faddp   st(1), st(0)
006732BC   83C4F8                 add     esp, -$08
006732BF   DF3C24                 fistp   qword ptr [esp]
006732C2   9B                     wait
006732C3   8B06                   mov     eax, [esi]
006732C5   8B8070080000           mov     eax, [eax+$0870]
006732CB   8B10                   mov     edx, [eax]
006732CD   FF929C000000           call    dword ptr [edx+$009C]
006732D3   8B06                   mov     eax, [esi]
006732D5   8B8074080000           mov     eax, [eax+$0874]
006732DB   8B10                   mov     edx, [eax]
006732DD   FF524C                 call    dword ptr [edx+$4C]
006732E0   DF7DC8                 fistp   qword ptr [ebp-$38]
006732E3   9B                     wait
006732E4   8B06                   mov     eax, [esi]
006732E6   8B8028090000           mov     eax, [eax+$0928]
006732EC   8B10                   mov     edx, [eax]
006732EE   FF524C                 call    dword ptr [edx+$4C]
006732F1   DF6DC8                 fild    qword ptr [ebp-$38]
006732F4   DEC1                   faddp   st(1), st(0)
006732F6   83C4F8                 add     esp, -$08
006732F9   DF3C24                 fistp   qword ptr [esp]
006732FC   9B                     wait
006732FD   8B06                   mov     eax, [esi]
006732FF   8B8074080000           mov     eax, [eax+$0874]
00673305   8B10                   mov     edx, [eax]
00673307   FF929C000000           call    dword ptr [edx+$009C]
0067330D   8B06                   mov     eax, [esi]
0067330F   8B8078080000           mov     eax, [eax+$0878]
00673315   8B10                   mov     edx, [eax]
00673317   FF524C                 call    dword ptr [edx+$4C]
0067331A   DF7DC8                 fistp   qword ptr [ebp-$38]
0067331D   9B                     wait
0067331E   8B06                   mov     eax, [esi]
00673320   8B802C090000           mov     eax, [eax+$092C]
00673326   8B10                   mov     edx, [eax]
00673328   FF524C                 call    dword ptr [edx+$4C]
0067332B   DF6DC8                 fild    qword ptr [ebp-$38]
0067332E   DEC1                   faddp   st(1), st(0)
00673330   83C4F8                 add     esp, -$08
00673333   DF3C24                 fistp   qword ptr [esp]
00673336   9B                     wait
00673337   8B06                   mov     eax, [esi]
00673339   8B8078080000           mov     eax, [eax+$0878]
0067333F   8B10                   mov     edx, [eax]
00673341   FF929C000000           call    dword ptr [edx+$009C]
00673347   8B06                   mov     eax, [esi]
00673349   8B807C080000           mov     eax, [eax+$087C]
0067334F   8B10                   mov     edx, [eax]
00673351   FF524C                 call    dword ptr [edx+$4C]
00673354   DF7DC8                 fistp   qword ptr [ebp-$38]
00673357   9B                     wait
00673358   8B06                   mov     eax, [esi]
0067335A   8B8030090000           mov     eax, [eax+$0930]
00673360   8B10                   mov     edx, [eax]
00673362   FF524C                 call    dword ptr [edx+$4C]
00673365   DF6DC8                 fild    qword ptr [ebp-$38]
00673368   DEC1                   faddp   st(1), st(0)
0067336A   83C4F8                 add     esp, -$08
0067336D   DF3C24                 fistp   qword ptr [esp]
00673370   9B                     wait
00673371   8B06                   mov     eax, [esi]
00673373   8B807C080000           mov     eax, [eax+$087C]
00673379   8B10                   mov     edx, [eax]
0067337B   FF929C000000           call    dword ptr [edx+$009C]
00673381   8B06                   mov     eax, [esi]
00673383   8B8084080000           mov     eax, [eax+$0884]
00673389   8B10                   mov     edx, [eax]
0067338B   FF524C                 call    dword ptr [edx+$4C]
0067338E   DF7DC8                 fistp   qword ptr [ebp-$38]
00673391   9B                     wait
00673392   8B06                   mov     eax, [esi]
00673394   8B8038090000           mov     eax, [eax+$0938]
0067339A   8B10                   mov     edx, [eax]
0067339C   FF524C                 call    dword ptr [edx+$4C]
0067339F   DF6DC8                 fild    qword ptr [ebp-$38]
006733A2   DEC1                   faddp   st(1), st(0)
006733A4   83C4F8                 add     esp, -$08
006733A7   DF3C24                 fistp   qword ptr [esp]
006733AA   9B                     wait
006733AB   8B06                   mov     eax, [esi]
006733AD   8B8084080000           mov     eax, [eax+$0884]
006733B3   8B10                   mov     edx, [eax]
006733B5   FF929C000000           call    dword ptr [edx+$009C]
006733BB   8B06                   mov     eax, [esi]
006733BD   8B8088080000           mov     eax, [eax+$0888]
006733C3   8B10                   mov     edx, [eax]
006733C5   FF524C                 call    dword ptr [edx+$4C]
006733C8   DF7DC8                 fistp   qword ptr [ebp-$38]
006733CB   9B                     wait
006733CC   8B06                   mov     eax, [esi]
006733CE   8B803C090000           mov     eax, [eax+$093C]
006733D4   8B10                   mov     edx, [eax]
006733D6   FF524C                 call    dword ptr [edx+$4C]
006733D9   DF6DC8                 fild    qword ptr [ebp-$38]
006733DC   DEC1                   faddp   st(1), st(0)
006733DE   83C4F8                 add     esp, -$08
006733E1   DF3C24                 fistp   qword ptr [esp]
006733E4   9B                     wait
006733E5   8B06                   mov     eax, [esi]
006733E7   8B8088080000           mov     eax, [eax+$0888]
006733ED   8B10                   mov     edx, [eax]
006733EF   FF929C000000           call    dword ptr [edx+$009C]
006733F5   8B06                   mov     eax, [esi]
006733F7   8B808C080000           mov     eax, [eax+$088C]
006733FD   8B10                   mov     edx, [eax]
006733FF   FF524C                 call    dword ptr [edx+$4C]
00673402   DF7DC8                 fistp   qword ptr [ebp-$38]
00673405   9B                     wait
00673406   8B06                   mov     eax, [esi]
00673408   8B8040090000           mov     eax, [eax+$0940]
0067340E   8B10                   mov     edx, [eax]
00673410   FF524C                 call    dword ptr [edx+$4C]
00673413   DF6DC8                 fild    qword ptr [ebp-$38]
00673416   DEC1                   faddp   st(1), st(0)
00673418   83C4F8                 add     esp, -$08
0067341B   DF3C24                 fistp   qword ptr [esp]
0067341E   9B                     wait
0067341F   8B06                   mov     eax, [esi]
00673421   8B808C080000           mov     eax, [eax+$088C]
00673427   8B10                   mov     edx, [eax]
00673429   FF929C000000           call    dword ptr [edx+$009C]
0067342F   8B06                   mov     eax, [esi]
00673431   8B8090080000           mov     eax, [eax+$0890]
00673437   8B10                   mov     edx, [eax]
00673439   FF524C                 call    dword ptr [edx+$4C]
0067343C   DF7DC8                 fistp   qword ptr [ebp-$38]
0067343F   9B                     wait
00673440   8B06                   mov     eax, [esi]
00673442   8B8044090000           mov     eax, [eax+$0944]
00673448   8B10                   mov     edx, [eax]
0067344A   FF524C                 call    dword ptr [edx+$4C]
0067344D   DF6DC8                 fild    qword ptr [ebp-$38]
00673450   DEC1                   faddp   st(1), st(0)
00673452   83C4F8                 add     esp, -$08
00673455   DF3C24                 fistp   qword ptr [esp]
00673458   9B                     wait
00673459   8B06                   mov     eax, [esi]
0067345B   8B8090080000           mov     eax, [eax+$0890]
00673461   8B10                   mov     edx, [eax]
00673463   FF929C000000           call    dword ptr [edx+$009C]
00673469   8B06                   mov     eax, [esi]
0067346B   8B80D0070000           mov     eax, [eax+$07D0]
00673471   8B10                   mov     edx, [eax]
00673473   FF924C020000           call    dword ptr [edx+$024C]
00673479   8B06                   mov     eax, [esi]
0067347B   8B808C060000           mov     eax, [eax+$068C]

|
00673481   E86EAEF2FF             call    0059E2F4
00673486   8B06                   mov     eax, [esi]
00673488   8B808C060000           mov     eax, [eax+$068C]
0067348E   80B8A100000000         cmp     byte ptr [eax+$00A1], $00
00673495   0F84F6EFFFFF           jz      00672491
0067349B   8B06                   mov     eax, [esi]
0067349D   8B808C060000           mov     eax, [eax+$068C]
006734A3   33D2                   xor     edx, edx
006734A5   8B08                   mov     ecx, [eax]
006734A7   FF9190010000           call    dword ptr [ecx+$0190]

* Reference to Form50
|
006734AD   A12C366B00             mov     eax, dword ptr [$006B362C]

* Reference to: Forms.TCustomForm.Close()
|
006734B2   E841F0E0FF             call    004824F8
006734B7   33C0                   xor     eax, eax
006734B9   5A                     pop     edx
006734BA   59                     pop     ecx
006734BB   59                     pop     ecx
006734BC   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^‹å]Ã'
|
006734BF   68E1346700             push    $006734E1
006734C4   8D45D4                 lea     eax, [ebp-$2C]
006734C7   BA08000000             mov     edx, $00000008

|
006734CC   E8D315D9FF             call    00404AA4
006734D1   8D45F4                 lea     eax, [ebp-$0C]

|
006734D4   E8A715D9FF             call    00404A80
006734D9   C3                     ret

006734DA   E9850FD9FF             jmp     00404464
006734DF   EBE3                   jmp     006734C4

****** END
|
006734E1   5F                     pop     edi
006734E2   5E                     pop     esi
006734E3   8BE5                   mov     esp, ebp
006734E5   5D                     pop     ebp
006734E6   C3                     ret

*)
end;

procedure TForm50.sBitBtn5Click(Sender : TObject);
begin
(*

* Reference to Form50
|
006734FC   A12C366B00             mov     eax, dword ptr [$006B362C]

* Reference to: Forms.TCustomForm.Close()
|
00673501   E8F2EFE0FF             call    004824F8
00673506   C3                     ret

*)
end;

procedure TForm50.FormShow(Sender : TObject);
begin
(*
00673508   53                     push    ebx
00673509   8BD8                   mov     ebx, eax
0067350B   6A13                   push    $13

* Reference to field TForm50.OFFS_004C
|
0067350D   8B434C                 mov     eax, [ebx+$4C]
00673510   50                     push    eax

* Reference to field TForm50.OFFS_0048
|
00673511   8B4348                 mov     eax, [ebx+$48]
00673514   50                     push    eax

* Reference to field TForm50.OFFS_0044
|
00673515   8B4344                 mov     eax, [ebx+$44]
00673518   50                     push    eax

* Reference to field TForm50.OFFS_0040
|
00673519   8B4340                 mov     eax, [ebx+$40]
0067351C   50                     push    eax
0067351D   6AFF                   push    $FF
0067351F   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
00673521   E86A76DFFF             call    0046AB90
00673526   50                     push    eax

* Reference to: user32.SetWindowPos()
|
00673527   E89449D9FF             call    00407EC0
0067352C   5B                     pop     ebx
0067352D   C3                     ret

*)
end;

procedure TForm50._PROC_00673531(Sender : TObject);
begin
(*
00673531   8BEC                   mov     ebp, esp
00673533   33C0                   xor     eax, eax
00673535   55                     push    ebp
00673536   687F356700             push    $0067357F
0067353B   64FF30                 push    dword ptr fs:[eax]
0067353E   648920                 mov     fs:[eax], esp
00673541   FF0540366B00           inc     dword ptr [$006B3640]
00673547   7528                   jnz     00673571
00673549   B83C366B00             mov     eax, $006B363C

|
0067354E   E82D15D9FF             call    00404A80
00673553   B838366B00             mov     eax, $006B3638

|
00673558   E82315D9FF             call    00404A80
0067355D   B834366B00             mov     eax, $006B3634

|
00673562   E81915D9FF             call    00404A80
00673567   B830366B00             mov     eax, $006B3630

|
0067356C   E80F15D9FF             call    00404A80
00673571   33C0                   xor     eax, eax
00673573   5A                     pop     edx
00673574   59                     pop     ecx
00673575   59                     pop     ecx
00673576   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ãƒ-@6k'
|
00673579   6886356700             push    $00673586
0067357E   C3                     ret

0067357F   E9E00ED9FF             jmp     00404464
00673584   EBF8                   jmp     0067357E

****** END
|
00673586   5D                     pop     ebp
00673587   C3                     ret

*)
end;

procedure TForm50._PROC_00673588(Sender : TObject);
begin
(*
00673588   832D40366B0001         sub     dword ptr [$006B3640], +$01
0067358F   C3                     ret

*)
end;

procedure TForm50._PROC_00673590(Sender : TObject);
begin
(*
00673590   DC3567000000           fdiv    qword ptr [$00000067]
00673596   0000                   add     [eax], al

*)
end;

end.