unit Unit6;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DB, DBTables, sSkinManager, DBCtrls,
  sLabel, sDBNavigator, Grids, DBGrids, acDBGrid, ComCtrls, sPageControl,
  Buttons, sBitBtn, ExtCtrls, sPanel, ABSMain ;
type
  TForm6=class(TForm)
    sPanel1: TsPanel;
    sBitBtn10: TsBitBtn;
    sBitBtn9: TsBitBtn;
    sPanel3: TsPanel;
    sPageControl2: TsPageControl;
    sTabSheet8: TsTabSheet;
    sDBGrid1: TsDBGrid;
    sDBNavigator1: TsDBNavigator;
    sTabSheet9: TsTabSheet;
    sLabelFX1: TsLabelFX;
    sDBGrid2: TsDBGrid;
    sDBNavigator2: TsDBNavigator;
    DBLookupComboBox1: TDBLookupComboBox;
    sTabSheet10: TsTabSheet;
    sLabelFX2: TsLabelFX;
    sLabelFX5: TsLabelFX;
    sDBNavigator3: TsDBNavigator;
    sDBGrid3: TsDBGrid;
    DBLookupComboBox2: TDBLookupComboBox;
    DBLookupComboBox3: TDBLookupComboBox;
    sTabSheet11: TsTabSheet;
    sLabelFX6: TsLabelFX;
    sLabelFX3: TsLabelFX;
    sLabelFX4: TsLabelFX;
    DBLookupComboBox4: TDBLookupComboBox;
    DBLookupComboBox5: TDBLookupComboBox;
    sDBGrid4: TsDBGrid;
    sDBNavigator4: TsDBNavigator;
    DBLookupComboBox6: TDBLookupComboBox;
    sSkinManager1: TsSkinManager;
    Datasilk: TDataSource;
    Datacho: TDataSource;
    Dataslk: TDataSource;
    Datarotb: TDataSource;
    ABSSilk: TABSTable;
    ABSCho: TABSTable;
    ABSSlk: TABSTable;
    ABSrotb: TABSTable;
    ABSDatabase1: TABSDatabase;
    procedure sBitBtn10Click(Sender : TObject);
    procedure sBitBtn9Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_0061B2A8(Sender : TObject);
    procedure _PROC_0061B2D8(Sender : TObject);
    procedure _PROC_0061B2E0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form6: TForm6;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm6.sBitBtn10Click(Sender : TObject);
begin
  //0061B1A4
  Close;
(*

* Reference to Form6
|
0061B1A4   A144336B00             mov     eax, dword ptr [$006B3344]

* Reference to field Form6.OFFS_0370
|
0061B1A9   8B8070030000           mov     eax, [eax+$0370]
0061B1AF   8B10                   mov     edx, [eax]
0061B1B1   FF920C020000           call    dword ptr [edx+$020C]

* Reference to Form6
|
0061B1B7   A144336B00             mov     eax, dword ptr [$006B3344]

* Reference to field Form6.OFFS_037C
|
0061B1BC   8B807C030000           mov     eax, [eax+$037C]
0061B1C2   8B10                   mov     edx, [eax]
0061B1C4   FF920C020000           call    dword ptr [edx+$020C]

* Reference to Form6
|
0061B1CA   A144336B00             mov     eax, dword ptr [$006B3344]

* Reference to field Form6.OFFS_0384
|
0061B1CF   8B8084030000           mov     eax, [eax+$0384]
0061B1D5   8B10                   mov     edx, [eax]
0061B1D7   FF920C020000           call    dword ptr [edx+$020C]

* Reference to Form6
|
0061B1DD   A144336B00             mov     eax, dword ptr [$006B3344]

* Reference to field Form6.OFFS_038C
|
0061B1E2   8B808C030000           mov     eax, [eax+$038C]
0061B1E8   8B10                   mov     edx, [eax]
0061B1EA   FF920C020000           call    dword ptr [edx+$020C]

* Reference to Form6
|
0061B1F0   A144336B00             mov     eax, dword ptr [$006B3344]

* Reference to: Forms.TCustomForm.Close()
|
0061B1F5   E8FE72E6FF             call    004824F8
0061B1FA   C3                     ret

*)
end;

procedure TForm6.sBitBtn9Click(Sender : TObject);
begin
  //0061B1FC
  Close;
(*
0061B1FC   53                     push    ebx

* Possible reference to Form6
|
0061B1FD   BB44336B00             mov     ebx, $006B3344
0061B202   8B03                   mov     eax, [ebx]

* Reference to control TForm6.silk : TTable
|
0061B204   8B8070030000           mov     eax, [eax+$0370]

|
0061B20A   E8D931F8FF             call    0059E3E8
0061B20F   8B03                   mov     eax, [ebx]

* Reference to field TTable.OFFS_0370
|
0061B211   8B8070030000           mov     eax, [eax+$0370]
0061B217   8B10                   mov     edx, [eax]
0061B219   FF924C020000           call    dword ptr [edx+$024C]
0061B21F   8B03                   mov     eax, [ebx]
0061B221   8B807C030000           mov     eax, [eax+$037C]

|
0061B227   E8BC31F8FF             call    0059E3E8
0061B22C   8B03                   mov     eax, [ebx]
0061B22E   8B807C030000           mov     eax, [eax+$037C]
0061B234   8B10                   mov     edx, [eax]
0061B236   FF924C020000           call    dword ptr [edx+$024C]
0061B23C   8B03                   mov     eax, [ebx]
0061B23E   8B8084030000           mov     eax, [eax+$0384]

|
0061B244   E89F31F8FF             call    0059E3E8
0061B249   8B03                   mov     eax, [ebx]
0061B24B   8B8084030000           mov     eax, [eax+$0384]
0061B251   8B10                   mov     edx, [eax]
0061B253   FF924C020000           call    dword ptr [edx+$024C]
0061B259   8B03                   mov     eax, [ebx]
0061B25B   8B808C030000           mov     eax, [eax+$038C]

|
0061B261   E88231F8FF             call    0059E3E8
0061B266   8B03                   mov     eax, [ebx]
0061B268   8B808C030000           mov     eax, [eax+$038C]
0061B26E   8B10                   mov     edx, [eax]
0061B270   FF924C020000           call    dword ptr [edx+$024C]
0061B276   8B03                   mov     eax, [ebx]

* Reference to: Forms.TCustomForm.Close()
|
0061B278   E87B72E6FF             call    004824F8
0061B27D   5B                     pop     ebx
0061B27E   C3                     ret

*)
end;

procedure TForm6.FormShow(Sender : TObject);
begin
(*
0061B280   53                     push    ebx
0061B281   8BD8                   mov     ebx, eax
0061B283   6A13                   push    $13

* Reference to field TForm6.OFFS_004C
|
0061B285   8B434C                 mov     eax, [ebx+$4C]
0061B288   50                     push    eax

* Reference to field TForm6.OFFS_0048
|
0061B289   8B4348                 mov     eax, [ebx+$48]
0061B28C   50                     push    eax

* Reference to field TForm6.OFFS_0044
|
0061B28D   8B4344                 mov     eax, [ebx+$44]
0061B290   50                     push    eax

* Reference to field TForm6.OFFS_0040
|
0061B291   8B4340                 mov     eax, [ebx+$40]
0061B294   50                     push    eax
0061B295   6AFF                   push    $FF
0061B297   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
0061B299   E8F2F8E4FF             call    0046AB90
0061B29E   50                     push    eax

* Reference to: user32.SetWindowPos()
|
0061B29F   E81CCCDEFF             call    00407EC0
0061B2A4   5B                     pop     ebx
0061B2A5   C3                     ret

*)
end;

procedure TForm6._PROC_0061B2A8(Sender : TObject);
begin
(*
0061B2A8   55                     push    ebp
0061B2A9   8BEC                   mov     ebp, esp
0061B2AB   33C0                   xor     eax, eax
0061B2AD   55                     push    ebp

* Possible String Reference to: 'é’‘Þÿëø]Ã‹Àƒ-H3k'
|
0061B2AE   68CDB26100             push    $0061B2CD
0061B2B3   64FF30                 push    dword ptr fs:[eax]
0061B2B6   648920                 mov     fs:[eax], esp
0061B2B9   FF0548336B00           inc     dword ptr [$006B3348]
0061B2BF   33C0                   xor     eax, eax
0061B2C1   5A                     pop     edx
0061B2C2   59                     pop     ecx
0061B2C3   59                     pop     ecx
0061B2C4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-H3k'
|
0061B2C7   68D4B26100             push    $0061B2D4
0061B2CC   C3                     ret

0061B2CD   E99291DEFF             jmp     00404464
0061B2D2   EBF8                   jmp     0061B2CC

****** END
|
0061B2D4   5D                     pop     ebp
0061B2D5   C3                     ret

*)
end;

procedure TForm6._PROC_0061B2D8(Sender : TObject);
begin
(*
0061B2D8   832D48336B0001         sub     dword ptr [$006B3348], +$01
0061B2DF   C3                     ret

*)
end;

procedure TForm6._PROC_0061B2E0(Sender : TObject);
begin
(*
0061B2E0   2CB3                   sub     al, $B3
0061B2E2   61                     popa
0061B2E3   0000                   add     [eax], al

*)
end;

end.