unit Unit37;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ImgList, acAlphaImageList,
  acTitleBar, Buttons, sBitBtn, Grids, DBGrids, acDBGrid, sLabel, acPNG,
  ExtCtrls, acImage, sSpeedButton, sPanel ;
type
  TForm37=class(TForm)
    sPanel1: TsPanel;
    sPanel4: TsPanel;
    sBitBtn32: TsBitBtn;
    sSpeedButton7: TsSpeedButton;
    sImage1: TsImage;
    sLabelFX2: TsLabelFX;
    sLabelFX1: TsLabelFX;
    sLabelFX3: TsLabelFX;
    sDBGrid1: TsDBGrid;
    sLabelFX4: TsLabelFX;
    sSpeedButton8: TsSpeedButton;
    sTitleBar1: TsTitleBar;
    sAlphaImageList22: TsAlphaImageList;
    procedure sBitBtn32Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_0066FA08(Sender : TObject);
    procedure _PROC_0066FA38(Sender : TObject);
    procedure _PROC_0066FA40(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form37: TForm37;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm37.sBitBtn32Click(Sender : TObject);
begin
(*
0066F978   53                     push    ebx

* Reference to TData instance
|
0066F979   8B1DD8F06A00           mov     ebx, [$006AF0D8]
0066F97F   8B03                   mov     eax, [ebx]

* Reference to field TForm37.OFFS_0694
|
0066F981   8B8094060000           mov     eax, [eax+$0694]

|
0066F987   E850E6F2FF             call    0059DFDC
0066F98C   EB0D                   jmp     0066F99B
0066F98E   8B03                   mov     eax, [ebx]
0066F990   8B8094060000           mov     eax, [eax+$0694]

|
0066F996   E885EDF2FF             call    0059E720
0066F99B   8B03                   mov     eax, [ebx]
0066F99D   8B8094060000           mov     eax, [eax+$0694]

|
0066F9A3   E8C4E4F2FF             call    0059DE6C
0066F9A8   84C0                   test    al, al
0066F9AA   74E2                   jz      0066F98E

* Reference to TForm1 instance
|
0066F9AC   A170FA6A00             mov     eax, dword ptr [$006AFA70]
0066F9B1   8B00                   mov     eax, [eax]

* Reference to control TForm1.sSpeedButton5 : TsSpeedButton
|
0066F9B3   8B8024080000           mov     eax, [eax+$0824]
0066F9B9   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible()
|
0066F9BB   E88846DFFF             call    00464048

* Reference to TForm1 instance
|
0066F9C0   A170FA6A00             mov     eax, dword ptr [$006AFA70]
0066F9C5   8B00                   mov     eax, [eax]

* Reference to control TForm1.Timer2 : TTimer
|
0066F9C7   8B8028080000           mov     eax, [eax+$0828]
0066F9CD   33D2                   xor     edx, edx

* Reference to: Extctrls.TTimer.SetEnabled()
|
0066F9CF   E830C6DCFF             call    0043C004

* Reference to Form37
|
0066F9D4   A1FC356B00             mov     eax, dword ptr [$006B35FC]

* Reference to: Forms.TCustomForm.Close()
|
0066F9D9   E81A2BE1FF             call    004824F8
0066F9DE   5B                     pop     ebx
0066F9DF   C3                     ret

*)
end;

procedure TForm37.FormShow(Sender : TObject);
begin
(*
0066F9E0   53                     push    ebx
0066F9E1   8BD8                   mov     ebx, eax
0066F9E3   6A13                   push    $13

* Reference to field TForm37.OFFS_004C
|
0066F9E5   8B434C                 mov     eax, [ebx+$4C]
0066F9E8   50                     push    eax

* Reference to field TForm37.OFFS_0048
|
0066F9E9   8B4348                 mov     eax, [ebx+$48]
0066F9EC   50                     push    eax

* Reference to field TForm37.OFFS_0044
|
0066F9ED   8B4344                 mov     eax, [ebx+$44]
0066F9F0   50                     push    eax

* Reference to field TForm37.OFFS_0040
|
0066F9F1   8B4340                 mov     eax, [ebx+$40]
0066F9F4   50                     push    eax
0066F9F5   6AFF                   push    $FF
0066F9F7   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
0066F9F9   E892B1DFFF             call    0046AB90
0066F9FE   50                     push    eax

* Reference to: user32.SetWindowPos()
|
0066F9FF   E8BC84D9FF             call    00407EC0
0066FA04   5B                     pop     ebx
0066FA05   C3                     ret

*)
end;

procedure TForm37._PROC_0066FA08(Sender : TObject);
begin
(*
0066FA08   55                     push    ebp
0066FA09   8BEC                   mov     ebp, esp
0066FA0B   33C0                   xor     eax, eax
0066FA0D   55                     push    ebp

* Possible String Reference to: 'é2JÙÿëø]Ã‹Àƒ-'
|
0066FA0E   682DFA6600             push    $0066FA2D
0066FA13   64FF30                 push    dword ptr fs:[eax]
0066FA16   648920                 mov     fs:[eax], esp
0066FA19   FF0500366B00           inc     dword ptr [$006B3600]
0066FA1F   33C0                   xor     eax, eax
0066FA21   5A                     pop     edx
0066FA22   59                     pop     ecx
0066FA23   59                     pop     ecx
0066FA24   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-'
|
0066FA27   6834FA6600             push    $0066FA34
0066FA2C   C3                     ret

0066FA2D   E9324AD9FF             jmp     00404464
0066FA32   EBF8                   jmp     0066FA2C

****** END
|
0066FA34   5D                     pop     ebp
0066FA35   C3                     ret

*)
end;

procedure TForm37._PROC_0066FA38(Sender : TObject);
begin
(*
0066FA38   832D00366B0001         sub     dword ptr [$006B3600], +$01
0066FA3F   C3                     ret

*)
end;

procedure TForm37._PROC_0066FA40(Sender : TObject);
begin
(*
0066FA40   8CFA                   mov     dx, 
0066FA42   660000                 add     [eax], al

*)
end;

end.