unit Unit42;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, sPanel, Buttons, sBitBtn,
  sEdit, sLabel, sSpeedButton, acPNG, acImage, ComCtrls, sPageControl;
type
  TForm42=class(TForm)
    sPageControl1: TsPageControl;
    sTabSheet1: TsTabSheet;
    sTabSheet2: TsTabSheet;
    sImage1: TsImage;
    sSpeedButton1: TsSpeedButton;
    sPanel4: TsPanel;
    sLabelFX4: TsLabelFX;
    sSpeedButton8: TsSpeedButton;
    sBitBtn32: TsBitBtn;
    sLabelFX5: TsLabelFX;
    sLabelFX7: TsLabelFX;
    sLabelFX8: TsLabelFX;
    Image2: TImage;
    Image3: TImage;
    Image1: TImage;
    sLabelFX3: TsLabelFX;
    sLabelFX6: TsLabelFX;
    sLabelFX9: TsLabelFX;
    sLabelFX10: TsLabelFX;
    sLabelFX2: TsLabelFX;
    sLabelFX1: TsLabelFX;
    sImage2: TsImage;
    sSpeedButton2: TsSpeedButton;
    sLabelFX11: TsLabelFX;
    sLabelFX12: TsLabelFX;
    Image4: TImage;
    Image5: TImage;
    sLabelFX13: TsLabelFX;
    Image6: TImage;
    sLabelFX14: TsLabelFX;
    sLabelFX15: TsLabelFX;
    sLabelFX16: TsLabelFX;
    sLabelFX17: TsLabelFX;
    Label2: TLabel;
    sEdit1: TsEdit;
    sBitBtn1: TsBitBtn;
    sLabelFX18: TsLabelFX;
    procedure sBitBtn32Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure FormActivate(Sender : TObject);
    procedure sEdit1Change(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure sBitBtn1Click(Sender : TObject);
    procedure sBitBtn2Click(Sender : TObject);
    procedure _PROC_006720CE(Sender : TObject);
    procedure _PROC_0067217C(Sender : TObject);
    procedure _PROC_006721AC(Sender : TObject);
    procedure _PROC_006721B4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form42: TForm42;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm42.sBitBtn32Click(Sender : TObject);
begin
  //00671AF0
  Close;
end;

procedure TForm42.FormShow(Sender : TObject);
begin
(*
00671AFC   53                     push    ebx
00671AFD   8BD8                   mov     ebx, eax
00671AFF   6A13                   push    $13

* Reference to field TForm42.OFFS_004C
|
00671B01   8B434C                 mov     eax, [ebx+$4C]
00671B04   50                     push    eax

* Reference to field TForm42.OFFS_0048
|
00671B05   8B4348                 mov     eax, [ebx+$48]
00671B08   50                     push    eax

* Reference to field TForm42.OFFS_0044
|
00671B09   8B4344                 mov     eax, [ebx+$44]
00671B0C   50                     push    eax

* Reference to field TForm42.OFFS_0040
|
00671B0D   8B4340                 mov     eax, [ebx+$40]
00671B10   50                     push    eax
00671B11   6AFF                   push    $FF
00671B13   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
00671B15   E87690DFFF             call    0046AB90
00671B1A   50                     push    eax

* Reference to: user32.SetWindowPos()
|
00671B1B   E8A063D9FF             call    00407EC0
00671B20   5B                     pop     ebx
00671B21   C3                     ret

*)
end;

procedure TForm42.FormActivate(Sender : TObject);
begin
  //00671B24
     //Form42.sBitBtn1;
     //'D18F'+00671A1C()+'Y22X';
     Form42.Label2.Caption :='D18F'+'Y22X';
     if(FileExists('C:\Windows\System32\sgsql.dll'))then begin
        // Form42.sEdit1.Text;
         Form42.sLabelFX18.Caption :=   '‰”Œ… ﬂ«„·‹‹‹… „‰ »—‰«„Ã  ”ÌÌ— «·—Ê« » Ê«·„‰Õ';
     end;
(*
* Reference to control TForm42.sBitBtn1 : TsBitBtn
|
00671B3E   8B8384030000           mov     eax, [ebx+$0384]
00671B44   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00671B46   FF5164                 call    dword ptr [ecx+$64]

* Possible String Reference to: 'D18F'
|
00671B49   68B81C6700             push    $00671CB8
00671B4E   8D55F8                 lea     edx, [ebp-$08]
00671B51   B8C81C6700             mov     eax, $00671CC8

|
00671B56   E8C1FEFFFF             call    00671A1C
00671B5B   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: 'Y22X'
|
00671B5E   68D41C6700             push    $00671CD4
00671B63   8D45FC                 lea     eax, [ebp-$04]
00671B66   BA03000000             mov     edx, $00000003

|
00671B6B   E89032D9FF             call    00404E00
00671B70   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TForm42.Label2 : TLabel
|
00671B73   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671B79   E8DA25DFFF             call    00464158

* Possible String Reference to: 'C:\Windows\System32\sgsql.dll'
|
00671B7E   B8E41C6700             mov     eax, $00671CE4

|
00671B83   E8E083D9FF             call    00409F68
00671B88   84C0                   test    al, al
00671B8A   747C                   jz      00671C08

* Reference to field TForm42.OFFS_038C
|
00671B8C   8B938C030000           mov     edx, [ebx+$038C]

* Reference to control TForm42.sEdit1 : TsEdit
|
00671B92   8B8380030000           mov     eax, [ebx+$0380]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671B98   E8BB25DFFF             call    00464158
00671B9D   33D2                   xor     edx, edx

* Reference to control TForm42.sEdit1 : TsEdit
|
00671B9F   8B8380030000           mov     eax, [ebx+$0380]
00671BA5   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsEdit.OFFS_64
|
00671BA7   FF5164                 call    dword ptr [ecx+$64]
00671BAA   33D2                   xor     edx, edx

* Reference to control TForm42.sBitBtn1 : TsBitBtn
|
00671BAC   8B8384030000           mov     eax, [ebx+$0384]

* Reference to: Controls.TControl.SetVisible()
|
00671BB2   E89124DFFF             call    00464048
00671BB7   33D2                   xor     edx, edx

* Reference to control TForm42.Label2 : TLabel
|
00671BB9   8B837C030000           mov     eax, [ebx+$037C]
00671BBF   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel.OFFS_64
|
00671BC1   FF5164                 call    dword ptr [ecx+$64]
00671BC4   33D2                   xor     edx, edx

* Reference to control TForm42.sLabelFX17 : TsLabelFX
|
00671BC6   8B8378030000           mov     eax, [ebx+$0378]
00671BCC   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsLabelFX.OFFS_64
|
00671BCE   FF5164                 call    dword ptr [ecx+$64]
00671BD1   33D2                   xor     edx, edx

* Reference to control TForm42.sLabelFX16 : TsLabelFX
|
00671BD3   8B8374030000           mov     eax, [ebx+$0374]
00671BD9   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsLabelFX.OFFS_64
|
00671BDB   FF5164                 call    dword ptr [ecx+$64]

* Reference to Form42
|
00671BDE   A124366B00             mov     eax, dword ptr [$006B3624]

* Reference to field Form42.OFFS_0300
|
00671BE3   8B8000030000           mov     eax, [eax+$0300]

* Possible String Reference to: '‰”Œ… ﬂ«„·…'
|
00671BE9   BA0C1D6700             mov     edx, $00671D0C

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671BEE   E86525DFFF             call    00464158

* Possible String Reference to: '‰”Œ… ﬂ«„·‹‹‹… „‰ »—‰«„Ã  ”ÌÌ— «·—Ê«
|                                 » Ê«·„‰Õ'
|
00671BF3   BA201D6700             mov     edx, $00671D20

* Reference to control TForm42.sLabelFX18 : TsLabelFX
|
00671BF8   8B8388030000           mov     eax, [ebx+$0388]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671BFE   E85525DFFF             call    00464158
00671C03   E980000000             jmp     00671C88
00671C08   33D2                   xor     edx, edx

* Reference to control TForm42.sEdit1 : TsEdit
|
00671C0A   8B8380030000           mov     eax, [ebx+$0380]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671C10   E84325DFFF             call    00464158
00671C15   B201                   mov     dl, $01

* Reference to control TForm42.sEdit1 : TsEdit
|
00671C17   8B8380030000           mov     eax, [ebx+$0380]
00671C1D   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsEdit.OFFS_64
|
00671C1F   FF5164                 call    dword ptr [ecx+$64]
00671C22   B201                   mov     dl, $01

* Reference to control TForm42.sBitBtn1 : TsBitBtn
|
00671C24   8B8384030000           mov     eax, [ebx+$0384]

* Reference to: Controls.TControl.SetVisible()
|
00671C2A   E81924DFFF             call    00464048
00671C2F   B201                   mov     dl, $01

* Reference to control TForm42.Label2 : TLabel
|
00671C31   8B837C030000           mov     eax, [ebx+$037C]
00671C37   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel.OFFS_64
|
00671C39   FF5164                 call    dword ptr [ecx+$64]
00671C3C   B201                   mov     dl, $01

* Reference to control TForm42.sLabelFX17 : TsLabelFX
|
00671C3E   8B8378030000           mov     eax, [ebx+$0378]
00671C44   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsLabelFX.OFFS_64
|
00671C46   FF5164                 call    dword ptr [ecx+$64]
00671C49   B201                   mov     dl, $01

* Reference to control TForm42.sLabelFX16 : TsLabelFX
|
00671C4B   8B8374030000           mov     eax, [ebx+$0374]
00671C51   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsLabelFX.OFFS_64
|
00671C53   FF5164                 call    dword ptr [ecx+$64]

* Reference to Form42
|
00671C56   A124366B00             mov     eax, dword ptr [$006B3624]

* Reference to field Form42.OFFS_0300
|
00671C5B   8B8000030000           mov     eax, [eax+$0300]

* Possible String Reference to: '‰”Œ…  Ã—Ì»Ì…'
|
00671C61   BA581D6700             mov     edx, $00671D58

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671C66   E8ED24DFFF             call    00464158

* Possible String Reference to: '‰”Œ…  Ã—Ì»Ì… „‰ »—‰«„Ã  ”ÌÌ— «·—Ê« 
|                                » Ê«·„‰Õ'
|
00671C6B   BA701D6700             mov     edx, $00671D70

* Reference to control TForm42.sLabelFX18 : TsLabelFX
|
00671C70   8B8388030000           mov     eax, [ebx+$0388]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671C76   E8DD24DFFF             call    00464158
00671C7B   33D2                   xor     edx, edx

* Reference to control TForm42.sBitBtn1 : TsBitBtn
|
00671C7D   8B8384030000           mov     eax, [ebx+$0384]
00671C83   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00671C85   FF5164                 call    dword ptr [ecx+$64]
00671C88   33C0                   xor     eax, eax
00671C8A   5A                     pop     edx
00671C8B   59                     pop     ecx
00671C8C   59                     pop     ecx
00671C8D   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]√'
|
00671C90   68AA1C6700             push    $00671CAA
00671C95   8D45F8                 lea     eax, [ebp-$08]
00671C98   BA02000000             mov     edx, $00000002

|
00671C9D   E8022ED9FF             call    00404AA4
00671CA2   C3                     ret

00671CA3   E9BC27D9FF             jmp     00404464
00671CA8   EBEB                   jmp     00671C95

****** END
|
00671CAA   5B                     pop     ebx
00671CAB   59                     pop     ecx
00671CAC   59                     pop     ecx
00671CAD   5D                     pop     ebp
00671CAE   C3                     ret

*)
end;

procedure TForm42.sEdit1Change(Sender : TObject);
begin
(*
00671D9C   55                     push    ebp
00671D9D   8BEC                   mov     ebp, esp
00671D9F   6A00                   push    $00
00671DA1   53                     push    ebx
00671DA2   8BD8                   mov     ebx, eax
00671DA4   33C0                   xor     eax, eax
00671DA6   55                     push    ebp

* Possible String Reference to: 'È]&ŸˇÎ[Y]√ç@'
|
00671DA7   68021E6700             push    $00671E02
00671DAC   64FF30                 push    dword ptr fs:[eax]
00671DAF   648920                 mov     fs:[eax], esp
00671DB2   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TForm42.sEdit1 : TsEdit
|
00671DB5   8B8380030000           mov     eax, [ebx+$0380]

* Reference to: Controls.TControl.GetText()
|
00671DBB   E86823DFFF             call    00464128
00671DC0   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TForm42.OFFS_038C
|
00671DC3   8B938C030000           mov     edx, [ebx+$038C]

|
00671DC9   E8BE30D9FF             call    00404E8C
00671DCE   750F                   jnz     00671DDF
00671DD0   B201                   mov     dl, $01

* Reference to control TForm42.sBitBtn1 : TsBitBtn
|
00671DD2   8B8384030000           mov     eax, [ebx+$0384]
00671DD8   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00671DDA   FF5164                 call    dword ptr [ecx+$64]
00671DDD   EB0D                   jmp     00671DEC
00671DDF   33D2                   xor     edx, edx

* Reference to control TForm42.sBitBtn1 : TsBitBtn
|
00671DE1   8B8384030000           mov     eax, [ebx+$0384]
00671DE7   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00671DE9   FF5164                 call    dword ptr [ecx+$64]
00671DEC   33C0                   xor     eax, eax
00671DEE   5A                     pop     edx
00671DEF   59                     pop     ecx
00671DF0   59                     pop     ecx
00671DF1   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ç@'
|
00671DF4   68091E6700             push    $00671E09
00671DF9   8D45FC                 lea     eax, [ebp-$04]

|
00671DFC   E87F2CD9FF             call    00404A80
00671E01   C3                     ret

00671E02   E95D26D9FF             jmp     00404464
00671E07   EBF0                   jmp     00671DF9

****** END
|
00671E09   5B                     pop     ebx
00671E0A   59                     pop     ecx
00671E0B   5D                     pop     ebp
00671E0C   C3                     ret

*)
end;

procedure TForm42.FormCreate(Sender : TObject);
begin
(*
00671E10   55                     push    ebp
00671E11   8BEC                   mov     ebp, esp
00671E13   81C41CFEFFFF           add     esp, $FFFFFE1C
00671E19   53                     push    ebx
00671E1A   56                     push    esi
00671E1B   33C9                   xor     ecx, ecx
00671E1D   898D1CFEFFFF           mov     [ebp+$FFFFFE1C], ecx
00671E23   898D20FEFFFF           mov     [ebp+$FFFFFE20], ecx
00671E29   898D24FEFFFF           mov     [ebp+$FFFFFE24], ecx
00671E2F   894DFC                 mov     [ebp-$04], ecx
00671E32   894DF8                 mov     [ebp-$08], ecx
00671E35   8BF0                   mov     esi, eax
00671E37   33C0                   xor     eax, eax
00671E39   55                     push    ebp

* Possible String Reference to: 'È€$ŸˇÎ€^[ãÂ]√'
|
00671E3A   68841F6700             push    $00671F84
00671E3F   64FF30                 push    dword ptr fs:[eax]
00671E42   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'sys.dat'
|
00671E45   BA9C1F6700             mov     edx, $00671F9C
00671E4A   8D8528FEFFFF           lea     eax, [ebp+$FFFFFE28]

|
00671E50   E8BB11D9FF             call    00403010
00671E55   8D8528FEFFFF           lea     eax, [ebp+$FFFFFE28]

|
00671E5B   E84C0FD9FF             call    00402DAC

|
00671E60   E8170BD9FF             call    0040297C
00671E65   8D55FC                 lea     edx, [ebp-$04]
00671E68   8D8528FEFFFF           lea     eax, [ebp+$FFFFFE28]

|
00671E6E   E8D916D9FF             call    0040354C
00671E73   8D8528FEFFFF           lea     eax, [ebp+$FFFFFE28]

|
00671E79   E83A17D9FF             call    004035B8

|
00671E7E   E8F90AD9FF             call    0040297C
00671E83   8D55FC                 lea     edx, [ebp-$04]
00671E86   8D8528FEFFFF           lea     eax, [ebp+$FFFFFE28]

|
00671E8C   E8BB16D9FF             call    0040354C
00671E91   8D8528FEFFFF           lea     eax, [ebp+$FFFFFE28]

|
00671E97   E81C17D9FF             call    004035B8

|
00671E9C   E8DB0AD9FF             call    0040297C
00671EA1   8B45FC                 mov     eax, [ebp-$04]

|
00671EA4   E8972ED9FF             call    00404D40
00671EA9   84C0                   test    al, al
00671EAB   764B                   jbe     00671EF8
00671EAD   8845F7                 mov     [ebp-$09], al
00671EB0   B301                   mov     bl, $01
00671EB2   33C0                   xor     eax, eax
00671EB4   8AC3                   mov     al, bl
00671EB6   8B55FC                 mov     edx, [ebp-$04]
00671EB9   807C02FF30             cmp     byte ptr [edx+eax-$01], $30
00671EBE   7232                   jb      00671EF2
00671EC0   33C0                   xor     eax, eax
00671EC2   8AC3                   mov     al, bl
00671EC4   8B55FC                 mov     edx, [ebp-$04]
00671EC7   807C02FF39             cmp     byte ptr [edx+eax-$01], $39
00671ECC   7724                   jnbe    00671EF2
00671ECE   8D8524FEFFFF           lea     eax, [ebp+$FFFFFE24]
00671ED4   33D2                   xor     edx, edx
00671ED6   8AD3                   mov     dl, bl
00671ED8   8B4DFC                 mov     ecx, [ebp-$04]
00671EDB   8A5411FF               mov     dl, byte ptr [ecx+edx-$01]

|
00671EDF   E8842DD9FF             call    00404C68
00671EE4   8B9524FEFFFF           mov     edx, [ebp+$FFFFFE24]
00671EEA   8D45F8                 lea     eax, [ebp-$08]

|
00671EED   E8562ED9FF             call    00404D48
00671EF2   43                     inc     ebx
00671EF3   FE4DF7                 dec     byte ptr [ebp-$09]
00671EF6   75BA                   jnz     00671EB2
00671EF8   8B45F8                 mov     eax, [ebp-$08]

|
00671EFB   E8747BD9FF             call    00409A74
00671F00   69D8111C0000           imul    ebx, eax, $00001C11
00671F06   81C3E4070000           add     ebx, $000007E4
00671F0C   8D9520FEFFFF           lea     edx, [ebp+$FFFFFE20]
00671F12   8BC3                   mov     eax, ebx

|
00671F14   E8EF79D9FF             call    00409908
00671F19   8B9520FEFFFF           mov     edx, [ebp+$FFFFFE20]

* Reference to field TForm42.OFFS_038C
|
00671F1F   8D868C030000           lea     eax, [esi+$038C]

|
00671F25   E8AA2BD9FF             call    00404AD4
00671F2A   8D951CFEFFFF           lea     edx, [ebp+$FFFFFE1C]
00671F30   8BC3                   mov     eax, ebx

|
00671F32   E8D179D9FF             call    00409908
00671F37   8B951CFEFFFF           mov     edx, [ebp+$FFFFFE1C]

* Reference to control TForm42.sEdit1 : TsEdit
|
00671F3D   8B8680030000           mov     eax, [esi+$0380]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671F43   E81022DFFF             call    00464158

* Reference to field TForm42.OFFS_038C
|
00671F48   8B968C030000           mov     edx, [esi+$038C]

* Reference to control TForm42.Label2 : TLabel
|
00671F4E   8B867C030000           mov     eax, [esi+$037C]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00671F54   E8FF21DFFF             call    00464158
00671F59   33C0                   xor     eax, eax
00671F5B   5A                     pop     edx
00671F5C   59                     pop     ecx
00671F5D   59                     pop     ecx
00671F5E   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[ãÂ]√'
|
00671F61   688B1F6700             push    $00671F8B
00671F66   8D851CFEFFFF           lea     eax, [ebp+$FFFFFE1C]
00671F6C   BA03000000             mov     edx, $00000003

|
00671F71   E82E2BD9FF             call    00404AA4
00671F76   8D45F8                 lea     eax, [ebp-$08]
00671F79   BA02000000             mov     edx, $00000002

|
00671F7E   E8212BD9FF             call    00404AA4
00671F83   C3                     ret

00671F84   E9DB24D9FF             jmp     00404464
00671F89   EBDB                   jmp     00671F66

****** END
|
00671F8B   5E                     pop     esi
00671F8C   5B                     pop     ebx
00671F8D   8BE5                   mov     esp, ebp
00671F8F   5D                     pop     ebp
00671F90   C3                     ret

*)
end;

procedure TForm42.sBitBtn1Click(Sender : TObject);
begin
(*
00671FA4   53                     push    ebx
00671FA5   56                     push    esi
00671FA6   57                     push    edi
00671FA7   8BD8                   mov     ebx, eax

* Possible String Reference to: 'C:\Windows\System32\sgsql.dll'
|
00671FA9   B95C206700             mov     ecx, $0067205C
00671FAE   B201                   mov     dl, $01

* Reference to class TIniFile
|
00671FB0   A1341B4400             mov     eax, dword ptr [$00441B34]

* Reference to: Axctrls.TOleStream.Create(System.[DelphiInterfacePointer; Integer; IStream ])
|
00671FB5   E82AFCDCFF             call    00441BE4
00671FBA   8BF0                   mov     esi, eax

* Possible String Reference to: 'C:\Windows\System32\'
|
00671FBC   6884206700             push    $00672084

* Possible String Reference to: 'Dossier'
|
00671FC1   B9A4206700             mov     ecx, $006720A4

* Possible String Reference to: 'DOSSIER'
|
00671FC6   BAB4206700             mov     edx, $006720B4
00671FCB   8BC6                   mov     eax, esi
00671FCD   8B38                   mov     edi, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
00671FCF   FF5704                 call    dword ptr [edi+$04]

* Possible String Reference to: 'FAYCEL BOUDJIL©2017'
|
00671FD2   68C4206700             push    $006720C4

* Possible String Reference to: 'Copyright'
|
00671FD7   B9E0206700             mov     ecx, $006720E0

* Possible String Reference to: 'DOSSIER'
|
00671FDC   BAB4206700             mov     edx, $006720B4
00671FE1   8BC6                   mov     eax, esi
00671FE3   8B30                   mov     esi, [eax]

* Possible reference to virtual method TIniFile.OFFS_04
|
00671FE5   FF5604                 call    dword ptr [esi+$04]
00671FE8   33D2                   xor     edx, edx

* Reference to control TForm42.sEdit1 : TsEdit
|
00671FEA   8B8380030000           mov     eax, [ebx+$0380]
00671FF0   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsEdit.OFFS_64
|
00671FF2   FF5164                 call    dword ptr [ecx+$64]
00671FF5   33D2                   xor     edx, edx

* Reference to control TForm42.sBitBtn1 : TsBitBtn
|
00671FF7   8B8384030000           mov     eax, [ebx+$0384]

* Reference to: Controls.TControl.SetVisible()
|
00671FFD   E84620DFFF             call    00464048
00672002   33D2                   xor     edx, edx

* Reference to control TForm42.Label2 : TLabel
|
00672004   8B837C030000           mov     eax, [ebx+$037C]
0067200A   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel.OFFS_64
|
0067200C   FF5164                 call    dword ptr [ecx+$64]
0067200F   33D2                   xor     edx, edx

* Reference to control TForm42.sLabelFX17 : TsLabelFX
|
00672011   8B8378030000           mov     eax, [ebx+$0378]
00672017   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsLabelFX.OFFS_64
|
00672019   FF5164                 call    dword ptr [ecx+$64]
0067201C   33D2                   xor     edx, edx

* Reference to control TForm42.sLabelFX16 : TsLabelFX
|
0067201E   8B8374030000           mov     eax, [ebx+$0374]
00672024   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsLabelFX.OFFS_64
|
00672026   FF5164                 call    dword ptr [ecx+$64]

* Reference to Form42
|
00672029   A124366B00             mov     eax, dword ptr [$006B3624]

* Reference to field Form42.OFFS_0300
|
0067202E   8B8000030000           mov     eax, [eax+$0300]

* Possible String Reference to: '‰”Œ… ﬂ«„·…'
|
00672034   BAF4206700             mov     edx, $006720F4

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00672039   E81A21DFFF             call    00464158

* Possible String Reference to: '‰”Œ… ﬂ«„·‹‹‹… „‰ »—‰«„Ã  ”ÌÌ— «·—Ê«
|                                 » Ê«·„‰Õ'
|
0067203E   BA08216700             mov     edx, $00672108

* Reference to control TForm42.sLabelFX18 : TsLabelFX
|
00672043   8B8388030000           mov     eax, [ebx+$0388]

* Reference to: Controls.TControl.SetText(System.AnsiString)
|
00672049   E80A21DFFF             call    00464158
0067204E   5F                     pop     edi
0067204F   5E                     pop     esi
00672050   5B                     pop     ebx
00672051   C3                     ret

*)
end;

procedure TForm42.sBitBtn2Click(Sender : TObject);
begin
(*
00672138   55                     push    ebp
00672139   8BEC                   mov     ebp, esp
0067213B   6A00                   push    $00
0067213D   33D2                   xor     edx, edx
0067213F   55                     push    ebp

* Possible String Reference to: 'È"ŸˇÎY]√ç@'
|
00672140   686F216700             push    $0067216F
00672145   64FF32                 push    dword ptr fs:[edx]
00672148   648922                 mov     fs:[edx], esp
0067214B   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TForm42.Label2 : TLabel
|
0067214E   8B807C030000           mov     eax, [eax+$037C]

* Reference to: Controls.TControl.GetText()
|
00672154   E8CF1FDFFF             call    00464128
00672159   33C0                   xor     eax, eax
0067215B   5A                     pop     edx
0067215C   59                     pop     ecx
0067215D   59                     pop     ecx
0067215E   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'Y]√ç@'
|
00672161   6876216700             push    $00672176
00672166   8D45FC                 lea     eax, [ebp-$04]

|
00672169   E81229D9FF             call    00404A80
0067216E   C3                     ret

0067216F   E9F022D9FF             jmp     00404464
00672174   EBF0                   jmp     00672166

****** END
|
00672176   59                     pop     ecx
00672177   5D                     pop     ebp
00672178   C3                     ret

*)
end;

procedure TForm42._PROC_006720CE(Sender : TObject);
begin
(*
006720CE   44                     inc     esp
006720CF   4A                     dec     edx
006720D0   49                     dec     ecx
006720D1   4C                     dec     esp
006720D2   A932303137             test    eax, $37313032
006720D7   00FF                   add     bh, bh
006720D9   FFFF                   DB  $FF, $FF  //      
006720DB   FF09                   dec     dword ptr [ecx]
006720DD   0000                   add     [eax], al

*)
end;

procedure TForm42._PROC_0067217C(Sender : TObject);
begin
(*
0067217C   55                     push    ebp
0067217D   8BEC                   mov     ebp, esp
0067217F   33C0                   xor     eax, eax
00672181   55                     push    ebp

* Possible String Reference to: 'Èæ"ŸˇÎ¯]√ã¿É-(6k'
|
00672182   68A1216700             push    $006721A1
00672187   64FF30                 push    dword ptr fs:[eax]
0067218A   648920                 mov     fs:[eax], esp
0067218D   FF0528366B00           inc     dword ptr [$006B3628]
00672193   33C0                   xor     eax, eax
00672195   5A                     pop     edx
00672196   59                     pop     ecx
00672197   59                     pop     ecx
00672198   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-(6k'
|
0067219B   68A8216700             push    $006721A8
006721A0   C3                     ret

006721A1   E9BE22D9FF             jmp     00404464
006721A6   EBF8                   jmp     006721A0

****** END
|
006721A8   5D                     pop     ebp
006721A9   C3                     ret

*)
end;

procedure TForm42._PROC_006721AC(Sender : TObject);
begin
(*
006721AC   832D28366B0001         sub     dword ptr [$006B3628], +$01
006721B3   C3                     ret

*)
end;

procedure TForm42._PROC_006721B4(Sender : TObject);
begin
(*
006721B4   0022                   add     [edx], ah
006721B6   670000                 add     [bx+si], al
006721B9   0000                   add     [eax], al

*)
end;

end.