unit Unit22;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Grids, DBGrids, acDBGrid,
  sEdit, sSpinEdit, acDBDecimalSpinEdit, DBCtrls, sDBComboBox, Mask,
  sDBEdit, acPNG, acImage, ComCtrls, sPageControl, Buttons, sBitBtn,
  sSpeedButton, sLabel, sPanel,sSkinManager, sComboBox;
type
  TForm22=class(TForm)
    sPanel4: TsPanel;
    sLabelFX4: TsLabelFX;
    sSpeedButton8: TsSpeedButton;
    sSpeedButton1: TsSpeedButton;
    sBitBtn2: TsBitBtn;
    sBitBtn32: TsBitBtn;
    sPageControl1: TsPageControl;
    sTabSheet1: TsTabSheet;
    sTabSheet2: TsTabSheet;
    sTabSheet3: TsTabSheet;
    sPanel1: TsPanel;
    sImage1: TsImage;
    sLabelFX2: TsLabelFX;
    sImage2: TsImage;
    sImage3: TsImage;
    sImage4: TsImage;
    sImage5: TsImage;
    sImage6: TsImage;
    sImage7: TsImage;
    sImage8: TsImage;
    sImage9: TsImage;
    sLabelFX6: TsLabelFX;
    sLabelFX1: TsLabelFX;
    sLabelFX3: TsLabelFX;
    sLabelFX5: TsLabelFX;
    sLabelFX11: TsLabelFX;
    sLabelFX10: TsLabelFX;
    sLabelFX8: TsLabelFX;
    sLabelFX9: TsLabelFX;
    sPanel9: TsPanel;
    Edit1: TEdit;
    sPanel2: TsPanel;
    sPanel3: TsPanel;
    sImage10: TsImage;
    sLabelFX7: TsLabelFX;
    sImage11: TsImage;
    sImage13: TsImage;
    sImage14: TsImage;
    sImage16: TsImage;
    sLabelFX13: TsLabelFX;
    sLabelFX14: TsLabelFX;
    sLabelFX15: TsLabelFX;
    sLabelFX18: TsLabelFX;
    sPanel5: TsPanel;
    Edit2: TEdit;
    sPanel6: TsPanel;
    sImage19: TsImage;
    sLabelFX20: TsLabelFX;
    sImage20: TsImage;
    sImage25: TsImage;
    sLabelFX22: TsLabelFX;
    sLabelFX27: TsLabelFX;
    sPanel7: TsPanel;
    Edit3: TEdit;
    sLabelFX12: TsLabelFX;
    sImage12: TsImage;
    sTabSheet4: TsTabSheet;
    sPanel8: TsPanel;
    sImage15: TsImage;
    sPanel10: TsPanel;
    Edit4: TEdit;
    sPanel11: TsPanel;
    sPanel12: TsPanel;
    sBitBtn8: TsBitBtn;
    sBitBtn9: TsBitBtn;
    sBitBtn10: TsBitBtn;
    sLabelFX17: TsLabelFX;
    sLabelFX16: TsLabelFX;
    sDBGrid1: TsDBGrid;
    sDBDecimalSpinEdit1: TsDBDecimalSpinEdit;
    sLabelFX19: TsLabelFX;
    sImage17: TsImage;
    sLabelFX21: TsLabelFX;
    Timer1: TTimer;
    sBitBtn1: TsBitBtn;
    sEdit1: TsEdit;
    sEdit2: TsEdit;
    sEdit3: TsEdit;
    sEdit4: TsEdit;
    sEdit5: TsEdit;
    sEdit6: TsEdit;
    sEdit7: TsEdit;
    sEdit8: TsEdit;
    sEdit9: TsEdit;
    sEdit10: TsEdit;
    sEdit11: TsEdit;
    sComboBox1: TsComboBox;
    sComboBox2: TsComboBox;
    sComboBox3: TsComboBox;
    sEdit12: TsEdit;
    sBitBtn3: TsBitBtn;
    procedure sBitBtn2Click(Sender : TObject);
    procedure sBitBtn32Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure sBitBtn8Click(Sender : TObject);
    procedure sBitBtn9Click(Sender : TObject);
    procedure sBitBtn10Click(Sender : TObject);
    procedure Timer1Timer(Sender : TObject);
    procedure _PROC_00668B91(Sender : TObject);
    procedure _PROC_00668BC0(Sender : TObject);
    procedure _PROC_00668BC8(Sender : TObject);
    procedure _PROC_00668D09(Sender : TObject);
    procedure sBitBtn1Click(Sender: TObject);
    procedure sBitBtn3Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form22: TForm22;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation
      uses
        Unit2,unit1;
{$R *.DFM}

procedure TForm22.sBitBtn2Click(Sender : TObject);
begin
  //006668B0
  with data do begin
    SetParametre('Aliase','Data/dest.abs');
    SetParametre('W_demine',sComboBox3.Text);
    SetParametre('Mof_daraib',sEdit12.Text);
    SetParametre('As_per',sEdit10.Text);
    SetParametre('W_cnas',sComboBox2.Text);
    SetParametre('Adress_cnas',sEdit6.Text);
    SetParametre('Ccp_cnas',sEdit11.Text);
    SetParametre('Cfpa',sEdit1.Text);
    SetParametre('CODE',sEdit7.Text);
    SetParametre('APC',sEdit2.Text);
    SetParametre('WEL',sComboBox1.Text);
    SetParametre('C_ard',sEdit4.Text);
    SetParametre('Adresse',sEdit5.Text);
    SetParametre('Tel',sEdit3.Text);
    SetParametre('PrZone',sDBDecimalSpinEdit1.Text);
    SetParametre('A-sarf',sEdit9.Text);
    SetParametre('C_a_c',sEdit8.Text);
  end;

end;

procedure TForm22.sBitBtn32Click(Sender : TObject);
begin
  //006668D0
  sBitBtn2Click(Sender);
  ModalResult := mrOk;
end;

procedure TForm22.FormShow(Sender : TObject);
begin
   with data do begin
    sComboBox3.Text := GetParametre('W_demine');
    sEdit12.Text    := GetParametre('Mof_daraib');
    sEdit10.Text    := GetParametre('As_per');
    sComboBox2.Text := GetParametre('W_cnas');
    sEdit6.Text     := GetParametre('Adress_cnas');
    sEdit11.Text    := GetParametre('Ccp_cnas');
    sEdit1.Text     := GetParametre('Cfpa');
    sEdit7.Text     := GetParametre('CODE');
    sEdit2.Text     := GetParametre('APC');
    sComboBox1.Text := GetParametre('WEL');
    sEdit4.Text     := GetParametre('C_ard');
    sEdit5.Text     := GetParametre('Adresse');
    sEdit3.Text     := GetParametre('Tel');
    sDBDecimalSpinEdit1.Text := GetParametre('PrZone');
    sEdit9.Text     := GetParametre('A-sarf');
    sEdit8.Text     := GetParametre('C_a_c');
  end;
end;

procedure TForm22.sBitBtn8Click(Sender : TObject);
begin
  //00668AEC
  Data.ABSBanque.Append;
end;

procedure TForm22.sBitBtn9Click(Sender : TObject);
begin
  //00668B00
  Data.ABSBanque.Edit;
end;

procedure TForm22.sBitBtn10Click(Sender : TObject);
begin
  //00668B14
  with data do begin
    if ABSBanque.IsEmpty then
       raise Exception.Create('áÇ íæÌÏ ÊÚííä ááÍÐÝ')
    else
      ABSBanque.Delete;
  end;
end;

procedure TForm22.Timer1Timer(Sender : TObject);
begin
  //00668B70
   Form22.sLabelFX21.Visible:= not Form22.sLabelFX21.Visible;
end;

procedure TForm22._PROC_00668B91(Sender : TObject);
begin
(*
00668B91   8BEC                   mov     ebp, esp
00668B93   33C0                   xor     eax, eax
00668B95   55                     push    ebp

* Possible String Reference to: 'éª¸Ùÿëø]Ã‹Àƒ-ˆ5k'
|
00668B96   68B58B6600             push    $00668BB5
00668B9B   64FF30                 push    dword ptr fs:[eax]
00668B9E   648920                 mov     fs:[eax], esp
00668BA1   FF0588356B00           inc     dword ptr [$006B3588]
00668BA7   33C0                   xor     eax, eax
00668BA9   5A                     pop     edx
00668BAA   59                     pop     ecx
00668BAB   59                     pop     ecx
00668BAC   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ˆ5k'
|
00668BAF   68BC8B6600             push    $00668BBC
00668BB4   C3                     ret

00668BB5   E9AAB8D9FF             jmp     00404464
00668BBA   EBF8                   jmp     00668BB4

****** END
|
00668BBC   5D                     pop     ebp
00668BBD   C3                     ret

*)
end;

procedure TForm22._PROC_00668BC0(Sender : TObject);
begin
(*
00668BC0   832D88356B0001         sub     dword ptr [$006B3588], +$01
00668BC7   C3                     ret

*)
end;

procedure TForm22._PROC_00668BC8(Sender : TObject);
begin
(*
00668BC8   148C                   adc     al, $8C
00668BCA   660000                 add     [eax], al

*)
end;

procedure TForm22._PROC_00668D09(Sender : TObject);
begin
(*
00668D09   006992                 add     [ecx-$6E], ch
00668D0C   6600F8                 add     al, bh
00668D0F   0200                   add     al, byte ptr [eax]
00668D11   0000                   add     [eax], al

*)
end;

procedure TForm22.sBitBtn1Click(Sender: TObject);
begin
 ModalResult := mrCancel;
end;

procedure TForm22.sBitBtn3Click(Sender: TObject);
begin
 Data.ABSBanque.Post; 
end;

end.