unit Unit26;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QRCtrls, QuickRpt, ExtCtrls;
type
  TForm26=class(TForm)
    QuickRep1: TQuickRep;
    QRBand1: TQRBand;
    QRShape8: TQRShape;
    QRLabel21: TQRLabel;
    QRShape9: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape15: TQRShape;
    QRLabel30: TQRLabel;
    QRLabel32: TQRLabel;
    QRShape19: TQRShape;
    QRLabel33: TQRLabel;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRLabel34: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel36: TQRLabel;
    QRLabel37: TQRLabel;
    QRLabel38: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel40: TQRLabel;
    QRLabel41: TQRLabel;
    QRLabel42: TQRLabel;
    QRLabel43: TQRLabel;
    QRLabel44: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel46: TQRLabel;
    QRLabel47: TQRLabel;
    QRBand6: TQRBand;
    QRShape6: TQRShape;
    QRShape5: TQRShape;
    QRShape4: TQRShape;
    QRShape3: TQRShape;
    QRShape2: TQRShape;
    QRLabel4: TQRLabel;
    QRDBText20: TQRDBText;
    QRDBText19: TQRDBText;
    QRDBText18: TQRDBText;
    QRDBText17: TQRDBText;
    QRDBText16: TQRDBText;
    QRShape39: TQRShape;
    QRShape38: TQRShape;
    QRShape37: TQRShape;
    QRShape36: TQRShape;
    QRShape35: TQRShape;
    QRShape31: TQRShape;
    QRLabel5: TQRLabel;
    QRDBText25: TQRDBText;
    QRDBText24: TQRDBText;
    QRDBText23: TQRDBText;
    QRDBText22: TQRDBText;
    QRDBText21: TQRDBText;
    QRShape32: TQRShape;
    QRShape30: TQRShape;
    QRShape29: TQRShape;
    QRShape28: TQRShape;
    QRShape27: TQRShape;
    QRShape18: TQRShape;
    QRLabel3: TQRLabel;
    QRDBText15: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText11: TQRDBText;
    QRShape7: TQRShape;
    QRShape17: TQRShape;
    QRShape16: TQRShape;
    QRShape14: TQRShape;
    QRShape13: TQRShape;
    QRShape10: TQRShape;
    QRLabel2: TQRLabel;
    QRDBText9: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText10: TQRDBText;
    QRLabel24: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel31: TQRLabel;
    QRDBText1: TQRDBText;
    QRDBText45: TQRDBText;
    QRDBText46: TQRDBText;
    QRLabel1: TQRLabel;
    procedure _PROC_0066A82C(Sender : TObject);
    procedure _PROC_0066A834(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form26: TForm26;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm26._PROC_0066A82C(Sender : TObject);
begin
(*
0066A82C   832DA8356B0001         sub     dword ptr [$006B35A8], +$01
0066A833   C3                     ret

*)
end;

procedure TForm26._PROC_0066A834(Sender : TObject);
begin
(*
0066A834   80A86600000000         sub     byte ptr [eax+$0066], $00
0066A83B   0000                   add     [eax], al

*)
end;

end.