unit Unit2222;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, ComCtrls, acProgressBar,
  jpeg;
type
  TSplash=class(TForm)
    Image3: TImage;
    Timer1: TTimer;
    sProgressBar1: TsProgressBar;
    procedure Timer1Timer(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Splash: TSplash;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TSplash.Timer1Timer(Sender : TObject);
begin
  //006A5ED0
  Splash.sProgressBar1.Visible :=True;
  Splash.sProgressBar1.position:=Splash.sProgressBar1.position+3;

end;

end.
