unit Unit40;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QuickRpt, QRCtrls, ExtCtrls;
type
  TForm40=class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape2: TQRShape;
    QRLabel1: TQRLabel;
    QRShape6: TQRShape;
    QRLabel6: TQRLabel;
    QRShape7: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    QRDBText45: TQRDBText;
    QRDBText46: TQRDBText;
    QRDBText1: TQRDBText;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRSubDetail3: TQRSubDetail;
    SummaryBand1: TQRBand;
    QRLabel50: TQRLabel;
    QRLabel51: TQRLabel;
    QRLabel52: TQRLabel;
    QRShape1: TQRShape;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRDBText44: TQRDBText;
    QRDBText18: TQRDBText;
    QRDBText43: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRShape8: TQRShape;
    QRLabel48: TQRLabel;
    QRDBText23: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    procedure _PROC_00671084(Sender : TObject);
    procedure _PROC_0067108C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form40: TForm40;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm40._PROC_00671084(Sender : TObject);
begin
(*
00671084   832D18366B0001         sub     dword ptr [$006B3618], +$01
0067108B   C3                     ret

*)
end;

procedure TForm40._PROC_0067108C(Sender : TObject);
begin
(*
0067108C   D810                   fcom    dword ptr [eax]
0067108E   670000                 add     [bx+si], al
00671091   0000                   add     [eax], al

*)
end;

end.