unit Unit4;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Grids, DBGrids, acDBGrid,
  DBCtrls, Mask, sMaskEdit, sCustomComboEdit, sToolEdit, sDBDateEdit,
  sDBComboBox, sDBEdit, Buttons, sBitBtn, sLabel, sPanel, acNoteBook,DateUtils,
  sDBLookupComboBox,DB, ActnList, DBActns;
type
  TForm4=class(TForm)
    sPanel6: TsPanel;
    sPanel8: TsPanel;
    sLabelFX5: TsLabelFX;
    sLabelFX12: TsLabelFX;
    sLabelFX26: TsLabelFX;
    sLabelFX32: TsLabelFX;
    DBEdit1: TDBEdit;
    sDBDateEdit4: TsDBDateEdit;
    sDBEdit12: TsDBEdit;
    sDBEdit23: TsDBEdit;
    DBImage2: TDBImage;
    sPanel9: TsPanel;
    sPanel22: TsPanel;
    sPanel10: TsPanel;
    DBEdit4: TDBEdit;
    sPanel11: TsPanel;
    sBitBtn8: TsBitBtn;
    sBitBtn9: TsBitBtn;
    sBitBtn10: TsBitBtn;
    sPanel16: TsPanel;
    sPanel18: TsPanel;
    sPanel4: TsPanel;
    sBitBtn2: TsBitBtn;
    sBitBtn32: TsBitBtn;
    sDBGrid1: TsDBGrid;
    sDBGrid2: TsDBGrid;
    sLabelFX15: TsLabelFX;
    sLabelFX13: TsLabelFX;
    sDBEdit19: TsDBEdit;
    sLabelFX30: TsLabelFX;
    sDBEdit20: TsDBEdit;
    sLabelFX31: TsLabelFX;
    sDBEdit22: TsDBEdit;
    sLabelFX29: TsLabelFX;
    sDBEdit18: TsDBEdit;
    sLabelFX28: TsLabelFX;
    sDBEdit21: TsDBEdit;
    sBitBtn1: TsBitBtn;
    sBitBtn3: TsBitBtn;
    sBitBtn4: TsBitBtn;
    sBitBtn12: TsBitBtn;
    Edit1: TEdit;
    sDBComboBox1: TsDBComboBox;
    sLabelFX8: TsLabelFX;
    sDBEdit2: TsDBEdit;
    sLabelFX21: TsLabelFX;
    Timer1: TTimer;
    sNotebook1: TNotebook;
    sPanel1: TsPanel;
    sLabelFX1: TsLabelFX;
    sLabelFX2: TsLabelFX;
    DBEdit2: TDBEdit;
    sPanel2: TsPanel;
    sBitBtn5: TsBitBtn;
    sBitBtn6: TsBitBtn;
    sDBEdit1: TsDBEdit;
    sDBComboBox2: TsDBComboBox;
    sPanel3: TsPanel;
    sLabelFX3: TsLabelFX;
    sLabelFX6: TsLabelFX;
    sLabelFX7: TsLabelFX;
    sLabelFX4: TsLabelFX;
    DBEdit3: TDBEdit;
    sPanel5: TsPanel;
    sBitBtn7: TsBitBtn;
    sBitBtn11: TsBitBtn;
    sDBEdit3: TsDBEdit;
    sDBDateEdit1: TsDBDateEdit;
    sDBComboBox3: TsDBComboBox;
    sDBComboBox4: TsDBComboBox;
    sDBLookupComboBox2: TsDBLookupComboBox;
    sBitBtn13: TsBitBtn;
    ActionList1: TActionList;
    DataSetPost1: TDataSetPost;
    DataSetPost2: TDataSetPost;
    DataSetCancel1: TDataSetCancel;
    procedure sBitBtn2Click(Sender : TObject);
    procedure sBitBtn32Click(Sender : TObject);
    procedure sBitBtn8Click(Sender : TObject);
    procedure sBitBtn9Click(Sender : TObject);
    procedure sBitBtn10Click(Sender : TObject);
    procedure sBitBtn1Click(Sender : TObject);
    procedure sBitBtn3Click(Sender : TObject);
    procedure sBitBtn4Click(Sender : TObject);
    procedure sComboBox2Change(Sender : TObject);
    procedure sBitBtn5Click(Sender : TObject);
    procedure sBitBtn6Click(Sender : TObject);
    procedure sBitBtn7Click(Sender : TObject);
    procedure sBitBtn11Click(Sender : TObject);
    procedure sBitBtn12Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure Timer1Timer(Sender : TObject);
    procedure _PROC_006118FC(Sender : TObject);
    procedure _PROC_00612640(Sender : TObject);
    procedure _PROC_00618E69(Sender : TObject);
    procedure _PROC_00618E98(Sender : TObject);
    procedure _PROC_00618EA0(Sender : TObject);
    procedure FormCreate(Sender: TObject);
    procedure sDBComboBox1Change(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form4: TForm4;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation
    uses
      Unit2;
{$R *.DFM}

procedure TForm4.sBitBtn2Click(Sender : TObject);
begin
  //00611980
  with Data do begin
    ABSconjoit.Cancel;
    ABSenfant.Cancel;
    Absemp.Cancel;
  end;
  Close;
end;

procedure TForm4.sBitBtn32Click(Sender : TObject);
begin
  //006119C4
  with Data do begin
    if(ABSEmpSituation_f.IsNull)then
      Form4.Timer1.Enabled := True;
      if not (ABSEmp.State in dsWriteModes) then ABSEmp.Post; //Refresh;
  end;
  Close;
end;

procedure TForm4.sBitBtn8Click(Sender : TObject);
begin
  //00612678
  Data.ABSconjoit.Append;
  sNotebook1.Visible :=True;
  sNotebook1.PageIndex:=0;

end;

procedure TForm4.sBitBtn9Click(Sender : TObject);
begin
 // 0061269C
 Data.ABSconjoit.edit;
 sNotebook1.PageIndex:=0;
 sNotebook1.Visible:=True;
end;

procedure TForm4.sBitBtn10Click(Sender : TObject);
begin
  //006126C0
  with Data do begin
   if(ABSconjoit.IsEmpty)then MessageDlg('·«Ì„ﬂ‰ﬂ Õ–› ›«—€', mtCustom, mbOKCancel, 0)
   else
    if(MessageDlg(' «ﬂÌœ ⁄„·Ì… «·Õ–›', mtCustom, mbOKCancel, 0) = mrOk) then begin
       if(not ABSenfant.IsEmpty)then begin
            ABSenfant.First;
            while (not ABSenfant.Eof) do begin
                ABSenfant.Delete;
                ABSenfant.Next;
            end;
       end;
      ABSenfant.Delete;
      UpdateZawaj;
    end;
  end;
end;

procedure TForm4.sBitBtn1Click(Sender : TObject);
begin
  //00612A2C
  if(Data.ABSconjoit.IsEmpty)then
    raise Exception.Create('ÌÃ» «œŒ«· »Ì«‰«  «·“ÊÃ… «Ê·«')
  else begin
    Data.ABSenfant.Append;
    sNotebook1.Visible:= True;
     sNotebook1.PageIndex:=1;

  end;

end;

procedure TForm4.sBitBtn3Click(Sender : TObject);
begin
  //00612AA4
  if(Data.ABSconjoitNom_prenom.AsString = '') then
    raise Exception.Create('ÌÃ» «œŒ«· „⁄·Ê„«  «·„ÊŸ› «Ê·«')
  else begin
    Data.ABSenfant.Edit;
    sNotebook1.Visible := True;
     sNotebook1.PageIndex:=1;

  end;
end;

procedure TForm4.sBitBtn4Click(Sender : TObject);
begin
  //00612B58
 with Data do begin
  if(ABSenfant.IsEmpty) then
   MessageDlg('·«Ì„ﬂ‰ﬂ Õ–› ›—«€', mtCustom, mbOKCancel, 0)
  else
  if(MessageDlg(' «ﬂÌœ «·Õ–›', mtCustom, mbOKCancel, 0) = mrOk) then begin
    ABSenfant.Delete;
    UpdateZawaj;
  end;
 end;
end;

procedure TForm4.sComboBox2Change(Sender : TObject);
begin
(*
00612E78   55                     push    ebp
00612E79   8BEC                   mov     ebp, esp
00612E7B   B904000000             mov     ecx, $00000004
00612E80   6A00                   push    $00
00612E82   6A00                   push    $00
00612E84   49                     dec     ecx
00612E85   75F9                   jnz     00612E80
00612E87   51                     push    ecx
00612E88   53                     push    ebx
00612E89   56                     push    esi
00612E8A   8BD8                   mov     ebx, eax

* Reference to TData instance
|
00612E8C   8B35D8F06A00           mov     esi, [$006AF0D8]
00612E92   33C0                   xor     eax, eax
00612E94   55                     push    ebp
00612E95   68E9326100             push    $006132E9
00612E9A   64FF30                 push    dword ptr fs:[eax]
00612E9D   648920                 mov     fs:[eax], esp
00612EA0   8D55FC                 lea     edx, [ebp-$04]

* Reference to Form4
|
00612EA3   A128336B00             mov     eax, dword ptr [$006B3328]

* Reference to field Form4.OFFS_03EC
|
00612EA8   8B80EC030000           mov     eax, [eax+$03EC]

* Reference to: Controls.TControl.GetText()
|
00612EAE   E87512E5FF             call    00464128
00612EB3   8B55FC                 mov     edx, [ebp-$04]
00612EB6   8B06                   mov     eax, [esi]
00612EB8   8B8084090000           mov     eax, [eax+$0984]
00612EBE   8B08                   mov     ecx, [eax]
00612EC0   FF91B0000000           call    dword ptr [ecx+$00B0]
00612EC6   8D55F8                 lea     edx, [ebp-$08]
00612EC9   8B06                   mov     eax, [esi]
00612ECB   8B8084090000           mov     eax, [eax+$0984]
00612ED1   8B08                   mov     ecx, [eax]
00612ED3   FF5160                 call    dword ptr [ecx+$60]
00612ED6   8B45F8                 mov     eax, [ebp-$08]

* Possible String Reference to: '√⁄“»'
|
00612ED9   BA00336100             mov     edx, $00613300

|
00612EDE   E8A91FDFFF             call    00404E8C
00612EE3   0F85CF000000           jnz     00612FB8
00612EE9   8B06                   mov     eax, [esi]
00612EEB   8B808C090000           mov     eax, [eax+$098C]
00612EF1   33D2                   xor     edx, edx
00612EF3   8B08                   mov     ecx, [eax]
00612EF5   FF91A8000000           call    dword ptr [ecx+$00A8]
00612EFB   8B06                   mov     eax, [esi]
00612EFD   8B8090090000           mov     eax, [eax+$0990]
00612F03   33D2                   xor     edx, edx
00612F05   8B08                   mov     ecx, [eax]
00612F07   FF91A8000000           call    dword ptr [ecx+$00A8]
00612F0D   8B06                   mov     eax, [esi]
00612F0F   8B8094090000           mov     eax, [eax+$0994]
00612F15   33D2                   xor     edx, edx
00612F17   8B08                   mov     ecx, [eax]
00612F19   FF91A8000000           call    dword ptr [ecx+$00A8]
00612F1F   8B06                   mov     eax, [esi]
00612F21   8B8098090000           mov     eax, [eax+$0998]
00612F27   33D2                   xor     edx, edx
00612F29   8B08                   mov     ecx, [eax]
00612F2B   FF91A8000000           call    dword ptr [ecx+$00A8]
00612F31   8B06                   mov     eax, [esi]
00612F33   8B809C090000           mov     eax, [eax+$099C]
00612F39   33D2                   xor     edx, edx
00612F3B   8B08                   mov     ecx, [eax]
00612F3D   FF91A8000000           call    dword ptr [ecx+$00A8]
00612F43   33D2                   xor     edx, edx

* Reference to control TForm4.sDBGrid1 : TsDBGrid
|
00612F45   8B835C030000           mov     eax, [ebx+$035C]
00612F4B   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBGrid.OFFS_64
|
00612F4D   FF5164                 call    dword ptr [ecx+$64]
00612F50   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn8 : TsBitBtn
|
00612F52   8B833C030000           mov     eax, [ebx+$033C]
00612F58   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00612F5A   FF5164                 call    dword ptr [ecx+$64]
00612F5D   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn9 : TsBitBtn
|
00612F5F   8B8340030000           mov     eax, [ebx+$0340]
00612F65   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00612F67   FF5164                 call    dword ptr [ecx+$64]
00612F6A   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn10 : TsBitBtn
|
00612F6C   8B8344030000           mov     eax, [ebx+$0344]
00612F72   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00612F74   FF5164                 call    dword ptr [ecx+$64]
00612F77   33D2                   xor     edx, edx

* Reference to control TForm4.sDBGrid2 : TsDBGrid
|
00612F79   8B8360030000           mov     eax, [ebx+$0360]
00612F7F   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBGrid.OFFS_64
|
00612F81   FF5164                 call    dword ptr [ecx+$64]
00612F84   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn1 : TsBitBtn
|
00612F86   8B8390030000           mov     eax, [ebx+$0390]
00612F8C   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00612F8E   FF5164                 call    dword ptr [ecx+$64]
00612F91   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn3 : TsBitBtn
|
00612F93   8B8394030000           mov     eax, [ebx+$0394]
00612F99   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00612F9B   FF5164                 call    dword ptr [ecx+$64]
00612F9E   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn4 : TsBitBtn
|
00612FA0   8B8398030000           mov     eax, [ebx+$0398]
00612FA6   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00612FA8   FF5164                 call    dword ptr [ecx+$64]
00612FAB   33D2                   xor     edx, edx

* Reference to control TForm4.sDBEdit19 : TsDBEdit
|
00612FAD   8B836C030000           mov     eax, [ebx+$036C]
00612FB3   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBEdit.OFFS_64
|
00612FB5   FF5164                 call    dword ptr [ecx+$64]
00612FB8   8D55F4                 lea     edx, [ebp-$0C]
00612FBB   8B06                   mov     eax, [esi]
00612FBD   8B8084090000           mov     eax, [eax+$0984]
00612FC3   8B08                   mov     ecx, [eax]
00612FC5   FF5160                 call    dword ptr [ecx+$60]
00612FC8   8B45F4                 mov     eax, [ebp-$0C]

* Possible String Reference to: '⁄“»«¡'
|
00612FCB   BA10336100             mov     edx, $00613310

|
00612FD0   E8B71EDFFF             call    00404E8C
00612FD5   0F85CF000000           jnz     006130AA
00612FDB   8B06                   mov     eax, [esi]
00612FDD   8B808C090000           mov     eax, [eax+$098C]
00612FE3   33D2                   xor     edx, edx
00612FE5   8B08                   mov     ecx, [eax]
00612FE7   FF91A8000000           call    dword ptr [ecx+$00A8]
00612FED   8B06                   mov     eax, [esi]
00612FEF   8B8090090000           mov     eax, [eax+$0990]
00612FF5   33D2                   xor     edx, edx
00612FF7   8B08                   mov     ecx, [eax]
00612FF9   FF91A8000000           call    dword ptr [ecx+$00A8]
00612FFF   8B06                   mov     eax, [esi]
00613001   8B8094090000           mov     eax, [eax+$0994]
00613007   33D2                   xor     edx, edx
00613009   8B08                   mov     ecx, [eax]
0061300B   FF91A8000000           call    dword ptr [ecx+$00A8]
00613011   8B06                   mov     eax, [esi]
00613013   8B8098090000           mov     eax, [eax+$0998]
00613019   33D2                   xor     edx, edx
0061301B   8B08                   mov     ecx, [eax]
0061301D   FF91A8000000           call    dword ptr [ecx+$00A8]
00613023   8B06                   mov     eax, [esi]
00613025   8B809C090000           mov     eax, [eax+$099C]
0061302B   33D2                   xor     edx, edx
0061302D   8B08                   mov     ecx, [eax]
0061302F   FF91A8000000           call    dword ptr [ecx+$00A8]
00613035   33D2                   xor     edx, edx

* Reference to control TForm4.sDBGrid1 : TsDBGrid
|
00613037   8B835C030000           mov     eax, [ebx+$035C]
0061303D   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBGrid.OFFS_64
|
0061303F   FF5164                 call    dword ptr [ecx+$64]
00613042   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn8 : TsBitBtn
|
00613044   8B833C030000           mov     eax, [ebx+$033C]
0061304A   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
0061304C   FF5164                 call    dword ptr [ecx+$64]
0061304F   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn9 : TsBitBtn
|
00613051   8B8340030000           mov     eax, [ebx+$0340]
00613057   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00613059   FF5164                 call    dword ptr [ecx+$64]
0061305C   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn10 : TsBitBtn
|
0061305E   8B8344030000           mov     eax, [ebx+$0344]
00613064   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00613066   FF5164                 call    dword ptr [ecx+$64]
00613069   33D2                   xor     edx, edx

* Reference to control TForm4.sDBGrid2 : TsDBGrid
|
0061306B   8B8360030000           mov     eax, [ebx+$0360]
00613071   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBGrid.OFFS_64
|
00613073   FF5164                 call    dword ptr [ecx+$64]
00613076   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn1 : TsBitBtn
|
00613078   8B8390030000           mov     eax, [ebx+$0390]
0061307E   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00613080   FF5164                 call    dword ptr [ecx+$64]
00613083   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn3 : TsBitBtn
|
00613085   8B8394030000           mov     eax, [ebx+$0394]
0061308B   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
0061308D   FF5164                 call    dword ptr [ecx+$64]
00613090   33D2                   xor     edx, edx

* Reference to control TForm4.sBitBtn4 : TsBitBtn
|
00613092   8B8398030000           mov     eax, [ebx+$0398]
00613098   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
0061309A   FF5164                 call    dword ptr [ecx+$64]
0061309D   33D2                   xor     edx, edx

* Reference to control TForm4.sDBEdit19 : TsDBEdit
|
0061309F   8B836C030000           mov     eax, [ebx+$036C]
006130A5   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBEdit.OFFS_64
|
006130A7   FF5164                 call    dword ptr [ecx+$64]
006130AA   8D55F0                 lea     edx, [ebp-$10]
006130AD   8B06                   mov     eax, [esi]
006130AF   8B8084090000           mov     eax, [eax+$0984]
006130B5   8B08                   mov     ecx, [eax]
006130B7   FF5160                 call    dword ptr [ecx+$60]
006130BA   8B45F0                 mov     eax, [ebp-$10]

* Possible String Reference to: '„ “ÊÃ'
|
006130BD   BA20336100             mov     edx, $00613320

|
006130C2   E8C51DDFFF             call    00404E8C
006130C7   0F85DC000000           jnz     006131A9
006130CD   8B06                   mov     eax, [esi]
006130CF   8B405C                 mov     eax, [eax+$5C]
006130D2   8B10                   mov     edx, [eax]
006130D4   FF924C010000           call    dword ptr [edx+$014C]
006130DA   8BD0                   mov     edx, eax
006130DC   8B06                   mov     eax, [esi]
006130DE   8B808C090000           mov     eax, [eax+$098C]
006130E4   8B08                   mov     ecx, [eax]
006130E6   FF91A8000000           call    dword ptr [ecx+$00A8]
006130EC   8B06                   mov     eax, [esi]
006130EE   8B8090090000           mov     eax, [eax+$0990]
006130F4   33D2                   xor     edx, edx
006130F6   8B08                   mov     ecx, [eax]
006130F8   FF91A8000000           call    dword ptr [ecx+$00A8]
006130FE   8B06                   mov     eax, [esi]
00613100   8B8094090000           mov     eax, [eax+$0994]
00613106   33D2                   xor     edx, edx
00613108   8B08                   mov     ecx, [eax]
0061310A   FF91A8000000           call    dword ptr [ecx+$00A8]
00613110   8B06                   mov     eax, [esi]
00613112   8B8098090000           mov     eax, [eax+$0998]
00613118   33D2                   xor     edx, edx
0061311A   8B08                   mov     ecx, [eax]
0061311C   FF91A8000000           call    dword ptr [ecx+$00A8]
00613122   8B06                   mov     eax, [esi]
00613124   8B809C090000           mov     eax, [eax+$099C]
0061312A   33D2                   xor     edx, edx
0061312C   8B08                   mov     ecx, [eax]
0061312E   FF91A8000000           call    dword ptr [ecx+$00A8]
00613134   B201                   mov     dl, $01

* Reference to control TForm4.sDBGrid1 : TsDBGrid
|
00613136   8B835C030000           mov     eax, [ebx+$035C]
0061313C   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBGrid.OFFS_64
|
0061313E   FF5164                 call    dword ptr [ecx+$64]
00613141   B201                   mov     dl, $01

* Reference to control TForm4.sBitBtn8 : TsBitBtn
|
00613143   8B833C030000           mov     eax, [ebx+$033C]
00613149   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
0061314B   FF5164                 call    dword ptr [ecx+$64]
0061314E   B201                   mov     dl, $01

* Reference to control TForm4.sBitBtn9 : TsBitBtn
|
00613150   8B8340030000           mov     eax, [ebx+$0340]
00613156   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00613158   FF5164                 call    dword ptr [ecx+$64]
0061315B   B201                   mov     dl, $01

* Reference to control TForm4.sBitBtn10 : TsBitBtn
|
0061315D   8B8344030000           mov     eax, [ebx+$0344]
00613163   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00613165   FF5164                 call    dword ptr [ecx+$64]
00613168   B201                   mov     dl, $01

* Reference to control TForm4.sDBGrid2 : TsDBGrid
|
0061316A   8B8360030000           mov     eax, [ebx+$0360]
00613170   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBGrid.OFFS_64
|
00613172   FF5164                 call    dword ptr [ecx+$64]
00613175   B201                   mov     dl, $01

* Reference to control TForm4.sBitBtn1 : TsBitBtn
|
00613177   8B8390030000           mov     eax, [ebx+$0390]
0061317D   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
0061317F   FF5164                 call    dword ptr [ecx+$64]
00613182   B201                   mov     dl, $01

* Reference to control TForm4.sBitBtn3 : TsBitBtn
|
00613184   8B8394030000           mov     eax, [ebx+$0394]
0061318A   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
0061318C   FF5164                 call    dword ptr [ecx+$64]
0061318F   B201                   mov     dl, $01

* Reference to control TForm4.sBitBtn4 : TsBitBtn
|
00613191   8B8398030000           mov     eax, [ebx+$0398]
00613197   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsBitBtn.OFFS_64
|
00613199   FF5164                 call    dword ptr [ecx+$64]
0061319C   B201                   mov     dl, $01

* Reference to control TForm4.sDBEdit19 : TsDBEdit
|
0061319E   8B836C030000           mov     eax, [ebx+$036C]
006131A4   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TsDBEdit.OFFS_64
|
006131A6   FF5164                 call    dword ptr [ecx+$64]
006131A9   8D55EC                 lea     edx, [ebp-$14]
006131AC   8B06                   mov     eax, [esi]
006131AE   8B8084090000           mov     eax, [eax+$0984]
006131B4   8B08                   mov     ecx, [eax]
006131B6   FF5160                 call    dword ptr [ecx+$60]
006131B9   8B45EC                 mov     eax, [ebp-$14]

* Possible String Reference to: '„ “ÊÃ…'
|
006131BC   BA30336100             mov     edx, $00613330

|
006131C1   E8C61CDFFF             call    00404E8C
006131C6   751A                   jnz     006131E2
006131C8   B201                   mov     dl, $01

* Reference to control TForm4.sPanel10 : TsPanel
|
006131CA   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible()
|
006131D0   E8730EE5FF             call    00464048
006131D5   B201                   mov     dl, $01

* Reference to control TForm4.sPanel16 : TsPanel
|
006131D7   8B8348030000           mov     eax, [ebx+$0348]

* Reference to: Controls.TControl.SetVisible()
|
006131DD   E8660EE5FF             call    00464048
006131E2   8D55E8                 lea     edx, [ebp-$18]
006131E5   8B06                   mov     eax, [esi]
006131E7   8B8084090000           mov     eax, [eax+$0984]
006131ED   8B08                   mov     ecx, [eax]
006131EF   FF5160                 call    dword ptr [ecx+$60]
006131F2   8B45E8                 mov     eax, [ebp-$18]

* Possible String Reference to: '„ÿ·ﬁ'
|
006131F5   BA40336100             mov     edx, $00613340

|
006131FA   E88D1CDFFF             call    00404E8C
006131FF   751A                   jnz     0061321B
00613201   B201                   mov     dl, $01

* Reference to control TForm4.sPanel10 : TsPanel
|
00613203   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible()
|
00613209   E83A0EE5FF             call    00464048
0061320E   B201                   mov     dl, $01

* Reference to control TForm4.sPanel16 : TsPanel
|
00613210   8B8348030000           mov     eax, [ebx+$0348]

* Reference to: Controls.TControl.SetVisible()
|
00613216   E82D0EE5FF             call    00464048
0061321B   8D55E4                 lea     edx, [ebp-$1C]
0061321E   8B06                   mov     eax, [esi]
00613220   8B8084090000           mov     eax, [eax+$0984]
00613226   8B08                   mov     ecx, [eax]
00613228   FF5160                 call    dword ptr [ecx+$60]
0061322B   8B45E4                 mov     eax, [ebp-$1C]

* Possible String Reference to: '„ÿ·ﬁ…'
|
0061322E   BA50336100             mov     edx, $00613350

|
00613233   E8541CDFFF             call    00404E8C
00613238   751A                   jnz     00613254
0061323A   B201                   mov     dl, $01

* Reference to control TForm4.sPanel10 : TsPanel
|
0061323C   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible()
|
00613242   E8010EE5FF             call    00464048
00613247   B201                   mov     dl, $01

* Reference to control TForm4.sPanel16 : TsPanel
|
00613249   8B8348030000           mov     eax, [ebx+$0348]

* Reference to: Controls.TControl.SetVisible()
|
0061324F   E8F40DE5FF             call    00464048
00613254   8D55E0                 lea     edx, [ebp-$20]
00613257   8B06                   mov     eax, [esi]
00613259   8B8084090000           mov     eax, [eax+$0984]
0061325F   8B08                   mov     ecx, [eax]
00613261   FF5160                 call    dword ptr [ecx+$60]
00613264   8B45E0                 mov     eax, [ebp-$20]

* Possible String Reference to: '√—„·'
|
00613267   BA60336100             mov     edx, $00613360

|
0061326C   E81B1CDFFF             call    00404E8C
00613271   751A                   jnz     0061328D
00613273   B201                   mov     dl, $01

* Reference to control TForm4.sPanel10 : TsPanel
|
00613275   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible()
|
0061327B   E8C80DE5FF             call    00464048
00613280   B201                   mov     dl, $01

* Reference to control TForm4.sPanel16 : TsPanel
|
00613282   8B8348030000           mov     eax, [ebx+$0348]

* Reference to: Controls.TControl.SetVisible()
|
00613288   E8BB0DE5FF             call    00464048
0061328D   8D55DC                 lea     edx, [ebp-$24]
00613290   8B06                   mov     eax, [esi]
00613292   8B8084090000           mov     eax, [eax+$0984]
00613298   8B08                   mov     ecx, [eax]
0061329A   FF5160                 call    dword ptr [ecx+$60]
0061329D   8B45DC                 mov     eax, [ebp-$24]

* Possible String Reference to: '√—„·…'
|
006132A0   BA70336100             mov     edx, $00613370

|
006132A5   E8E21BDFFF             call    00404E8C
006132AA   751A                   jnz     006132C6
006132AC   B201                   mov     dl, $01

* Reference to control TForm4.sPanel10 : TsPanel
|
006132AE   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible()
|
006132B4   E88F0DE5FF             call    00464048
006132B9   B201                   mov     dl, $01

* Reference to control TForm4.sPanel16 : TsPanel
|
006132BB   8B8348030000           mov     eax, [ebx+$0348]

* Reference to: Controls.TControl.SetVisible()
|
006132C1   E8820DE5FF             call    00464048
006132C6   33C0                   xor     eax, eax
006132C8   5A                     pop     edx
006132C9   59                     pop     ecx
006132CA   59                     pop     ecx
006132CB   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[ãÂ]√'
|
006132CE   68F0326100             push    $006132F0
006132D3   8D45DC                 lea     eax, [ebp-$24]
006132D6   BA08000000             mov     edx, $00000008

|
006132DB   E8C417DFFF             call    00404AA4
006132E0   8D45FC                 lea     eax, [ebp-$04]

|
006132E3   E89817DFFF             call    00404A80
006132E8   C3                     ret

006132E9   E97611DFFF             jmp     00404464
006132EE   EBE3                   jmp     006132D3

****** END
|
006132F0   5E                     pop     esi
006132F1   5B                     pop     ebx
006132F2   8BE5                   mov     esp, ebp
006132F4   5D                     pop     ebp
006132F5   C3                     ret

*)
end;

procedure TForm4.sBitBtn5Click(Sender : TObject);
begin
  //00613378
  Data.ABSconjoit.Cancel;
 sNotebook1.Visible:=false;
end;

procedure TForm4.sBitBtn6Click(Sender : TObject);
begin
  //0061339C
 with Data do begin
  if ABSconjoit.Modified then begin
          if not (ABSconjoit.State in dsWriteModes) then ABSconjoit.Post;
  end
  else begin
     ABSconjoit.Edit;
     ABSconjoit.UpdateRecord;
     ABSconjoit.Post;
  end;
  UpdateZawaj;
 end;
  sNotebook1.Visible:=false;
end;

procedure TForm4.sBitBtn7Click(Sender : TObject);
begin
  //00613EA8
   sNotebook1.Visible:=false;
end;

procedure TForm4.sBitBtn11Click(Sender : TObject);
begin
  //00613ECC
  Data.UpdateZawaj;
  sNotebook1.Visible:=false;
end;

procedure TForm4.sBitBtn12Click(Sender : TObject);
begin
  //006149D0
  
  Data.UpdateZawaj;

end;

procedure TForm4.FormShow(Sender : TObject);
begin
  sNotebook1.Visible :=False;
(*
00618E20   53                     push    ebx
00618E21   8BD8                   mov     ebx, eax
00618E23   6A13                   push    $13

* Reference to field TForm4.OFFS_004C
|
00618E25   8B434C                 mov     eax, [ebx+$4C]
00618E28   50                     push    eax

* Reference to field TForm4.OFFS_0048
|
00618E29   8B4348                 mov     eax, [ebx+$48]
00618E2C   50                     push    eax

* Reference to field TForm4.OFFS_0044
|
00618E2D   8B4344                 mov     eax, [ebx+$44]
00618E30   50                     push    eax

* Reference to field TForm4.OFFS_0040
|
00618E31   8B4340                 mov     eax, [ebx+$40]
00618E34   50                     push    eax
00618E35   6AFF                   push    $FF
00618E37   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
00618E39   E8521DE5FF             call    0046AB90
00618E3E   50                     push    eax

* Reference to: user32.SetWindowPos()
|
00618E3F   E87CF0DEFF             call    00407EC0
00618E44   5B                     pop     ebx
00618E45   C3                     ret

*)
end;

procedure TForm4.Timer1Timer(Sender : TObject);
begin
  //00618E48
  Form4.sLabelFX21.Visible:= not Form4.sLabelFX21.Visible;
end;

procedure TForm4._PROC_006118FC(Sender : TObject);
begin
(*
006118FC   55                     push    ebp
006118FD   8BEC                   mov     ebp, esp
006118FF   83C4F4                 add     esp, -$0C
00611902   FF7514                 push    dword ptr [ebp+$14]
00611905   FF7510                 push    dword ptr [ebp+$10]
00611908   8D4DFC                 lea     ecx, [ebp-$04]
0061190B   8D55FE                 lea     edx, [ebp-$02]
0061190E   8D45FA                 lea     eax, [ebp-$06]

|
00611911   E8B2A2DFFF             call    0040BBC8
00611916   FF750C                 push    dword ptr [ebp+$0C]
00611919   FF7508                 push    dword ptr [ebp+$08]
0061191C   8D4DF4                 lea     ecx, [ebp-$0C]
0061191F   8D55F6                 lea     edx, [ebp-$0A]
00611922   8D45F8                 lea     eax, [ebp-$08]

|
00611925   E89EA2DFFF             call    0040BBC8
0061192A   668B45FA               mov     ax, word ptr [ebp-$06]
0061192E   663B45F8               cmp     ax, word ptr [ebp-$08]
00611932   7518                   jnz     0061194C
00611934   668B45FE               mov     ax, word ptr [ebp-$02]
00611938   663B45F6               cmp     ax, word ptr [ebp-$0A]
0061193C   750E                   jnz     0061194C
0061193E   668B45FC               mov     ax, word ptr [ebp-$04]
00611942   663B45F4               cmp     ax, word ptr [ebp-$0C]
00611946   7504                   jnz     0061194C
00611948   33C0                   xor     eax, eax
0061194A   EB2C                   jmp     00611978
0061194C   0FB745F8               movzx   eax, word ptr [ebp-$08]
00611950   0FB755FA               movzx   edx, word ptr [ebp-$06]
00611954   2BC2                   sub     eax, edx
00611956   668B55FE               mov     dx, word ptr [ebp-$02]
0061195A   663B55F6               cmp     dx, word ptr [ebp-$0A]
0061195E   7603                   jbe     00611963
00611960   48                     dec     eax
00611961   EB15                   jmp     00611978
00611963   668B55FE               mov     dx, word ptr [ebp-$02]
00611967   663B55F6               cmp     dx, word ptr [ebp-$0A]
0061196B   750B                   jnz     00611978
0061196D   668B55FC               mov     dx, word ptr [ebp-$04]
00611971   663B55F4               cmp     dx, word ptr [ebp-$0C]
00611975   7601                   jbe     00611978
00611977   48                     dec     eax
00611978   8BE5                   mov     esp, ebp
0061197A   5D                     pop     ebp
0061197B   C21000                 ret     $0010

*)
end;

procedure TForm4._PROC_00612640(Sender : TObject);
begin
(*
00612640   00401C                 add     [eax+$1C], al
00612643   46                     inc     esi
00612644   0000                   add     [eax], al

*)
end;

procedure TForm4._PROC_00618E69(Sender : TObject);
begin
(*
00618E69   8BEC                   mov     ebp, esp
00618E6B   33C0                   xor     eax, eax
00618E6D   55                     push    ebp

* Possible String Reference to: 'È“µﬁˇÎ¯]√ã¿É-<3k'
|
00618E6E   688D8E6100             push    $00618E8D
00618E73   64FF30                 push    dword ptr fs:[eax]
00618E76   648920                 mov     fs:[eax], esp
00618E79   FF053C336B00           inc     dword ptr [$006B333C]
00618E7F   33C0                   xor     eax, eax
00618E81   5A                     pop     edx
00618E82   59                     pop     ecx
00618E83   59                     pop     ecx
00618E84   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-<3k'
|
00618E87   68948E6100             push    $00618E94
00618E8C   C3                     ret

00618E8D   E9D2B5DEFF             jmp     00404464
00618E92   EBF8                   jmp     00618E8C

****** END
|
00618E94   5D                     pop     ebp
00618E95   C3                     ret

*)
end;

procedure TForm4._PROC_00618E98(Sender : TObject);
begin
(*
00618E98   832D3C336B0001         sub     dword ptr [$006B333C], +$01
00618E9F   C3                     ret

*)
end;

procedure TForm4._PROC_00618EA0(Sender : TObject);
begin
(*
00618EA0   EC                     in      al, dx
00618EA1   8E6100                 mov     fs, word ptr [ecx+$00]
00618EA4   0000                   add     [eax], al

*)
end;

procedure TForm4.FormCreate(Sender: TObject);
begin
 //=====
  sDBComboBox1Change(self);

end;

procedure TForm4.sDBComboBox1Change(Sender: TObject);
begin
  //ShowMessage(sDBComboBox1.Text);
 if (sDBComboBox1.Text = '√⁄“»') or (sDBComboBox1.Text = '⁄“»«¡') then
 begin
  sBitBtn8.Enabled := false;
  sBitBtn9.Enabled := false;
  sBitBtn10.Enabled := false;
  sDBGrid1.Enabled := false;
 end
 else
 begin
  sBitBtn8.Enabled := True;
  sBitBtn9.Enabled := True;
  sBitBtn10.Enabled := True;
  sDBGrid1.Enabled := True;
 end;
end;

end.
