unit Unit45;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, QuickRpt, QRCtrls, ExtCtrls;
type
  TForm45=class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel27: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel40: TQRLabel;
    QRLabel41: TQRLabel;
    QRShape50: TQRShape;
    QRLabel54: TQRLabel;
    QRShape27: TQRShape;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRSubDetail3: TQRSubDetail;
    QRShape8: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRShape33: TQRShape;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRShape55: TQRShape;
    QRDBText18: TQRDBText;
    QRDBText43: TQRDBText;
    QRDBText44: TQRDBText;
    QRDBText21: TQRDBText;
    SummaryBand1: TQRBand;
    QRShape34: TQRShape;
    QRShape42: TQRShape;
    QRShape44: TQRShape;
    QRShape46: TQRShape;
    QRLabel48: TQRLabel;
    QRDBText27: TQRDBText;
    QRDBText29: TQRDBText;
    QRDBText32: TQRDBText;
    QRDBText34: TQRDBText;
    QRDBText35: TQRDBText;
    QRDBText37: TQRDBText;
    QRDBText38: TQRDBText;
    QRDBText39: TQRDBText;
    QRShape53: TQRShape;
    QRDBText33: TQRDBText;
    QRLabel3: TQRLabel;
    QRShape13: TQRShape;
    QRLabel4: TQRLabel;
    QRShape49: TQRShape;
    QRLabel5: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel53: TQRLabel;
    QRLabel55: TQRLabel;
    QRLabel56: TQRLabel;
    QRLabel57: TQRLabel;
    QRLabel58: TQRLabel;
    QRLabel59: TQRLabel;
    QRLabel60: TQRLabel;
    QRLabel61: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRShape26: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel24: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel2: TQRLabel;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText10: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText13: TQRDBText;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel23: TQRLabel;
    QRLabel1: TQRLabel;
    QRDBText16: TQRDBText;
    QRDBText17: TQRDBText;
    QRDBText36: TQRDBText;
    QRDBText19: TQRDBText;
    QRLabel34: TQRLabel;
    QRShape1: TQRShape;
    QRLabel36: TQRLabel;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRLabel37: TQRLabel;
    QRLabel38: TQRLabel;
    QRLabel42: TQRLabel;
    procedure _PROC_00673EAC(Sender : TObject);
    procedure _PROC_00673EB4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form45: TForm45;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm45._PROC_00673EAC(Sender : TObject);
begin
(*
00673EAC   832D48366B0001         sub     dword ptr [$006B3648], +$01
00673EB3   C3                     ret

*)
end;

procedure TForm45._PROC_00673EB4(Sender : TObject);
begin
(*
00673EB4   003F                   add     [edi], bh
00673EB6   670000                 add     [bx+si], al
00673EB9   0000                   add     [eax], al

*)
end;

end.