unit Unit43;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TForm43=class(TForm)
    sPanel2: TsPanel;
    sImage4: TsImage;
    sLabelFX8: TsLabelFX;
    sSpeedButton2: TsSpeedButton;
    sPanel3: TsPanel;
    Edit2: TEdit;
    sLabelFX1: TsLabelFX;
    sPanel1: TsPanel;
    sSpeedButton1: TsSpeedButton;
    sBitBtn2: TsBitBtn;
    sBitBtn32: TsBitBtn;
    procedure FormShow(Sender : TObject);
    procedure _PROC_00611170(Sender : TObject);
    procedure _PROC_006111A0(Sender : TObject);
    procedure _PROC_006111A8(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form43: TForm43;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TForm43.FormShow(Sender : TObject);
begin
(*
00611148   53                     push    ebx
00611149   8BD8                   mov     ebx, eax
0061114B   6A13                   push    $13

* Reference to field TForm43.OFFS_004C
|
0061114D   8B434C                 mov     eax, [ebx+$4C]
00611150   50                     push    eax

* Reference to field TForm43.OFFS_0048
|
00611151   8B4348                 mov     eax, [ebx+$48]
00611154   50                     push    eax

* Reference to field TForm43.OFFS_0044
|
00611155   8B4344                 mov     eax, [ebx+$44]
00611158   50                     push    eax

* Reference to field TForm43.OFFS_0040
|
00611159   8B4340                 mov     eax, [ebx+$40]
0061115C   50                     push    eax
0061115D   6AFF                   push    $FF
0061115F   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
00611161   E82A9AE5FF             call    0046AB90
00611166   50                     push    eax

* Reference to: user32.SetWindowPos()
|
00611167   E8546DDFFF             call    00407EC0
0061116C   5B                     pop     ebx
0061116D   C3                     ret

*)
end;

procedure TForm43._PROC_00611170(Sender : TObject);
begin
(*
00611170   55                     push    ebp
00611171   8BEC                   mov     ebp, esp
00611173   33C0                   xor     eax, eax
00611175   55                     push    ebp

* Possible String Reference to: 'éÊ2ßÿëø]Ã‹Àƒ-$3k'
|
00611176   6895116100             push    $00611195
0061117B   64FF30                 push    dword ptr fs:[eax]
0061117E   648920                 mov     fs:[eax], esp
00611181   FF0524336B00           inc     dword ptr [$006B3324]
00611187   33C0                   xor     eax, eax
00611189   5A                     pop     edx
0061118A   59                     pop     ecx
0061118B   59                     pop     ecx
0061118C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-$3k'
|
0061118F   689C116100             push    $0061119C
00611194   C3                     ret

00611195   E9CA32DFFF             jmp     00404464
0061119A   EBF8                   jmp     00611194

****** END
|
0061119C   5D                     pop     ebp
0061119D   C3                     ret

*)
end;

procedure TForm43._PROC_006111A0(Sender : TObject);
begin
(*
006111A0   832D24336B0001         sub     dword ptr [$006B3324], +$01
006111A7   C3                     ret

*)
end;

procedure TForm43._PROC_006111A8(Sender : TObject);
begin
(*
006111A8   F4                     hlt
006111A9   116100                 adc     [ecx+$00], esp
006111AC   0000                   add     [eax], al

*)
end;

end.