unit Unit19;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtDlgs, sDialogs, DBCtrls,
  sDBLookupListBox, sLabel, sDBText, sEdit, sDBComboBox, Mask, sDBEdit,
  sGroupBox, ComCtrls, sPageControl, acPNG, ExtCtrls, acImage, Buttons,
  sBitBtn, sPanel;
type
  TForm19=class(TForm)
    sPanel4: TsPanel;
    sLabelFX4: TsLabelFX;
    sBitBtn2: TsBitBtn;
    sBitBtn32: TsBitBtn;
    sPanel1: TsPanel;
    sImage1: TsImage;
    sPageControl1: TsPageControl;
    sTabSheet1: TsTabSheet;
    sTabSheet2: TsTabSheet;
    sPanel2: TsPanel;
    sPanel3: TsPanel;
    sBitBtn3: TsBitBtn;
    sOpenPictureDialog1: TsOpenPictureDialog;
    sTabSheet3: TsTabSheet;
    sGroupBox1: TsGroupBox;
    sGroupBox2: TsGroupBox;
    sLabelFX1: TsLabelFX;
    sLabelFX2: TsLabelFX;
    sLabelFX3: TsLabelFX;
    sDBComboBox1: TsDBComboBox;
    sLabelFX5: TsLabelFX;
    sLabelFX6: TsLabelFX;
    sLabelFX7: TsLabelFX;
    sDBText1: TsDBText;
    sDBText2: TsDBText;
    sImage2: TsImage;
    sImage3: TsImage;
    sImage4: TsImage;
    sImage5: TsImage;
    sDBEdit1: TsDBEdit;
    DBImage1: TDBImage;
    sDBEdit2: TsDBEdit;
    sEdit1: TsEdit;
    sEdit2: TsEdit;
    sDBLookupListBox1: TsDBLookupListBox;
    procedure sBitBtn2Click(Sender : TObject);
    procedure sBitBtn32Click(Sender : TObject);
    procedure sBitBtn3Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure sEdit1Change(Sender : TObject);
    procedure sEdit2Change(Sender : TObject);
    procedure _PROC_0065716D(Sender : TObject);
    procedure _PROC_00657484(Sender : TObject);
    procedure _PROC_006574B4(Sender : TObject);
    procedure _PROC_006574BC(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form19: TForm19;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation
      uses
         Unit2;
{$R *.DFM}

procedure TForm19.sBitBtn2Click(Sender : TObject);
begin
  //00656CF8
  Data.ABSUsers.Cancel;
  Close;
end;

procedure TForm19.sBitBtn32Click(Sender : TObject);
begin
  //00656D18
  with Data do begin
     ABSUsers.Edit;
     if(sEdit1.GetTextLen = 0)then begin
       if(sEdit1.Text = sEdit2.Text) then
           ShowMessage('ﬂ·„ « «·„—Ê— €Ì— „ ÿ«»ﬁ« «‰')
       else begin
       ABSUsersPassword.AsString:=sEdit1.Text;
       ABSUsers.Post;
       Close;
       end;

     end;

  end;


  Close;
 (*' „  ”ÃÌ· «·œŒÊ· ≈·Ï «·‰Ÿ«„ „‰ ÿ—› '
 'Administrateur'
 'Faysoft19852017+*/'
 'type=''
 ' „  ”ÃÌ· «·œŒÊ· ≈·Ï «·‰Ÿ«„ „‰ ÿ—› '
 'Administrateur'
 'Faysoft19852017+*/' *)

end;

procedure TForm19.sBitBtn3Click(Sender : TObject);
begin
(*
00657200   55                     push    ebp
00657201   8BEC                   mov     ebp, esp
00657203   6A00                   push    $00
00657205   53                     push    ebx
00657206   8BD8                   mov     ebx, eax
00657208   33C0                   xor     eax, eax
0065720A   55                     push    ebp
0065720B   685E726500             push    $0065725E
00657210   64FF30                 push    dword ptr fs:[eax]
00657213   648920                 mov     fs:[eax], esp

* Reference to control TForm19.sOpenPictureDialog1 : TsOpenPictureDialog
|
00657216   8B8328030000           mov     eax, [ebx+$0328]
0065721C   8B10                   mov     edx, [eax]

* Possible reference to virtual method TsOpenPictureDialog.OFFS_3C
|
0065721E   FF523C                 call    dword ptr [edx+$3C]
00657221   84C0                   test    al, al
00657223   7423                   jz      00657248
00657225   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TForm19.sOpenPictureDialog1 : TsOpenPictureDialog
|
00657228   8B8328030000           mov     eax, [ebx+$0328]

* Reference to: Dialogs.TOpenDialog.GetFileName()
|
0065722E   E8B515DEFF             call    004387E8
00657233   8B55FC                 mov     edx, [ebp-$04]

* Reference to TData instance
|
00657236   A1D8F06A00             mov     eax, dword ptr [$006AF0D8]
0065723B   8B00                   mov     eax, [eax]

* Reference to control TData.psPhoto : TGraphicField
|
0065723D   8B8064020000           mov     eax, [eax+$0264]

* Reference to: Comctrls.TCustomTreeView.LoadFromFile(System.AnsiString)
|
00657243   E8E8F9F3FF             call    00596C30
00657248   33C0                   xor     eax, eax
0065724A   5A                     pop     edx
0065724B   59                     pop     ecx
0065724C   59                     pop     ecx
0065724D   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ç@'
|
00657250   6865726500             push    $00657265
00657255   8D45FC                 lea     eax, [ebp-$04]

|
00657258   E823D8DAFF             call    00404A80
0065725D   C3                     ret

0065725E   E901D2DAFF             jmp     00404464
00657263   EBF0                   jmp     00657255

****** END
|
00657265   5B                     pop     ebx
00657266   59                     pop     ecx
00657267   5D                     pop     ebp
00657268   C3                     ret

*)
end;

procedure TForm19.FormShow(Sender : TObject);
begin
(*
0065726C   53                     push    ebx
0065726D   8BD8                   mov     ebx, eax
0065726F   6A13                   push    $13

* Reference to field TForm19.OFFS_004C
|
00657271   8B434C                 mov     eax, [ebx+$4C]
00657274   50                     push    eax

* Reference to field TForm19.OFFS_0048
|
00657275   8B4348                 mov     eax, [ebx+$48]
00657278   50                     push    eax

* Reference to field TForm19.OFFS_0044
|
00657279   8B4344                 mov     eax, [ebx+$44]
0065727C   50                     push    eax

* Reference to field TForm19.OFFS_0040
|
0065727D   8B4340                 mov     eax, [ebx+$40]
00657280   50                     push    eax
00657281   6AFF                   push    $FF
00657283   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
00657285   E80639E1FF             call    0046AB90
0065728A   50                     push    eax

* Reference to: user32.SetWindowPos()
|
0065728B   E8300CDBFF             call    00407EC0
00657290   5B                     pop     ebx
00657291   C3                     ret

*)
end;

procedure TForm19.sEdit1Change(Sender : TObject);
begin
(*
00657294   53                     push    ebx
00657295   8BD8                   mov     ebx, eax

* Reference to control TForm19.sEdit1 : TsEdit
|
00657297   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Comctrls.TToolBar.GetRowCount()
|
0065729D   E8FACDE0FF             call    0046409C
006572A2   85C0                   test    eax, eax
006572A4   7412                   jz      006572B8

* Reference to Form19
|
006572A6   A15C356B00             mov     eax, dword ptr [$006B355C]

* Reference to field Form19.OFFS_0360
|
006572AB   8B8060030000           mov     eax, [eax+$0360]
006572B1   B201                   mov     dl, $01

* Reference to: Controls.TControl.SetVisible()
|
006572B3   E890CDE0FF             call    00464048

* Reference to control TForm19.sEdit1 : TsEdit
|
006572B8   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Comctrls.TToolBar.GetRowCount()
|
006572BE   E8D9CDE0FF             call    0046409C
006572C3   85C0                   test    eax, eax
006572C5   753B                   jnz     00657302

* Reference to control TForm19.sEdit2 : TsEdit
|
006572C7   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Comctrls.TToolBar.GetRowCount()
|
006572CD   E8CACDE0FF             call    0046409C
006572D2   85C0                   test    eax, eax
006572D4   751A                   jnz     006572F0
006572D6   33D2                   xor     edx, edx

* Reference to control TForm19.sImage4 : TsImage
|
006572D8   8B8364030000           mov     eax, [ebx+$0364]

* Reference to: Controls.TControl.SetVisible()
|
006572DE   E865CDE0FF             call    00464048
006572E3   33D2                   xor     edx, edx

* Reference to control TForm19.sImage5 : TsImage
|
006572E5   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible()
|
006572EB   E858CDE0FF             call    00464048

* Reference to Form19
|
006572F0   A15C356B00             mov     eax, dword ptr [$006B355C]

* Reference to field Form19.OFFS_0360
|
006572F5   8B8060030000           mov     eax, [eax+$0360]
006572FB   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible()
|
006572FD   E846CDE0FF             call    00464048
00657302   5B                     pop     ebx
00657303   C3                     ret

*)
end;

procedure TForm19.sEdit2Change(Sender : TObject);
begin
(*
00657304   55                     push    ebp
00657305   8BEC                   mov     ebp, esp
00657307   33C9                   xor     ecx, ecx
00657309   51                     push    ecx
0065730A   51                     push    ecx
0065730B   51                     push    ecx
0065730C   51                     push    ecx
0065730D   51                     push    ecx
0065730E   51                     push    ecx
0065730F   51                     push    ecx
00657310   51                     push    ecx
00657311   53                     push    ebx
00657312   8BD8                   mov     ebx, eax
00657314   33C0                   xor     eax, eax
00657316   55                     push    ebp

* Possible String Reference to: 'ÈËœ⁄ˇÎÎ[ãÂ]√êUãÏ3¿Uh©te'
|
00657317   6877746500             push    $00657477
0065731C   64FF30                 push    dword ptr fs:[eax]
0065731F   648920                 mov     fs:[eax], esp

* Reference to control TForm19.sEdit2 : TsEdit
|
00657322   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Comctrls.TToolBar.GetRowCount()
|
00657328   E86FCDE0FF             call    0046409C
0065732D   85C0                   test    eax, eax
0065732F   0F848A000000           jz      006573BF
00657335   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TForm19.sEdit2 : TsEdit
|
00657338   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Controls.TControl.GetText()
|
0065733E   E8E5CDE0FF             call    00464128
00657343   8B45FC                 mov     eax, [ebp-$04]
00657346   50                     push    eax
00657347   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TForm19.sEdit1 : TsEdit
|
0065734A   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Controls.TControl.GetText()
|
00657350   E8D3CDE0FF             call    00464128
00657355   8B55F8                 mov     edx, [ebp-$08]
00657358   58                     pop     eax

|
00657359   E82EDBDAFF             call    00404E8C
0065735E   751A                   jnz     0065737A
00657360   B201                   mov     dl, $01

* Reference to control TForm19.sImage4 : TsImage
|
00657362   8B8364030000           mov     eax, [ebx+$0364]

* Reference to: Controls.TControl.SetVisible()
|
00657368   E8DBCCE0FF             call    00464048
0065736D   33D2                   xor     edx, edx

* Reference to control TForm19.sImage5 : TsImage
|
0065736F   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible()
|
00657375   E8CECCE0FF             call    00464048
0065737A   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TForm19.sEdit2 : TsEdit
|
0065737D   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Controls.TControl.GetText()
|
00657383   E8A0CDE0FF             call    00464128
00657388   8B45F4                 mov     eax, [ebp-$0C]
0065738B   50                     push    eax
0065738C   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TForm19.sEdit1 : TsEdit
|
0065738F   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Controls.TControl.GetText()
|
00657395   E88ECDE0FF             call    00464128
0065739A   8B55F0                 mov     edx, [ebp-$10]
0065739D   58                     pop     eax

|
0065739E   E8E9DADAFF             call    00404E8C
006573A3   741A                   jz      006573BF
006573A5   33D2                   xor     edx, edx

* Reference to control TForm19.sImage4 : TsImage
|
006573A7   8B8364030000           mov     eax, [ebx+$0364]

* Reference to: Controls.TControl.SetVisible()
|
006573AD   E896CCE0FF             call    00464048
006573B2   B201                   mov     dl, $01

* Reference to control TForm19.sImage5 : TsImage
|
006573B4   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible()
|
006573BA   E889CCE0FF             call    00464048

* Reference to control TForm19.sEdit2 : TsEdit
|
006573BF   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Comctrls.TToolBar.GetRowCount()
|
006573C5   E8D2CCE0FF             call    0046409C
006573CA   85C0                   test    eax, eax
006573CC   0F858A000000           jnz     0065745C
006573D2   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TForm19.sEdit2 : TsEdit
|
006573D5   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Controls.TControl.GetText()
|
006573DB   E848CDE0FF             call    00464128
006573E0   8B45EC                 mov     eax, [ebp-$14]
006573E3   50                     push    eax
006573E4   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TForm19.sEdit1 : TsEdit
|
006573E7   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Controls.TControl.GetText()
|
006573ED   E836CDE0FF             call    00464128
006573F2   8B55E8                 mov     edx, [ebp-$18]
006573F5   58                     pop     eax

|
006573F6   E891DADAFF             call    00404E8C
006573FB   751A                   jnz     00657417
006573FD   33D2                   xor     edx, edx

* Reference to control TForm19.sImage4 : TsImage
|
006573FF   8B8364030000           mov     eax, [ebx+$0364]

* Reference to: Controls.TControl.SetVisible()
|
00657405   E83ECCE0FF             call    00464048
0065740A   33D2                   xor     edx, edx

* Reference to control TForm19.sImage5 : TsImage
|
0065740C   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible()
|
00657412   E831CCE0FF             call    00464048
00657417   8D55E4                 lea     edx, [ebp-$1C]

* Reference to control TForm19.sEdit2 : TsEdit
|
0065741A   8B837C030000           mov     eax, [ebx+$037C]

* Reference to: Controls.TControl.GetText()
|
00657420   E803CDE0FF             call    00464128
00657425   8B45E4                 mov     eax, [ebp-$1C]
00657428   50                     push    eax
00657429   8D55E0                 lea     edx, [ebp-$20]

* Reference to control TForm19.sEdit1 : TsEdit
|
0065742C   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Controls.TControl.GetText()
|
00657432   E8F1CCE0FF             call    00464128
00657437   8B55E0                 mov     edx, [ebp-$20]
0065743A   58                     pop     eax

|
0065743B   E84CDADAFF             call    00404E8C
00657440   741A                   jz      0065745C
00657442   33D2                   xor     edx, edx

* Reference to control TForm19.sImage4 : TsImage
|
00657444   8B8364030000           mov     eax, [ebx+$0364]

* Reference to: Controls.TControl.SetVisible()
|
0065744A   E8F9CBE0FF             call    00464048
0065744F   B201                   mov     dl, $01

* Reference to control TForm19.sImage5 : TsImage
|
00657451   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible()
|
00657457   E8ECCBE0FF             call    00464048
0065745C   33C0                   xor     eax, eax
0065745E   5A                     pop     edx
0065745F   59                     pop     ecx
00657460   59                     pop     ecx
00657461   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[ãÂ]√êUãÏ3¿Uh©te'
|
00657464   687E746500             push    $0065747E
00657469   8D45E0                 lea     eax, [ebp-$20]
0065746C   BA08000000             mov     edx, $00000008

|
00657471   E82ED6DAFF             call    00404AA4
00657476   C3                     ret

00657477   E9E8CFDAFF             jmp     00404464
0065747C   EBEB                   jmp     00657469

****** END
|
0065747E   5B                     pop     ebx
0065747F   8BE5                   mov     esp, ebp
00657481   5D                     pop     ebp
00657482   C3                     ret

*)
end;

procedure TForm19._PROC_0065716D(Sender : TObject);
begin
(*
0065716D   7365                   jnb     006571D4
0065716F   7200                   jb      00657171
00657171   0000                   add     [eax], al

00657173   00FF                   add     bh, bh
00657175   FFFF                   DB  $FF, $FF  //      
00657177   FF12                   call    dword ptr [edx]
00657179   0000                   add     [eax], al

0065717B   004661                 add     [esi+$61], al
0065717E   7973                   jns     006571F3
00657180   6F                     outsd
00657181   667431                 jz      006571B5
00657184   3938                   cmp     [eax], edi
00657186   3532303137             xor     eax, $37313032
0065718B   2B2A                   sub     ebp, dword ptr [edx]
0065718D   2F                     das
0065718E   0000                   add     [eax], al

00657190   FFFF                   DB  $FF, $FF  //      
00657192   FFFF                   DB  $FF, $FF  //      
00657194   06                     push    es
00657195   0000                   add     [eax], al

00657197   00747970               add     [ecx+edi*2+$70], dh
0065719B   653D270000FF           cmp     eax, $FF000027
006571A1   FFFF                   DB  $FF, $FF  //      
006571A3   FF02                   inc     dword ptr [edx]
006571A5   0000                   add     [eax], al

006571A7   002A                   add     [edx], ch
006571A9   27                     daa
006571AA   0000                   add     [eax], al

006571AC   FFFF                   DB  $FF, $FF  //      
006571AE   FFFF                   DB  $FF, $FF  //      
006571B0   0400                   add     al, +$00
006571B2   0000                   add     [eax], al

006571B4   207C7C20               and     [esp+edi*2+$20], bh
006571B8   0000                   add     [eax], al

006571BA   0000                   add     [eax], al

006571BC   FFFF                   DB  $FF, $FF  //      
006571BE   FFFF                   DB  $FF, $FF  //      
006571C0   2200                   and     al, byte ptr [eax]
006571C2   0000                   add     [eax], al

006571C4   CA                     ret     

006571C5   E320                   jcxz    +$20
006571C7   CA                     ret     

006571C8   D3CC                   ror     esp, cl
006571CA   ED                     in      eax, dx
006571CB   E120                   loope   +$20
006571CD   C7E1CFCEE6E1           mov     ecx, $E1E6CECF
006571D3   20C5                   and     ch, al
006571D5   E1EC                   loope   -$14
006571D7   20C7                   and     bh, al
006571D9   E1E4                   loope   -$1C
006571DB   D9C7                   fld     st(0), st(7)
006571DD   E320                   jcxz    +$20
006571DF   E3E4                   jcxz    -$1C
006571E1   20D8                   and     al, bl
006571E3   D1DD                   rcr     ebp, 1
006571E5   2000                   and     [eax], al
006571E7   00FF                   add     bh, bh
006571E9   FFFF                   DB  $FF, $FF  //      
006571EB   FF0E                   dec     dword ptr [esi]
006571ED   0000                   add     [eax], al

006571EF   004164                 add     [ecx+$64], al
006571F2   6D                     insd
006571F3   696E6973747261         imul    ebp, [esi+$69], $61727473
006571FA   7465                   jz      00657261
006571FC   7572                   jnz     00657270
006571FE   0000                   add     [eax], al

00657200   55                     push    ebp
00657201   8BEC                   mov     ebp, esp
00657203   6A00                   push    $00
00657205   53                     push    ebx
00657206   8BD8                   mov     ebx, eax
00657208   33C0                   xor     eax, eax
0065720A   55                     push    ebp
0065720B   685E726500             push    $0065725E
00657210   64FF30                 push    dword ptr fs:[eax]
00657213   648920                 mov     fs:[eax], esp
00657216   8B8328030000           mov     eax, [ebx+$0328]
0065721C   8B10                   mov     edx, [eax]
0065721E   FF523C                 call    dword ptr [edx+$3C]
00657221   84C0                   test    al, al
00657223   7423                   jz      00657248
00657225   8D55FC                 lea     edx, [ebp-$04]
00657228   8B8328030000           mov     eax, [ebx+$0328]

* Reference to: Dialogs.TOpenDialog.GetFileName()
|
0065722E   E8B515DEFF             call    004387E8
00657233   8B55FC                 mov     edx, [ebp-$04]

* Reference to TData instance
|
00657236   A1D8F06A00             mov     eax, dword ptr [$006AF0D8]
0065723B   8B00                   mov     eax, [eax]

* Reference to control TData.psPhoto : TGraphicField
|
0065723D   8B8064020000           mov     eax, [eax+$0264]

* Reference to: Comctrls.TCustomTreeView.LoadFromFile(System.AnsiString)
|
00657243   E8E8F9F3FF             call    00596C30
00657248   33C0                   xor     eax, eax
0065724A   5A                     pop     edx
0065724B   59                     pop     ecx
0065724C   59                     pop     ecx
0065724D   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ç@'
|
00657250   6865726500             push    $00657265
00657255   8D45FC                 lea     eax, [ebp-$04]

|
00657258   E823D8DAFF             call    00404A80
0065725D   C3                     ret

0065725E   E901D2DAFF             jmp     00404464
00657263   EBF0                   jmp     00657255

****** END
|
00657265   5B                     pop     ebx
00657266   59                     pop     ecx
00657267   5D                     pop     ebp
00657268   C3                     ret

00657269   8D4000                 lea     eax, [eax+$00]
0065726C   53                     push    ebx
0065726D   8BD8                   mov     ebx, eax
0065726F   6A13                   push    $13
00657271   8B434C                 mov     eax, [ebx+$4C]
00657274   50                     push    eax
00657275   8B4348                 mov     eax, [ebx+$48]
00657278   50                     push    eax
00657279   8B4344                 mov     eax, [ebx+$44]
0065727C   50                     push    eax
0065727D   8B4340                 mov     eax, [ebx+$40]
00657280   50                     push    eax
00657281   6AFF                   push    $FF
00657283   8BC3                   mov     eax, ebx

* Reference to: Controls.TWinControl.GetHandle()
|
00657285   E80639E1FF             call    0046AB90
0065728A   50                     push    eax

* Reference to: user32.SetWindowPos()
|
0065728B   E8300CDBFF             call    00407EC0
00657290   5B                     pop     ebx
00657291   C3                     ret

*)
end;

procedure TForm19._PROC_00657484(Sender : TObject);
begin
(*
00657484   55                     push    ebp
00657485   8BEC                   mov     ebp, esp
00657487   33C0                   xor     eax, eax
00657489   55                     push    ebp

* Possible String Reference to: 'È∂œ⁄ˇÎ¯]√ã¿É-`5k'
|
0065748A   68A9746500             push    $006574A9
0065748F   64FF30                 push    dword ptr fs:[eax]
00657492   648920                 mov     fs:[eax], esp
00657495   FF0560356B00           inc     dword ptr [$006B3560]
0065749B   33C0                   xor     eax, eax
0065749D   5A                     pop     edx
0065749E   59                     pop     ecx
0065749F   59                     pop     ecx
006574A0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-`5k'
|
006574A3   68B0746500             push    $006574B0
006574A8   C3                     ret

006574A9   E9B6CFDAFF             jmp     00404464
006574AE   EBF8                   jmp     006574A8

****** END
|
006574B0   5D                     pop     ebp
006574B1   C3                     ret

*)
end;

procedure TForm19._PROC_006574B4(Sender : TObject);
begin
(*
006574B4   832D60356B0001         sub     dword ptr [$006B3560], +$01
006574BB   C3                     ret

*)
end;

procedure TForm19._PROC_006574BC(Sender : TObject);
begin
(*
006574BC   C074650003             DB  $C0, $74, $65, $00, $03  //      byte ptr [ebp+$00], $03
006574C1   0B547347               or      edx, [ebx+esi*2+$47]
006574C5   61                     popa
006574C6   7567                   jnz     0065752F
006574C8   654B                   dec     ebx
006574CA   696E6401000000         imul    ebp, [esi+$64], $00000001
006574D1   000400                 add     [eax+eax], al
006574D4   0000                   add     [eax], al

006574D6   BC74650006             mov     esp, $06006574
006574DB   676B546578             imul    edx, [si+$65], $78
006574E0   740F                   jz      006574F1
006574E2   676B486F72             imul    ecx, [bx+si+$6F], $72
006574E7   697A6F6E74616C         imul    edi, [edx+$6F], $6C61746E
006574EE   42                     inc     edx
006574EF   61                     popa
006574F0   720D                   jb      006574FF
006574F2   676B566572             imul    edx, [bp+$65], $72
006574F7   7469                   jz      00657562
006574F9   63616C                 arpl    [ecx+$6C], sp
006574FC   42                     inc     edx
006574FD   61                     popa
006574FE   7205                   jb      00657505
00657500   676B506965             imul    edx, [bx+si+$69], $65
00657505   08676B                 or      [edi+$6B], ah
00657508   4E                     dec     esi
00657509   6565646C               insb
0065750D   6506                   push    es
0065750F   7347                   jnb     00657558
00657511   61                     popa
00657512   7567                   jnz     0065757B
00657514   658D4000               lea     eax, gs:[eax+$00]
00657518   1C75                   sbb     al, $75
0065751A   650008                 add     gs:[eax], cl
0065751D   0F54                   DB  $0F, $54  //
0065751F   50                     push    eax
00657520   7269                   jb      0065758B
00657522   6E                     outsb
00657523   7454                   jz      00657579
00657525   657874                 js      0065759C
00657528   45                     inc     ebp
00657529   7665                   jbe     00657590
0065752B   6E                     outsb
0065752C   7400                   jz      0065752E
0065752E   0208                   add     cl, byte ptr [eax]
00657530   06                     push    es
00657531   53                     push    ebx
00657532   656E                   outsb
00657534   64657207               jb      0065753F
00657538   54                     push    esp
00657539   4F                     dec     edi
0065753A   626A65                 bound   ebp, qword ptr [edx+$65]
0065753D   6374010B               arpl    [ecx+eax+$0B], si
00657541   54                     push    esp
00657542   657874                 js      006575B9
00657545   54                     push    esp
00657546   6F                     outsd
00657547   50                     push    eax
00657548   7269                   jb      006575B3
0065754A   6E                     outsb
0065754B   7406                   jz      00657553
0065754D   53                     push    ebx
0065754E   7472                   jz      006575C2
00657550   696E6700941140         imul    ebp, [esi+$67], $40119400
00657557   000411                 add     [ecx+edx], al
0065755A   40                     inc     eax
0065755B   00A875650000           add     [eax+$6575], ch
00657561   0000                   add     [eax], al

00657563   0000                   add     [eax], al

00657565   0000                   add     [eax], al

00657567   0038                   add     [eax], bh
00657569   7665                   jbe     006575D0
0065756B   006876                 add     [eax+$76], ch
0065756E   650000                 add     gs:[eax], al
00657571   0000                   add     [eax], al

00657573   0000                   add     [eax], al

00657575   0000                   add     [eax], al

00657577   005276                 add     [edx+$76], dl
0065757A   65005A76               add     gs:[edx+$76], bl
0065757E   6500CC                 add     ah, cl
00657581   0100                   add     [eax], eax
00657583   006802                 add     [eax+$02], ch
00657586   46                     inc     esi
00657587   000C69                 add     [ecx+ebp*2], cl
0065758A   42                     inc     edx
0065758B   00589D                 add     [eax-$63], bl
0065758E   65006062               add     gs:[eax+$62], ah
00657592   42                     inc     edx
00657593   002C3F                 add     [edi+edi], ch
00657596   40                     inc     eax
00657597   008C554600683C         add     [ebp+edx*2+$3C680046], cl
0065759E   40                     inc     eax
0065759F   00843C40004497         add     [esp+edi+$97440040], al
006575A6   65006C6246             add     gs:[edx+$46], ch
006575AB   00645646               add     [esi+edx*2+$46], ah
006575AF   0088E14100C8           add     [eax+$C80041E1], cl
006575B5   9D                     pop     
006575B6   6500D0                 add     al, dl
006575B9   3546003C35             xor     eax, $353C0046
006575BE   46                     inc     esi
006575BF   0010                   add     [eax], dl
006575C1   3F                     aas
006575C2   46                     inc     esi
006575C3   002469                 add     [ecx+ebp*2], ah
006575C6   42                     inc     edx
006575C7   000C66                 add     [esi], cl
006575CA   42                     inc     edx
006575CB   000466                 add     [esi], al
006575CE   42                     inc     edx
006575CF   002C69                 add     [ecx+ebp*2], ch
006575D2   42                     inc     edx
006575D3   00A47B6500FC50         add     [ebx+edi*2+$50FC0065], ah
006575DA   46                     inc     esi
006575DB   00F8                   add     al, bh
006575DD   50                     push    eax
006575DE   46                     inc     esi
006575DF   00C8                   add     al, cl
006575E1   51                     push    ecx
006575E2   46                     inc     esi
006575E3   00443446               add     [esp+esi+$46], al
006575E7   00B03B460014           add     [eax+$1400463B], dh
006575ED   3B4600                 cmp     eax, [esi+$00]
006575F0   3C44                   cmp     al, $44
006575F2   46                     inc     esi
006575F3   008C3346009033         add     [ebx+esi+$33900046], cl
006575FA   46                     inc     esi
006575FB   000464                 add     [esp], al
006575FE   46                     inc     esi
006575FF   0030                   add     [eax], dh
00657601   6446                   inc     esi
00657603   00F8                   add     al, bh
00657605   3E46                   inc     esi
00657607   0008                   add     [eax], cl
00657609   3546008440             xor     eax, $40840046
0065760E   46                     inc     esi
0065760F   00FC                   add     ah, bh
00657611   3F                     aas
00657612   46                     inc     esi
00657613   0010                   add     [eax], dl
00657615   43                     inc     ebx
00657616   46                     inc     esi
00657617   00BC414600A097         add     [ecx+eax*2+$97A00046], bh
0065761E   6500B4644600FC45       add     gs:[esp+$45FC0046], dh
00657626   46                     inc     esi
00657627   00A8464600BC           add     [eax+$BC004646], ch
0065762D   3646                   inc     esi
0065762F   008846460060           add     [eax+$60004646], cl
00657635   7D65                   jnl     0065769C
00657637   000E                   add     [esi], cl
00657639   0000                   add     [eax], al

0065763B   0000                   add     [eax], al

0065763D   0002                   add     [edx], al
0065763F   0000                   add     [eax], al

00657641   000411                 add     [ecx+edx], al
00657644   40                     inc     eax
00657645   009001000004           add     [eax+$4000001], dl
0065764B   114000                 adc     [eax+$00], eax
0065764E   A801                   test    al, $01
00657650   0000                   add     [eax], al

00657652   0100                   add     [eax], eax
00657654   1400                   adc     al, $00
00657656   009D65000754           add     [ebp+$54070065], bl
0065765C   7347                   jnb     006576A5
0065765E   61                     popa
0065765F   7567                   jnz     006576C8
00657661   658BC0                 mov     eax, eax
00657664   6876650007             push    $07006576
00657669   07                     pop     es
0065766A   54                     push    esp
0065766B   7347                   jnb     006576B4
0065766D   61                     popa
0065766E   7567                   jnz     006576D7
00657670   65A875                 test    al, $75
00657673   65005C0346             add     gs:[ebx+eax+$46], bl
00657678   002B                   add     [ebx], ch
0065767A   0006                   add     [esi], al
0065767C   7347                   jnb     006576C5
0065767E   61                     popa
0065767F   7567                   jnz     006576E8
00657681   652000                 and     gs:[eax], al
00657684   98                     cwde 
00657685   E745                   out     $45, eax
00657687   005B00                 add     [ebx+$00], bl
0065768A   00FF                   add     bh, bh
0065768C   1436                   adc     al, $36
0065768E   46                     inc     esi
0065768F   0001                   add     [ecx], al
00657691   0000                   add     [eax], al

00657693   0000                   add     [eax], al

00657695   0000                   add     [eax], al

00657697   800000                 add     byte ptr [eax], $00
0065769A   0000                   add     [eax], al

0065769C   0B00                   or      eax, [eax]
0065769E   05416C6967             add     eax, +$67696C41
006576A3   6E                     outsb
006576A4   C0EE45                 shr     dh, $45
006576A7   006100                 add     [ecx+$00], ah
006576AA   00FF                   add     bh, bh
006576AC   54                     push    esp
006576AD   3446                   xor     al, $46
006576AF   00F0                   add     al, dh
006576B1   3446                   xor     al, $46
006576B3   0000                   add     [eax], al

006576B5   0000                   add     [eax], al

006576B7   800300                 add     byte ptr [ebx], $00
006576BA   0000                   add     [eax], al

006576BC   0C00                   or      al, $00
006576BE   07                     pop     es
006576BF   41                     inc     ecx
006576C0   6E                     outsb
006576C1   63686F                 arpl    [eax+$6F], bp
006576C4   7273                   jb      00657739
006576C6   68EF450074             push    $740045EF
006576CB   0000                   add     [eax], al

006576CD   FF4C6646               dec     dword ptr [esi+$46]
006576D1   0001                   add     [ecx], al
006576D3   0000                   add     [eax], al

006576D5   0000                   add     [eax], al

006576D7   0000                   add     [eax], al

006576D9   800000                 add     byte ptr [eax], $00
006576DC   00800D000B43           add     [eax+$430B000D], al
006576E2   6F                     outsd
006576E3   6E                     outsb
006576E4   7374                   jnb     0065775A
006576E6   7261                   jb      00657749
006576E8   696E7473001040         imul    ebp, [esi+$74], $40100073
006576EF   005000                 add     [eax+$00], dl
006576F2   00FE                   add     dh, bh
006576F4   640000                 add     fs:[eax], al
006576F7   FE94                   DB  $FE, $94  //      
006576F9   61                     popa
006576FA   46                     inc     esi
006576FB   0000                   add     [eax], al

006576FD   0000                   add     [eax], al

006576FF   800100                 add     byte ptr [ecx], $00
00657702   0000                   add     [eax], al

00657704   0E                     push    cs
00657705   0007                   add     [edi], al
00657707   45                     inc     ebp
00657708   6E                     outsb
00657709   61                     popa
0065770A   626C6564               bound   ebp, qword ptr [ebp+$64]
0065770E   888342006800           mov     [ebx+$680042], al
00657714   00FF                   add     bh, bh
00657716   1C42                   sbb     al, $42
00657718   46                     inc     esi
00657719   002C42                 add     [edx+eax*2], ch
0065771C   46                     inc     esi
0065771D   0000                   add     [eax], al

0065771F   0000                   add     [eax], al

00657721   800000                 add     byte ptr [eax], $00
00657724   00800F000446           add     [eax+$4604000F], al
0065772A   6F                     outsd
0065772B   6E                     outsb
0065772C   7400                   jz      0065772E
0065772E   104000                 adc     [eax+$00], al
00657731   59                     pop     ecx
00657732   0000                   add     [eax], al


* Possible reference to virtual method T+$46].OFFS_46
|
00657734   FF544246               call    dword ptr [edx+eax*2+$46]
00657738   0001                   add     [ecx], al
0065773A   0000                   add     [eax], al

0065773C   0000                   add     [eax], al

0065773E   0000                   add     [eax], al

00657740   800100                 add     byte ptr [ecx], $00
00657743   0000                   add     [eax], al

00657745   1000                   adc     [eax], al
00657747   0A5061                 or      dl, byte ptr [eax+$61]
0065774A   7265                   jb      006577B1
0065774C   6E                     outsb
0065774D   7446                   jz      00657795
0065774F   6F                     outsd
00657750   6E                     outsb
00657751   7400                   jz      00657753
00657753   104000                 adc     [eax+$00], al
00657756   9A0000FF9C             call    $9CFF0000
0065775B   42                     inc     edx
0065775C   46                     inc     esi
0065775D   0001                   add     [ecx], al
0065775F   0000                   add     [eax], al

00657761   0000                   add     [eax], al

00657763   0000                   add     [eax], al

00657765   800100                 add     byte ptr [ecx], $00
00657768   0000                   add     [eax], al

0065776A   1100                   adc     [eax], eax
0065776C   0E                     push    cs
0065776D   50                     push    eax
0065776E   61                     popa
0065776F   7265                   jb      006577D6
00657771   6E                     outsb
00657772   7453                   jz      006577C7
00657774   686F774869             push    $6948776F
00657779   6E                     outsb
0065777A   7484                   jz      00657700
0065777C   384700                 cmp     [edi+$00], al
0065777F   7C00                   jl      00657781
00657781   00FF                   add     bh, bh
00657783   E040                   loopn   +$40
00657785   46                     inc     esi
00657786   0001                   add     [ecx], al
00657788   0000                   add     [eax], al

0065778A   0000                   add     [eax], al

0065778C   0000                   add     [eax], al

0065778E   800000                 add     byte ptr [eax], $00
00657791   008012000950           add     [eax+$50090012], al
00657797   6F                     outsd
00657798   7075                   jo      0065780F
0065779A   704D                   jo      006577E9
0065779C   656E                   outsb
0065779E   7500                   jnz     006577A0
006577A0   104000                 adc     [eax+$00], al
006577A3   99                     cdq
006577A4   0000                   add     [eax], al

006577A6   FF78                   DB  $FF, $78  //      
006577A8   42                     inc     edx
006577A9   46                     inc     esi
006577AA   004042                 add     [eax+$42], al
006577AD   46                     inc     esi
006577AE   0000                   add     [eax], al

006577B0   0000                   add     [eax], al

006577B2   800000                 add     byte ptr [eax], $00
006577B5   008013000853           add     [eax+$53080013], al
006577BB   686F774869             push    $6948776F
006577C0   6E                     outsb
006577C1   7400                   jz      006577C3
006577C3   104000                 adc     [eax+$00], al
006577C6   57                     push    edi
006577C7   0000                   add     [eax], al

006577C9   FF4840                 dec     dword ptr [eax+$40]
006577CC   46                     inc     esi
006577CD   00F4                   add     ah, dh
006577CF   61                     popa
006577D0   46                     inc     esi
006577D1   0000                   add     [eax], al

006577D3   0000                   add     [eax], al

006577D5   800100                 add     byte ptr [ecx], $00
006577D8   0000                   add     [eax], al

006577DA   1400                   adc     al, $00
006577DC   07                     pop     es
006577DD   56                     push    esi
006577DE   697369626C6530         imul    esi, [ebx+$69], $30656C62
006577E5   AB                     stosd
006577E6   41                     inc     ecx
006577E7   0020                   add     [eax], ah
006577E9   0100                   add     [eax], eax
006577EB   FF20                   jmp     dword ptr [eax]
006577ED   0100                   add     [eax], eax
006577EF   FF1462                 call    dword ptr [edx]
006577F2   46                     inc     esi
006577F3   0000                   add     [eax], al

006577F5   0000                   add     [eax], al

006577F7   800000                 add     byte ptr [eax], $00
006577FA   00801500074F           add     [eax+$4F070015], al
00657800   6E                     outsb
00657801   43                     inc     ebx
00657802   6C                     insb
00657803   69636B4CF74500         imul    esp, [ebx+$6B], $0045F74C
0065780A   3001                   xor     [ecx], al
0065780C   00FF                   add     bh, bh
0065780E   3001                   xor     [ecx], al
00657810   00FF                   add     bh, bh
00657812   0100                   add     [eax], eax
00657814   0000                   add     [eax], al

*)
end;

end.